### DISCUSSION TITLE
Traefik | ForwardAuth | no certificate issued

### DISCUSSION THREAD

**Discussion by Maximilian-Pfau-P** [thomseddon/traefik-forward-auth#262] [Q&A]
First of all I would like to thank you for this project, it has helped us a lot in our security efforts. I'm using this container with the Google OAuth client which is working fine so far. 

We think, that the problem is that Traefik doesn't create certificates when the OAuth container is added to the IngressRoute as middleware. 
But for example the redirect URL after a successul login never get a certificate, even if we deploy it without the middleware. As CA we use Lets Encrypt with the DNS Challenge. As DNS we created a wildcard dns name for traefik, which is working fine for all the applications.

Since with a missing certificate of the authentication ingress route it cannot be used productively, I would be very grateful if someone could help me with this problem.

`````
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-forward-auth
  namespace: traefik
  labels:
    app: traefik
spec:
  entryPoints:
    - https
  routes:
  - match: Host(`auth.*)
    kind: Rule
    services:
    - name: traefik-forward-auth
      port: 4181
    middlewares:
    - name: traefik-forward-auth
      namespace: traefik
  tls:
    certresolver: letsencrypt
`````
