### DISCUSSION TITLE
_oauth/logout  doesn't clear cookie

### DISCUSSION THREAD

**Discussion by monehsieh** [thomseddon/traefik-forward-auth#372] [Q&A]
Hi,

I'm encountering an issue with logging out from traefik-forward-auth. 

I have it configured as follows:

```
COOKIE_DOMAINS=home.example.com 
AUTH_HOST=oauth.home.example.com
```

The `oauth.home.example.com` is pointed to traefik-forward-auth's router. 

I have entrypoints set to use
```
entryPoints:
  websecure:
    address: :443
    http:
      middlewares: 
        - forwardAuth@file
```

forwardAuth@file is defined as follows
```
http:
    forwardAuth:
      forwardauth:
        address: http://traefik-forward-auth:4181
        trustForwardHeader: true
        authResponseHeaders: 
          = "X-Forwarded-User"
```

I can successfully Single Sign-On (SSO) with Google on the whoami service, but I am unable to log out.

After logging out from Google, I can't clear the `_forward_auth` cookie from the browser using the paths `whoami.home.example.com/_oauth/logout` nor `oauth.home.example.com/_oauth/logout`. 

I also even tried `home.example.com/_oauth/logout` which points to a homepage docker container and is configured with `- "traefik.http.routers.homepage.middlewares=forwardAuth@file"`.  It doesn't remove the cookie either.

Can anyone provide guidance on how to properly log out and remove the _forward_auth cookie from the browser? Any help would be greatly appreciated!

Thanks in advance,
Mone
