### DISCUSSION TITLE
how to set a custom not authorized page

### DISCUSSION THREAD

**Discussion by ivanjx** [thomseddon/traefik-forward-auth#390] [Q&A] [answered]
i already set up a nginx container that has `/401.html` page. here is my dynamic config:

```yml
  routers:
    to-service:
      rule: "Host(`service.com`)"
      service: service
      middlewares:
        - mw-auth
        - mw-errors

  middlewares:
    mw-auth:
      forwardAuth:
        address: "http://traefik-forward-auth:4181"
        authResponseHeaders:
          - "X-Forwarded-User"

    mw-errors:
      errors:
        status:
          - 401
        service: index
        query: "/{status}.html"

  services:
    index:
      loadBalancer:
        servers:
        - url: http://traefik-static:80

    service:
      loadBalancer:
        servers:
        - url: http://service:80

```

how to make traefik to show the custom html page on 401 errors from forward auth? it is still showing the default `Not authorized` string. thanks.
