### ISSUE TITLE
Question: How do I configure traefik/ traefik-auth to point to an external IP 

### ISSUE THREAD

**Issue by Rathna-K** [thomseddon/traefik-forward-auth#118]
Hello, my current setup is all docker containers are in an external network docker-network and SSO works like a charm for it, thank you! 
I am now looking to redirect to two sub domain URLs after auth is completed, 
1. to a container running in host network mode which is in a different subnet than the docket-network 
2. to an ip address in the host network running a web service. 
are these two possible? if so can you help with how to get started? I have been scratching my head over this and I posted in traefik forums. someone helped me there till they can but looks like now i am stuck ... 
here is the link to the original forum : 
[https://community.containo.us/t/forwarding-one-traefik-endpoint-to-dockers-host-network/5675/2](url)

if that is too long too long/ complicated I can start over with just a who am I running in host mode as well and go from there. any help is highly appreciated, thanks in advance!

**Comment by Rathna-K** [comment]
I didnt use toml file originally and everything is in docker-compose using labels. That was the recommendation in the other forum as well so I tried that and added a provider file just for this it but I must be missing something in that rules.toml file now. I am getting “middleware sts@file” does not exist.

**Comment by thomseddon** [comment]
Once authentication has completed, traefik-forward-auth (tfa) will redirect to whatever URL started the authentication flow.

So if you start with a request to `http://your.domain:port/path`, tfa will generate a redirect to your auth provider, the auth provider will redirect to `http://auth.host/_oauth` once authentication is (if your using auth host, it will just be `http://your.domian:port/_oauth` of not). If successfully authenticated, tfa will redirect back to `http://your.domain:port/path`.

In this sense, if your able to successfully complete the request without tfa (I would suggest removing it to test whilst your getting things setup), then as long as authentication is successful, it should work with tfa too.

If I've misunderstood something here, please let me know, but from my understanding this doesn't sound like an issue with tfa per se.

**Comment by Rathna-K** [comment]
yes but i think the part where i am stuck is how to redirect to a network outside of docker network such as to a host container running in host mode or an IP in the host LAN network. here is my current compose files for reference: 
traefik compose: 
```
version: "3.3"
services:
  traefik:
    image: traefik:latest
    container_name: "traefik"
    restart: always
    command:
      - "--global.sendAnonymousUsage=false"
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=myemail"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.websecure.http.middlewares=sts"
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.middlewares=auth
      - traefik.http.middlewares.sts.headers.stspreload=true
      - traefik.http.middlewares.sts.headers.stsseconds=31536000
    ports:
      - "80:80"
      - "443:443"
    networks:
      docker-network:
        aliases:
          - traefik
    volumes:
      - ".traefik_data/:/letsencrypt"
      - "./traefik_data/.htpasswd:/auth/.htpasswd"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
networks:
  docker-network:
    external: true
```
traefik-auth compose: 
```
version: "3.3"
services:
  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:2.1-arm
    container_name: "traefik-auth"
    restart: always
    environment:
      - DEFAULT_PROVIDER=oidc
      - PROVIDERS_OIDC_ISSUER_URL=https://login.microsoftonline.com/{tenant-id}/v2.0
      - PROVIDERS_OIDC_CLIENT_ID={clientid}
      - PROVIDERS_OIDC_CLIENT_SECRET={secret}
      - SECRET={secret}
      - DOMAIN={my domain name}
      - LOG_LEVEL=debug
      - AUTH_HOST=traefik-forward-auth.{my domain name}
    networks:
      docker-network:
        aliases:
          - traefik-auth
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-forward-auth.middlewares=auth
      - traefik.http.routers.traefik-forward-auth.entrypoints=websecure
      - traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4282
      - traefik.http.middlewares.auth.forwardauth.address=http://traefik-forward-auth:4282
      - traefik.http.middlewares.auth.forwardauth.authresponseheaders=X-Forwarded-User
networks:
  docker-network:
    external: true
```
home assistant  compose: 
```
version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    networks:
      docker-network:
        aliases:
          - homeassistant
    ports: 
      - 8123:8123
    volumes:
      - .homeassistant_data:/config
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.port=8123"
      - "traefik.http.middlewares.ha.redirectscheme.scheme=https"
      - "traefik.http.routers.ha.middlewares=auth"
      - "traefik.http.routers.ha-insecure.rule=Host(`hassio.{my domain name}`)"
      - "traefik.http.routers.ha-insecure.middlewares=ha"
      - "traefik.http.routers.ha.rule=Host(`hassio.{my domain name}`)"
      - "traefik.http.routers.ha.entrypoints=websecure"
      - "traefik.http.routers.ha.tls.certresolver=myresolver"
      - "traefik.http.services.ha.loadBalancer.server.port=8123"

networks:
  docker-network:
    external: true
```
