### ISSUE TITLE
Code exchange failed with provider

### ISSUE THREAD

**Issue by mivandev** [thomseddon/traefik-forward-auth#128]
I am trying to set this up with my docker containers. I followed this guide [https://www.smarthomebeginner.com/google-oauth-with-traefik-docker/#Step_2_Configure_Google_OAuth2_Service](url) to setup my OAuth app and my docker-compose files (listed below). Unfortunately, I am not able to authenticate. The login screen does appear when I visit ```traefik.example.com```, however, after entering my whitelisted email and password, ```service unavailable``` is shown in the webpage. 

In the log of ```traefik-forward-auth``` docker the following is shown:
```
time="2020-05-24T19:01:08Z" level=error msg="Code exchange failed with provider" error="Post https://www.googleapis.com/oauth2/v3/token: dial tcp: lookup www.googleapis.com on 127.0.0.11:53: read udp 127.0.0.1:46090->127.0.0.11:53: i/o timeout" handler=AuthCallback host=auth.example.com method=GET proto=https rule=default source_ip="[MY-IP-REDACTED], 162.158.158.152" uri="/_oauth?state=5a96bf2398378b30fad1bb669dcb69b7:google:https://traefik.example.com/&code=4/0AEiL3aUCC6-TRQ5Rn9PeN0l5o8eouAk9RP627FoASLxVybnqFBjORJGXfUhUSs-QcIQVbSNc9WQylUACvpqRgc&scope=email%20profile%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email%20openid&authuser=1&hd=example.com&prompt=consent"
```
 Of course, I have redacted my IP address in the code above, and I naturally used my own domain name instead of example.com.

I have tried:
- Creating a new Google project and a new oauth webapp
- Different browsers, so its not due to cookies or cache
- Logging in with different devices on another network, so my IP is not banned with Google

Does any of you have an idea where this error might arise from, and how it can be solved?
Much obliged!
```
version: "2"
services:
  traefik:
    hostname: traefik
    image: traefik:v1.7.16-alpine
    container_name: traefik
    restart: always
    domainname: example.com
    networks:
      - default # internal network
      - my-net	# traefik proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - CF_API_EMAIL=email@example.com
      - CF_API_KEY=my-secret-api
    command:
      - --accessLog.filePath=/var/log/access.log 
      - --accessLog.filters.statusCodes=400-499
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.example.com"  
#      - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /traefik"
      - "traefik.port=8080"
      - "traefik.docker.network=my-net"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=tiddl.net"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.auth.forward.address=http://oauth:4181"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User"
      - "traefik.frontend.auth.forward.trustForwardHeader=true"
    volumes:
      - /mydir/docker.sock:/var/run/docker.sock:ro
      - /mydir/traefik/:/etc/traefik
      - /mydir/shared:/shared
      - /var/log/traefik:/var/log  


## OAuth - Forward Authentication
  oauth:
    image: thomseddon/traefik-forward-auth
    container_name: oauth
    hostname: oauth
    restart: always
    networks:
      - default
      - my-net
    environment:
      - PROVIDERS_GOOGLE_CLIENT_ID=super-secret-code
      - PROVIDERS_GOOGLE_CLIENT_SECRET=even-more-secret
      - SECRET=random-secret-sequence
      - COOKIE_DOMAIN=example.com
      - INSECURE_COOKIE="false"
      - AUTH_HOST=auth.example.com
      - URL_PATH=/_oauth
      - WHITELIST=email@example.com
      - LOG_LEVEL=info
      - LIFETIME=2592000 # 30 days
    labels:
      - "traefik.enable=true"
      - "traefik.backend=oauth"
      - "traefik.port=4181"
      - "traefik.frontend.rule=Host:auth.example.com"
      - "traefik.frontend.headers.SSLHost=auth.example.com"
      - "traefik.docker.network=my-net"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.headers.SSLForceHost=true"
      - "traefik.frontend.headers.customResponseHeaders=X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.auth.forward.address=http://oauth:4181"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User"
      - "traefik.frontend.auth.forward.trustForwardHeader=true"

networks:
  my-net:
    external:
      name: my-net
  default:
    driver: bridge
 ```
