### ISSUE TITLE
Port mismatch on internal keycloak server as OICD provider

### ISSUE THREAD

**Issue by goost** [thomseddon/traefik-forward-auth#134]
Hi, 

thanks for the project! I have a configuration error and cannot seem to wrap my head around it. The setup is as follows:

Traefik2 is used as a proxy for all services, including a self-hosted Keycloak instance.
Traefik2 is only reachable when connected via a VPN (which propagates a custom DNS server), not externally.

This means that all services which need to communicate with one another do so via the internal docker network, using container names as hosts.

Now, traefik-forward-auth needs to communicate with Keycloak and traefik-forward-auth needs to forward clients correctly. Currently, I can only set one URL via `PROVIDERS_OIDC_ISSUER_URL`. If I set the correct URL for the client, `https://keycloak.example.com/auth/realms/master` traefik-forward-auth cannot start as this URL is not valid because all internal communications on the docker network are via HTTP, not HTTPS. I usually cheat and give the containers a name which is the same as the external URL and only specify connections with http, e.g. `http://keycloak.example.com/auth/realms/master`.  
As traefik2 automatically redirects clients from HTTP to HTTPS this works fine internally and externally. Unfortunately, this does not work in this case as the internal Keycloak port is 8080, meaning, the correct URL for internal is `http://keycloak.example.com:8080/auth/realms/master`.
Setting this, traefik-forward-auth starts fine but now clients get redirected to a wrong port which has no entrypoint.

Changing the port of the Keycloak container was so far unsuccessful and requires running it as root, which is not desirable.

Any ideas how I can configure this correctly?

Traefik Compose File
```yml
version: "3.8"
services:
  app:
    image: traefik:v2.2
    read_only: true
    restart: always
    container_name: traefik.example.com
    command:
      - --api.dashboard=true
      - --global.sendanonymoususage=false
      - --log.level=debug
      - --providers.docker
      - --providers.docker.endpoint=tcp://socket-proxy:2375
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=docker-net-proxy
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.middlewares=secheaders@docker,compress@docker
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certresolver=resolver
      - --entrypoints.websecure.http.tls.domains[0].main=*.example.com
      - --entrypoints.websecure.http.tls.domains[0].sans=example.com
      - --certificatesresolvers.resolver.acme.dnschallenge=true
      - --certificatesresolvers.resolver.acme.dnschallenge.provider=<provider>
      - --certificatesresolvers.resolver.acme.dnschallenge.resolvers=<redacted>
      - --certificatesresolvers.resolver.acme.dnschallenge.delayBeforeCheck=10
      - --certificatesresolvers.resolver.acme.email=<email>
      - --certificatesresolvers.resolver.acme.storage=/letsencrypt/acme.json
    environment:
      - CF_DNS_API_TOKEN=<token>
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      # Dashboard & API
      - "traefik.http.routers.traefik.rule=Host(`traefik.example.com`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.middlewares=dashboardauth"
      - "traefik.http.middlewares.dashboardauth.basicauth.users=admin:<redacted>"
      # Secure HTTP Headers
      - "traefik.http.middlewares.secheaders.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.secheaders.headers.sslredirect=true"
      - "traefik.http.middlewares.secheaders.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.compress.compress=true"
    volumes:
      - ${PWD}/mount/acme.json:/letsencrypt/acme.json
    networks:
      default:
      vpn:
        ipv4_address: 172.15.15.3
      proxy:

  socket-proxy:
    image: tecnativa/docker-socket-proxy
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    security_opt:
      - no-new-privileges:true
    environment:
      SERVICES: 1
      NETWORKS: 1
      CONTAINERS: 1
      INFO: 1

  forward-auth:
    image: thomseddon/traefik-forward-auth:2
    container_name: auth.example.com
    restart: always
    security_opt:
      - no-new-privileges:true
    environment:
      - PROVIDERS_OIDC_CLIENT_ID=traefik-forward-auth
      - PROVIDERS_OIDC_CLIENT_SECRET=<redacted>
      - PROVIDERS_OIDC_ISSUER_URL=http://keycloak.example.com:8080/auth/realms/master
      - LOG_LEVEL=debug
      - DEFAULT_PROVIDER=oidc
      - SECRET=<redacted>
      - AUTH_HOST=auth.example.com
      - COOKIE_DOMAIN=example.com
      - INSECURE_COOKIE=false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`auth.example.com`)"
      - "traefik.http.routers.auth.entrypoints=websecure"
      - "traefik.http.services.auth.loadbalancer.server.port=4181"
      - "traefik.http.middlewares.forward-auth.forwardauth.address=http://auth.example.com:4181"
      - "traefik.http.middlewares.forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
      - "traefik.http.middlewares.forward-auth.forwardauth.trustForwardHeader=true"
    networks:
      proxy:

networks:
  vpn:
    external:
      name: docker-net-wire
  proxy:
    external:
      name: docker-net-proxy
```

Keycloak compose

```yaml
version: "3.8"
services:
  app:
    image: jboss/keycloak
    restart: always
    container_name: keycloak.example.com
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.example.com`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
    environment:
      - DB_VENDOR=postgres
      - DB_DATABASE=<name>
      - DB_ADDR=db
      - DB_USER=<user>
      - DB_PASSWORD=<redacted>
      - KEYCLOAK_USER=<user>
      - KEYCLOAK_PASSWORD=<redacted>
      # This is required to run keycloak behind traefik
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_HOSTNAME=keycloak.example.com
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      default:
      proxy:

  db:
    image: postgres:12
    #read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - db-data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=<user>
      - POSTGRES_DB=<name>
      - POSTGRES_PASSWORD=<password>

volumes:
  db-data:
networks:
  proxy:
    external:
      name: docker-net-proxy
```
