### ISSUE TITLE
"unknown provider" error when using generic_oauth

### ISSUE THREAD

**Issue by natelandau** [thomseddon/traefik-forward-auth#144]
Super excited to use the OATH support released yesterday.  I can't seem to get it working though.  Starting up from my docker-compose file exits with the error `level=fatal msg="Unknown provider: "`

I am relatively certain something isn't set right in my compose file but I can't find it.  Here's the relevant yml

```yml
version: '3'

services:
  traefik-forward-auth:
    container_name: httpAuth
    hostname: httpAuth
    image: thomseddon/traefik-forward-auth:2.2
    ports:
      - "127.0.0.1:4181:4181"
    environment:
      - DEFAULT_PROVIDER="generic-oauth"
      - PROVIDERS_GENERIC_OAUTH_AUTH_URL="https://github.com/login/oauth/authorize"
      - PROVIDERS_GENERIC_OAUTH_TOKEN_URL="https://github.com/login/oauth/access_token"
      - PROVIDERS_GENERIC_OAUTH_USER_URL="https://api.github.com/user"
      - PROVIDERS_GENERIC_OAUTH_CLIENT_ID="[[ID]]"
      - PROVIDERS_GENERIC_OAUTH_CLIENT_SECRET="[[secret]]"
      - AUTH_HOST="https://auth.mysite.com/"
      - COOKIE_DOMAIN="mysite.com"
      - SECRET="[[secret]]"  
      - LOG_LEVEL=debug
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-forward-auth.rule=Host(`auth.mysite.com`)"
      - "traefik.http.routers.traefik-forward-auth.service=traefik-forward-auth"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.url=127.0.0.1"
      - "traefik.http.routers.traefik-forward-auth.entryPoints=web,websecure"
    networks:
      - web

networks:
  web:
    driver: bridge
```
