### ISSUE TITLE
Google auth loop

### ISSUE THREAD

**Issue by ptr727** [thomseddon/traefik-forward-auth#146]
Hi, I've seen several issues related to auth loops, but rather than jumping in there, I'll post my setup, and if a dupe, please point me in the right direction.

I'm using Ansible to configure docker, but the schema should be easy enough to follow.

Using CloudFlare for DNS, and have a wildcard CNAME pointing to my router with a 443 port forward to the docker server.
`*.insanegenius.net` == `home.insanegenius.net` == `[router IP]`
Using Google Apps custom domain with a single auth redirect URI `https://auth.insanegenius.net/_oauth`

When I hit `https://whoami.insanegenius.net` I am redirected to the Google login, on selecting my account I am again redirected to google, repeat.

I was reluctant to post the debug output as I don't know what secrets it contains, but I'll post specifics if need be.

Any ideas?

traefik.yml
```yaml
---
- name: 'Install Traefik'
  docker_container:
    name: traefik
    image: traefik
    pull: true
    hostname: traefik-{{ ansible_hostname }}
    domainname: home.insanegenius.net
    restart_policy: unless-stopped
    command:
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # HTTP port 80
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      # HTTPS port 443
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls.certresolver=dns-cloudflare"
      - "--entrypoints.websecure.http.tls.domains[0].main={{ ansible_fqdn }}"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.{{ ansible_domain }}"
      - "--entrypoints.websecure.http.tls.domains[1].main={{ external_domain }}"
      - "--entrypoints.websecure.http.tls.domains[1].sans=*.{{ external_domain }}"
      # SSL certs
      - "--certificatesresolvers.dns-cloudflare.acme.email={{ cloudflare_email }}"
      - "--certificatesresolvers.dns-cloudflare.acme.storage=/acme.json"
      - "--certificatesResolvers.dns-cloudflare.acme.dnschallenge.provider=cloudflare"
    env:
      CF_DNS_API_TOKEN: "{{ cloudflare_dns_api_token }}"
    volumes:
      - /data/appdata/traefik/config/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
    networks_cli_compatible: yes
    purge_networks: yes
    networks:
      - name: "{{ docker_local_network }}"
    published_ports:
      - 80:80
      - 443:443
      - 8080:8080
  ```

traefik-forward-auth.yml:
```yaml
---
- name: 'Install Traefik Forward Auth'
  docker_container:
    name: traefik-forward-auth
    image: thomseddon/traefik-forward-auth:2
    pull: true
    hostname: traefik-forward-auth-{{ ansible_hostname }}
    domainname: home.insanegenius.net
    restart_policy: unless-stopped
    env:
      DEFAULT_PROVIDER: "google"
      PROVIDERS_GOOGLE_CLIENT_ID: "{{ google_auth_id }}"
      PROVIDERS_GOOGLE_CLIENT_SECRET: "{{ google_auth_secret }}"
      SECRET: "{{ auth_secret }}"
      COOKIE_DOMAIN: "{{ external_domain }}"
      LOG_LEVEL: "debug"
      WHITELIST: "{{ auth_allow }}"
      AUTH_HOST: "auth.{{ external_domain }}"
    networks_cli_compatible: yes
    purge_networks: yes
    networks:
      - name: "{{ docker_local_network }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik-forward-auth.rule: "Host(`auth.{{ external_domain }}`)"
      traefik.http.routers.traefik-forward-auth.entrypoints: "websecure"
      traefik.http.middlewares.traefik-forward-auth.forwardauth.address: "http://traefik-forward-auth:4181"
      traefik.http.middlewares.traefik-forward-auth.forwardauth.authresponseheaders: "X-Forwarded-User"
      traefik.http.services.traefik-forward-auth.loadbalancer.server.port: "4181"
      traefik.http.services.traefik-forward-auth.loadbalancer.server.scheme: "http"
```

whoami.yml:
```yaml
---
- name: 'Install WhoAmI'
  docker_container:
    name: whoami
    image: containous/whoami
    pull: true
    hostname: whoami-{{ ansible_hostname }}
    domainname: home.insanegenius.net
    restart_policy: unless-stopped
    env:
      TZ: "America/Los_Angeles"
    networks_cli_compatible: yes
    purge_networks: yes
    networks:
      - name: "{{ docker_local_network }}"
    published_ports:
      - 2880:80
    labels:
      traefik.enable: "true"
      traefik.http.routers.whoami.rule: "PathPrefix(`/whoami`) || Host(`whoami.{{ external_domain }}`)"
      traefik.http.routers.whoami.entrypoints: "websecure"
      traefik.http.routers.whoami.middlewares: "traefik-forward-auth"
      traefik.http.services.whoami.loadbalancer.server.scheme: "http"
```
