### ISSUE TITLE
Not authorized error when selecting wrong account.

### ISSUE THREAD

**Issue by codestation** [thomseddon/traefik-forward-auth#147]
I am still seeing the #103 problem even after upgrading to 2.2.0 (thomseddon/traefik-forward-auth:v2.2.0). If i choose the email in the whitelist then it works properly and i am redirected to my original page, but if i choose the wrong email by mistake then i end with the "Not authorized" message and no way out until i delete the cookies.

My configuration is the following (using Auth Host Mode and Selective Authentication):

Environment:
```
version: '3.5'
services:
  forward-auth:
    image: thomseddon/traefik-forward-auth:v2.2.0
    environment:
      CONFIG: /run/secrets/credentials
      AUTH_HOST: auth.example.com
      WHITELIST: codestation@example.com
      COOKIE_DOMAIN: example.com
      LOG_LEVEL: debug
    secrets:
      - credentials
    networks:
      - gateway
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.oauth.rule=Host(`auth.example.com`)
        - traefik.http.routers.oauth.entryPoints=https
        - traefik.http.routers.oauth.middlewares=oauth-verify
        - traefik.http.routers.oauth.tls=true
        - traefik.http.routers.oauth.tls.certresolver=dns
        - traefik.http.routers.oauth.tls.domains[0].main=example.com
        - traefik.http.routers.oauth.tls.domains[0].sans=*.example.com
        - traefik.http.services.oauth.loadbalancer.server.port=4181
        - traefik.http.middlewares.oauth-verify.forwardauth.address=http://forward-auth:4181
        - traefik.http.middlewares.oauth-verify.forwardauth.authResponseHeaders=X-Forwarded-User

secrets:
  credentials:
    name: oauth2_credentials
    file: ./credentials.ini

networks:
  gateway:
    external: true
```

Credential file contents
```
client-id = xxxxxxxxxxxx.apps.googleusercontent.com
client-secret = xxxxxxxxxxxxx
secret = xxxxxxxxxxxxxxxxxx
```

The protected service has the following label:

```
traefik.http.routers.myservice.middlewares=oauth-verify
```

I can see the following in the logs:

    level=warning msg="Invalid email" email=wrongaccount@gmail.com handler=Auth host=myservice.example.com method=GET proto=https rule=default source_ip=xxx.xxx.xxx.xxx uri=/

The log is expected since i choose the wrong account, but it shouldn't redirect to the auth page and never show that message?
