### ISSUE TITLE
AUTH_HOST with selective auth ends in auth loop

### ISSUE THREAD

**Issue by vojbarzz** [thomseddon/traefik-forward-auth#149]
Hello,

I took Your example file https://github.com/thomseddon/traefik-forward-auth/blob/master/examples/traefik-v2/swarm/docker-compose-auth-host.yml and tried to use it in selective mode. Unfortunately it ends in auth loop. Could You advise how to make it working? I have commented `--entrypoints.http.http.middlewares=traefik-forward-auth` and added `traefik.http.routers.whoami.middlewares=traefik-forward-auth`. Here is a comple file:

```yaml
version: '3'

services:
  traefik:
    image: traefik:v2.2
    command:
      - --providers.docker
      # This example uses "global authentication"
      - --entryPoints.http.address=:80
#      - --entrypoints.http.http.middlewares=traefik-forward-auth
    ports:
      - "8085:80"
      - "8086:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    image: containous/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost.com`)"
# added
      - "traefik.http.routers.whoami.middlewares=traefik-forward-auth"

  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:2
    environment:
      - PROVIDERS_GOOGLE_CLIENT_ID=xxx
      - PROVIDERS_GOOGLE_CLIENT_SECRET=xxx
      - SECRET=xxx
      # INSECURE_COOKIE is required if not using a https entrypoint
      - INSECURE_COOKIE=true
      - COOKIE_DOMAIN=localhost.com
      - AUTH_HOST=auth.localhost.com:8085
      - LOG_LEVEL=debug
    labels:
      - "traefik.http.routers.traefik-forward-auth.rule=Host(`auth.localhost.com`)"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"
```

**Comment by vojbarzz** [comment]
Hello,

I have found what I have overlooked. It is not obvious, at least it was not for me. The trick it to use forward-auth middleware also for forward-auth container. Here is a complete working example:

```yaml
version: '3'

services:
  traefik:
    image: traefik:v2.2
    command:
      - --providers.docker
      # This example uses "global authentication"
      - --entryPoints.http.address=:80
#      - --entrypoints.http.http.middlewares=traefik-forward-auth
    ports:
      - "8085:80"
      - "8086:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    image: containous/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost.com`)"
      - "traefik.http.routers.whoami.middlewares=traefik-forward-auth"

  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:2
    environment:
      - PROVIDERS_GOOGLE_CLIENT_ID=xxx
      - PROVIDERS_GOOGLE_CLIENT_SECRET=xxx
      - SECRET=xxx
      # INSECURE_COOKIE is required if not using a https entrypoint
      - INSECURE_COOKIE=true
      - COOKIE_DOMAIN=localhost.com
      - AUTH_HOST=auth.localhost.com:8085
      - LOG_LEVEL=debug
    labels:
      - "traefik.http.routers.traefik-forward-auth.rule=Host(`auth.localhost.com`)"
      - "traefik.http.routers.traefik-forward-auth.middlewares=traefik-forward-auth"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"

```
