### ISSUE TITLE
Whitelist multiple hosts using docker-compose

### ISSUE THREAD

**Issue by dantebarba** [thomseddon/traefik-forward-auth#150]
Hi!.

This is mostly a question as I'm getting used to knowing the application. The README specifies that it is possible to add multiple whitelisted users. Unfortunately it doesn't clarify what happens if I want to add a list of whitelists from an env var. Is it allowed?. Should I use comma separated values?

This is my docker-compose:

```  
traefik-forward-auth:
      image: thomseddon/traefik-forward-auth:2.1.0
      container_name: traefik-forward-auth
      networks:
        - main
      environment:
        PROVIDERS_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
        PROVIDERS_GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
        PROVIDERS_OIDC_ISSUER_URL: ${OIDC_ISSUER}
        SECRET: secret_key
        AUTH_HOST: ${AUTH_HOST}
        COOKIE_DOMAIN: ${COOKIE_DOMAINS}
        WHITELIST: ${WHITELIST}
      labels:
        - "traefik.enable=true"
        - "traefik.backend=traefik-forward-auth"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.rule=Host:auth.${DOMAIN_URL}"
        - "traefik.port=4181"
        - "traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181"
        - "traefik.frontend.auth.forward.trustForwardHeader=true"
```

_My whitelist:_

```bash
export WHITELIST=adam@example.com,john@example.com
```
**Expected behaviour:**

Allow adam and john to log in.

**Actual result:**

Not Authorized.
