### ISSUE TITLE
docker secret compatibility

### ISSUE THREAD

**Issue by xNok** [thomseddon/traefik-forward-auth#155]
Hi, I am under the impression that this image is not compatible with docker secret.

If i take the starting example, i would expect to be able to manage sensitive credential as follow

```
services:
  traefik:
    image: traefik:v2.2
    command: --providers.docker
    ports:
      - "8085:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:2
    environment:
      - PROVIDERS_GOOGLE_CLIENT_ID
      - PROVIDERS_GOOGLE_CLIENT_SECRET
      - SECRET
  [...]

secrets:
  PROVIDERS_GOOGLE_CLIENT_ID:
    external: true
  PROVIDERS_GOOGLE_CLIENT_SECRET:
    external: true
  SECRET:
    external: true
```

I would be willing to implement it, but I just can't wrap my head around that to find a generic solution given that you use https://github.com/jessevdk/go-flags to parse the arguments. 

Maybe go-flags should implement a fallback method to be able to work with docker secret.

**Comment by thomseddon** [comment]
Hey,

This project supports configuration via ini file, so the way I've done this when using swarm is:

```
services:
  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:2
    secrets:
      - source: traefik-forward-auth-v8
        target: /config
    environment:
      - CONFIG=/config
      - PROVIDERS_GOOGLE_CLIENT_ID=your-client-id
      - PROVIDERS_GOOGLE_CLIENT_SECRET=your-client-secret
      - SECRET=something-random
      # INSECURE_COOKIE is required if not using a https entrypoint
      - INSECURE_COOKIE=true
      - LOG_LEVEL=debug
    labels:
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"

secrets:

secrets:
  traefik-forward-auth:
    file: secrets/traefik-forward-auth
```

would that work?
