### ISSUE TITLE
Infinite redirect

### ISSUE THREAD

**Issue by maxisme** [thomseddon/traefik-forward-auth#158]
Hey I am getting an infinite loop after authorising when visiting `whoami.$DOMAIN`

this is my swarm stack.yml for `traefik-forward-auth`:
```
  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth
    environment:
      - DEFAULT_PROVIDER=generic-oauth
      - "PROVIDERS_GENERIC_OAUTH_AUTH_URL=${PROVIDERS_GENERIC_OAUTH_AUTH_URL:?err}"
      - "PROVIDERS_GENERIC_OAUTH_TOKEN_URL=${PROVIDERS_GENERIC_OAUTH_TOKEN_URL:?err}"
      - "PROVIDERS_GENERIC_OAUTH_USER_URL=${PROVIDERS_GENERIC_OAUTH_USER_URL:?err}"
      - "PROVIDERS_GENERIC_OAUTH_CLIENT_ID=${PROVIDERS_GENERIC_OAUTH_CLIENT_ID:?err}"
      - "PROVIDERS_GENERIC_OAUTH_CLIENT_SECRET=${PROVIDERS_GENERIC_OAUTH_CLIENT_SECRET:?err}"
      - "SECRET=${OAUTH_SECRET:?err}"
      - "COOKIE_DOMAIN=${DOMAIN}"
      - "AUTH_HOST=auth.${DOMAIN}"
      - "LOG_LEVEL=trace"
    networks:
      - traefik
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik-forward-auth.rule=Host(`auth.${DOMAIN}`)"
        - "traefik.http.routers.traefik-forward-auth.entrypoints=web-secure"
        - "traefik.http.routers.traefik-forward-auth.tls.certresolver=letsencrypt"
        - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"
        - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4181"
        - "traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
      placement:
        constraints: [node.role == manager]
```

And this the whoami service:
```
  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami
    networks:
      - traefik
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN:?err}`)"
        - "traefik.http.routers.whoami.service=whoami"
        - "traefik.http.routers.whoami.entrypoints=web-secure"
        - "traefik.http.routers.whoami.tls.certresolver=letsencrypt"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
        - "traefik.http.routers.whoami.middlewares=traefik-forward-auth"
````

**Comment by maxisme** [comment]
My redirect URL on github is `https://auth.${DOMAIN}`

**Comment by maxisme** [comment]
Solution was to add to the `traefik-forward-auth` labels:
```
- "traefik.http.routers.traefik-forward-auth.middlewares=traefik-forward-auth"
````
Would you be able to put that in the documentation?

**Comment by sodennis** [comment]
```yaml
 - "traefik.http.routers.traefik-forward-auth.middlewares=traefik-forward-auth"
```

For others who are encountering this issue, add the above line to the `traefik-forward-auth` container.

**Comment by Federerer** [comment]
I've wasted an hour on this 🙄

**Comment by Andreychik32** [comment]
@thomseddon, you should add this to docs.

> ```yaml
>  - "traefik.http.routers.traefik-forward-auth.middlewares=traefik-forward-auth"
> ```
> 
> For others who are encountering this issue, add the above line to the `traefik-forward-auth` container.

I've wasted almost 3 hours until I found this.

**Comment by edorgeville** [comment]
I've wasted less than 10 minutes because I went to the issue tracker right away 🤣

**Comment by NishikaDeSilva** [comment]
I'm still getting an infinite loop. I made some changes to middleware as below since `http://traefik-forward-auth:4181` didn't work for me at all.

```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-forward-auth
spec:
  forwardAuth:
    address: https://auth.${DOMAIN}
    authResponseHeaders:
      - X-Forwarded-User
```
Any help is appreciated. 
I also tried added middleware to route, but that didn't even forwarded to google auth.
