### ISSUE TITLE
Incorrect openid logout path

### ISSUE THREAD

**Issue by riplatt** [thomseddon/traefik-forward-auth#163]
when calling the /_oauth/logout endpoint I'm been redirected to ```https://auth.example.net/auth/realms/myrealm/protocol/openid-connect/openid-connect```

Would have expected to redirected to ```https://auth.example.net/auth/realms/myrealm/protocol/openid-connect/logout```

traefik-forward-auth Debug Log:
```text
time="2020-08-11T06:23:52Z" level=debug msg="Allowing valid request" handler=Auth host=grafana.example.net method=GET proto=https rule=default source_ip=10.0.139.56 uri=/logout
time="2020-08-11T06:23:52Z" level=debug msg="Handling logout" cookies="[_forward_auth=EFRHNN4aNW9ehVmHMmfeAxoNK6q80aEty4R5mwB-MaY=|1597120206|me@example.net]" handler=Logout host=grafana.example.net method=GET proto=https rule=default source_ip=10.0.139.56 uri=/_oauth/logout
time="2020-08-11T06:23:52Z" level=info msg="Logged out user" handler=Logout host=grafana.example.net method=GET proto=https rule=default source_ip=10.0.139.56 uri=/_oauth/logout
```

Chrome Network  log:
```text
General
  Request URL: https://grafana.example.net/_oauth/logout
  Request Method: GET
  Status Code: 307 
  Remote Address: 157.230.250.177:443
  Referrer Policy: no-referrer-when-downgrade
Response Header
  content-length: 130
  content-type: text/html; charset=utf-8
  date: Tue, 11 Aug 2020 06:23:52 GMT
  location: https://auth.example.net/auth/realms/myrealm/protocol/openid-connect/openid-connect
  set-cookie: _forward_auth=; Path=/; Domain=grafana.example.net; Expires=Tue, 11 Aug 2020 05:23:52 GMT; HttpOnly; Secure
  status: 307
Request Header
  :authority: grafana.example.net
  :method: GET
  :path: /_oauth/logout
  :scheme: https
  accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
  accept-encoding: gzip, deflate, br
  accept-language: en-AU,en-GB;q=0.9,en-US;q=0.8,en;q=0.7
  cache-control: no-cache
  cookie: _forward_auth=EFRHNN4aNW9ehVmHMmfeAxoNK6q80aEty4R5mwB-MaY=|1597120206|me@example.net
  pragma: no-cache
  referer: https://grafana.example.net/?orgId=5
  sec-fetch-dest: document
  sec-fetch-mode: navigate
  sec-fetch-site: same-origin
  sec-fetch-user: ?1
  upgrade-insecure-requests: 1
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
```

Docker settings:
```yaml
keycloak-auth:
  container_name: keycloak-auth
  image: thomseddon/keycloak-auth:2.2.0
  restart: unless-stopped
  environment:
    - DEFAULT_PROVIDER=generic-oauth
    - PROVIDERS_GENERIC_OAUTH_AUTH_URL=https://auth.example/auth/realms/myrealm/protocol/openid-connect/auth
    - PROVIDERS_GENERIC_OAUTH_TOKEN_URL=https://auth.example/auth/realms/myrealm/protocol/openid-connect/token
    - PROVIDERS_GENERIC_OAUTH_USER_URL=https://auth.example/auth/realms/myrealm/protocol/openid-connect/userinfo
    - LOGOUT_REDIRECT=https://example.net
    - PROVIDERS_GENERIC_OAUTH_CLIENT_ID=<CLIENT_ID>
    - PROVIDERS_GENERIC_OAUTH_CLIENT_SECRET=<CLIENT_SECRET>
    - SECRET=<SECRET>
    - LOG_LEVEL=debug
  networks:
    - internal-network
  labels:
    - "traefik.http.middlewares.keycloak-auth.forwardauth.address=http://keycloak-auth:4181"
    - "traefik.http.middlewares.keycloak-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
    - "traefik.http.services.keycloak-auth.loadbalancer.server.port=4181"
```
