### ISSUE TITLE
Redirect or cookie issue with auth mode

### ISSUE THREAD

**Issue by chriske** [thomseddon/traefik-forward-auth#165]
Hi there!

Not so long ago I've tested your application with Traefik v2 in Kubernetes, and it worked like a charm. For my test scenario I used auth mode, OIDC (dex) and a single subdomain like whoami.example.com and auth.example.com for the callback. As I mentioned, everything went well.

Now I'm trying to make work the same setup in a PoC cluster, but with multiple subdomains. For example whoami.k8spoc.example.com and auth.k8spoc.example.com. Now when I hit the whoami domain in the browser, it redirects me to my OIDC providers page and I'm able to log in. In dex's logs I can see that's ok. But after the login was successful, I'm going to be redirected to the OIDC login site again, and not to the whoami webpage. If I check the logs of traefik or the forward-auth container, there is no relevant information at all moreover the forward-auth container logs are completely empty. I tried to set the log level to trace, but there are no logs at all.

Can you help me please figuring out what is happened?

My relevant configs are:

Forward-auth.env:
```
oidc_issuer_url=https://oidc.k8spoc.example.dev
oidc_client_id=oidc
oidc_client_secret=*****
secret=*****
auth_host_url=auth.k8spoc.example.dev
cookie_domain=example.dev
domain=example.hu
```

Middleware:
```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-forward-auth
  namespace: ingress
spec:
  forwardAuth:
    address: http://traefik-forward-auth:4181
    authResponseHeaders:
      - X-Forwarded-User
```
Ingress (I'm using certmanager, so I can't make an IngressRoute):
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: traefik-forward-auth
  namespace: ingress
  labels:
    app: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:    
  rules:
  - host: auth.k8spoc.example.dev
    http:
      paths:
      - path: /
        backend:
          serviceName: traefik-forward-auth
          servicePort: 4181
  tls:
  - hosts:
    - auth.k8spoc.example.dev
    secretName: auth-https-cert
```
And finally the ingress for whoami app:
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: whoami
  labels:
    app: whoami
  namespace: ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: ingress-traefik-forward-auth@kubernetescrd
spec:
  rules:
  - host: whoami.k8spoc.example.dev
    http:
      paths:
      - path: /
        backend:
          serviceName: whoami
          servicePort: 80
  tls:
  - hosts:
    - whoami.k8spoc.example.dev
    secretName: whoami-https-cert
```

Thanks in advance!
