### ISSUE TITLE
After authentication, redirected to 404

### ISSUE THREAD

**Issue by peavers** [thomseddon/traefik-forward-auth#166]
Hi, I'm trying to get a very basic example working with my domain and applications. 

I get through the Google authentication stage but then end up stuck with the OAuth data in the URL and no redirect happening. 

The URL looks like `https://my-domain.com/_oauth?state=456c10eee[..]`

My simple docker-compose file. All my services run on base paths rather than domains, that shouldn't matter though? 
```yaml
version: '3'
services:

  traefik:
    image: traefik:v2.2
    command: 
      - --api
      - --providers.docker
      - --entrypoints.websecure.address=:443
      - --entrypoints.http.http.middlewares=traefik-forward-auth
      - --certificatesresolvers.leresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.leresolver.acme.storage=/acme.json
      - --certificatesresolvers.leresolver.acme.tlschallenge=true
    ports:
      - "443:443"
      - "8086:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:2
    environment:
      - PROVIDERS_GOOGLE_CLIENT_ID=[..]
      - PROVIDERS_GOOGLE_CLIENT_SECRET=[..]
      - SECRET=[..]
      - LOG_LEVEL=debug
    labels:
      - "traefik.http.routers.traefik-forward-auth.middlewares=traefik-forward-auth"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"

  test-sample:
    container_name: test-sample
    image: test-sample:latest
    labels:
      - "traefik.http.routers.test-sample.middlewares=traefik-forward-auth"
      - "traefik.http.routers.test-sample.rule=Host(`my-domain.com`) && PathPrefix(`/test-sample`)"
      - "traefik.http.routers.test-sample.tls=true"
```

Have I just not configured something correctly?
