### ISSUE TITLE
GitLab OIDC

### ISSUE THREAD

**Issue by aendeavor** [thomseddon/traefik-forward-auth#171]
# Forwarding issue with GitLab's OIDC capabilities?

## Description

I am using GitLab and Traefik, and therefore wanted to have OAuth2 capabilities. After some configuration, I am stuck in the following situation: I am forwarded to the authorization screen in GitLab. But when pressing this button, I am redirected to the same page.

![2020-08-25-181130_1920x1080_scrot](https://user-images.githubusercontent.com/44545919/91201263-86743380-e700-11ea-8cea-4672efd4908b.png)

The picture shows the console log and the dialogue.

## Configuration

This is the configuration. I am (still) running Docker Swarm, though I do not believe this to be the issue in this case.

``` YAML
version: '3.8'

services:

  traefik:
    image: traefik:v2.2.8
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443
      - 10022:10022
      - 10025:10025
    environment:
      - CLOUDFLARE_EMAIL=-------------
      - CLOUDFLARE_DNS_API_TOKEN=-----
      - CLOUDFLARE_ZONE_API_TOKEN=----
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic_conf.yml:/etc/traefik/dynamic_conf.yml:ro
      - ./public.pem:/etc/traefik/public.pem:ro
      - ./private.pem:/etc/traefik/private.pem:ro
      - ./acme.json:/etc/traefik/acme.json:ro
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 15s
      placement:
        constraints:
          - node.role == manager
          - node.platform.os == linux

  oauth:
    image: thomseddon/traefik-forward-auth
    networks:
       - traefik
    environment:
      # Provider Settings
      - DEFAULT_PROVIDER=oidc
      - PROVIDERS_OIDC_ISSUER_URL=https://gitlab.----.com
      - PROVIDERS_OIDC_CLIENT_ID=----
      - PROVIDERS_OIDC_CLIENT_SECRET=----
      - SECRET=----
      # Authentication Rules
      - AUTH_HOST=oauth.----.com
      - COOKIE_DOMAIN=----.com
      - URL_PATH=/_oauth
      - INSECURE_COOKIE=false
      - LIFETIME=21600 # 6 Hours
      # Log
      - LOG_LEVEL=debug
      - LOG_FORMAT=json
    deploy:
      mode: global
      labels:
        - traefik.enable=true
        # ? Router
        - traefik.http.routers.oauth.rule=Host(`oauth.----.com`)
        - traefik.http.routers.oauth.entrypoints=https
        # ? Middleware
        - traefik.http.middlewares.oauth.forwardauth.address=http://oauth:4181
        - traefik.http.middlewares.oauth.forwardauth.authresponseheaders=X-Forwarded-User
        # ? Service
        - traefik.http.services.oauth.loadbalancer.server.port=4181

networks:
  traefik:
    external: true
```

Can anyone help me?
