### ISSUE TITLE
Not Authorized (3 Hosts setup with keycloak)

### ISSUE THREAD

**Issue by TobenderZephyr** [thomseddon/traefik-forward-auth#172]
My setup currently are three different Docker Hosts (no swarm), each running one of: `keycloak + traefik`, `traefik-forward-auth+  traefik`, `application + traefik`. The plan was to have the application run somewhere (LAN/DMZ or even cloud), while the forward-auth-host is inside a DMZ allowing only HTTP/HTTPS+outgoing LDAP for Authentication against Active Directory.
The KeyCloak Server could either be inside the same DMZ or internal - yet to decide where it makes most sense.

When I hit the `whoami` page, I will get redirected to the KeyCloak login page by `traefik-forward-auth`. After entering username+password, I get redirected again to `traefik-forward-auth` with /_oauth?<string>.

Yet I receive `401 Not Authenticated`. Depending on the Environment Variables I chose beforehand (OIDC vs generic oauth) I see either all Keycloak cookies, or nothing at all (with generic-oauth)

```time="2020-08-27T20:06:09Z" level=debug msg="Authenticating request" cookies="[]" handler=Auth host=auth.<example.com> method=GET proto=https rule=default source_ip=172.25.200.15 uri=/
time="2020-08-27T20:06:09Z" level=debug msg="Set CSRF cookie and redirected to provider login url" csrf_cookie="_forward_auth_csrf=ec2ae9f7367f1b3d77f66f5104f08f6c; Path=/; Domain=<example.com>; Expires=Fri, 28 Aug 2020 08:06:09 GMT; HttpOnly" handler=Auth host=auth.<example.com> login_url="https://auth.<example.local>/auth/realms/Internal/protocol/openid-connect/auth?client_id=auth-proxy-internal&redirect_uri=https%3A%2F%2Fauth.<example.com>%2F_oauth&response_type=code&scope=openid+profile+email&state=ec2ae9f7367f1b3d77f66f5104f08f6c%3Aoidc%3Ahttps%3A%2F%2Fauth.<example.com>%2F" method=GET proto=https rule=default source_ip=172.25.200.15 uri=/
time="2020-08-27T20:06:09Z" level=debug msg="Handling callback" cookies="[]" handler=AuthCallback host=auth.<example.com> method=GET proto=https rule=default source_ip=172.25.217.7 uri="/_oauth?state=ec2ae9f7367f1b3d77f66f5104f08f6c%3Aoidc%3Ahttps%3A%2F%2Fauth.<example.com>%2F&session_state=3521a5f0-279d-46c4-9699-b78ce783e6a5&code=35af93f0-9ae3-4d28-80db-e1a9855ead63.3521a5f0-279d-46c4-9699-b78ce783e6a5.dd176887-3e47-4319-8337-44b68b520582"
time="2020-08-27T20:06:09Z" level=info msg="Missing csrf cookie" handler=AuthCallback host=auth.<example.com> method=GET proto=https rule=default source_ip=172.25.217.7 uri="/_oauth?state=ec2ae9f7367f1b3d77f66f5104f08f6c%3Aoidc%3Ahttps%3A%2F%2Fauth.<example.com>%2F&session_state=3521a5f0-279d-46c4-9699-b78ce783e6a5&code=35af93f0-9ae3-4d28-80db-e1a9855ead63.3521a5f0-279d-46c4-9699-b78ce783e6a5.dd176887-3e47-4319-8337-44b68b520582"
```

This is my setup:

`traefik-forward-auth`:

```
version: '3'
services:
  auth-proxy:
    container_name: auth-proxy
    image: thomseddon/traefik-forward-auth:2
    environment:
      DEFAULT_PROVIDER: oidc #generic-oauth
      PROVIDERS_OIDC_CLIENT_ID: auth-proxy-internal
      PROVIDERS_OIDC_CLIENT_SECRET: 51cfe608-6b1a-4698-9d15-02cbca2811ff
      PROVIDERS_OIDC_ISSUER_URL: https://<keycloak>/auth/realms/Internal

      PROVIDERS_GENERIC_OAUTH_AUTH_URL: https://<keycloak>/auth/realms/Internal/protocol/openid-connect/auth
      PROVIDERS_GENERIC_OAUTH_TOKEN_URL: https://<keycloak>/auth/realms/Internal/protocol/openid-connect/token
      PROVIDERS_GENERIC_OAUTH_USER_URL: https://<keycloak>/auth/realms/Internal/protocol/openid-connect/userinfo
      PROVIDERS_GENERIC_OAUTH_CLIENT_ID: auth-proxy-internal
      PROVIDERS_GENERIC_OAUTH_CLIENT_SECRET: 51cfe608-6b1a-4698-9d15-02cbca2811ff

      SECRET: 554034e6a2da367916f11b73d385ac99
      AUTH_HOST: auth.<example.com>
      INSECURE_COOKIE: 'true'
      CSRF_COOKIE_NAME: '_forward_auth_csrf'
      LOG_LEVEL: debug
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /etc/ssl/certs/ca-bundle.crt:/etc/ssl/certs/ca-certificates.crt:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.forward-auth.forwardauth.address=http://auth-proxy:4181/"
      - "traefik.http.middlewares.forward-auth.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
      - "traefik.http.routers.auth-proxy.rule=Host(`auth.<example.com>`)"
      - "traefik.http.routers.auth-proxy.entrypoints=http"
      - "traefik.http.routers.auth-proxy.middlewares=forward-auth"
      - "traefik.http.services.auth-proxy.loadbalancer.server.port=4181"
      - "traefik.http.routers.auth-proxy-secure.entrypoints=https"
      - "traefik.http.routers.auth-proxy-secure.rule=Host(`auth.<example.com>`)"
      - "traefik.http.routers.auth-proxy-secure.middlewares=forward-auth"
      - "traefik.http.routers.auth-proxy-secure.tls=true"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
```

`whoami`:
```
version: '3'
services:
  test:
    image: mendhak/http-https-echo
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.forward-auth.forwardauth.address=https://auth.<example.com>/"
      - "traefik.http.middlewares.forward-auth.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
      - "traefik.http.services.test.loadbalancer.server.port=80"
      - "traefik.http.routers.test.entrypoints=http"
      - "traefik.http.routers.test.rule=Host(`whoami.<example.local>`)"
      - "traefik.http.routers.test.middlewares=forward-auth"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
```

I guess it comes down to normal Docker Networking now and avoiding traefik at a certain point, so proxy headers won't get mixed up. Key is replacing most VM-webservices into containers, having the opportunity of varying hosts not in the same network.

Any help on this is appreciated,

Thanks
Marcus

EDIT: changed logs
