### ISSUE TITLE
Oauth2 Provider does not work

### ISSUE THREAD

**Issue by v7lin** [thomseddon/traefik-forward-auth#173]
traefik logs
```shell
middleware "traefik-forward-auth@docker" does not exist
```

traefik.yaml
```yaml
# 版本
version: "3.7"

# 服务
services:

  # 暂不支持设置时区
  traefik:
    image: traefik:v2.2.1
    ports:
      - 22:22
      - 80:80
      - 443:443
#      - 8080
    networks:
      - net # traefik_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../../dev-ops-repo/traefik/acme:/etc/traefik/acme
      - ./certs:/certs
      - ./certs.yml:/etc/traefik/dynamic_conf/conf.yml
#    environment:
#      - TZ=${TIME_ZONE:-Asia/Shanghai}
#      - ALICLOUD_ACCESS_KEY=
#      - ALICLOUD_SECRET_KEY=
    command:
#      - "--log.level=DEBUG"
      - "--api=true"
      - "--providers.docker=true"
      - "--providers.docker.swarmmode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file=true"
      - "--providers.file.directory=/etc/traefik/dynamic_conf"
      - "--providers.file.watch=true"
      - "--entrypoints.ssh.address=:22"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
#      - "--certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL:-traefik@traefik.com}" # ocsp(在线证书状态协议, http://ocsp.int-x3.letsencrypt.org/)无法正常访问
##      - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory" # 默认
##      - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory" # staging
#      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme-v2.json" # 默认
##      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme-staging-v2.json" # staging
#      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
#      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http"
##      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
##      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53"
##      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=alidns" # https://docs.traefik.io/https/acme/#providers
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager # 部署位置，只在管理节点部署
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_net"
        - "traefik.docker.lbswarm=true"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
        - "traefik.http.routers.traefik.service=api@internal" # 不能用 traefik，除非开启 --api.insecure=true
        - "traefik.http.routers.traefik.rule=Host(`traefik.${SERVER_DOMAIN:-localhost}`)"
        - "traefik.http.routers.traefik.entrypoints=http"
        - "traefik.http.routers.traefik.middlewares=redirecttls"
        - "traefik.http.middlewares.redirecttls.redirectscheme.scheme=https"
        - "traefik.http.routers.traefiktls.service=api@internal" # 不能用 traefik，除非开启 --api.insecure=true
        - "traefik.http.routers.traefiktls.rule=Host(`traefik.${SERVER_DOMAIN:-localhost}`)"
        - "traefik.http.routers.traefiktls.entrypoints=https"
        - "traefik.http.routers.traefiktls.tls=true"
#        - "traefik.http.routers.traefiktls.tls.certresolver=letsencrypt"
#        - "traefik.http.routers.traefiktls.middlewares=traefik-forward-auth"

networks:
  # docker stack deploy -c <(docker-compose -f docker-swarm.yml config) traefik
  # Creating network traefik_net
  # 外部引用 "traefik_net"
  net:
    driver: overlay
    attachable: true
```

traefik-forward-auth.yaml
```yaml
# 版本
version: "3.7"

# 服务
services:

  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:2.2
#    ports:
#      - 4181
    networks:
      - traefik_net
    environment:
#      - TZ=${TIME_ZONE:-Asia/Shanghai}
      - DEFAULT_PROVIDER=generic-oauth
      - PROVIDERS_GENERIC_OAUTH_AUTH_URL=https://gitea.${SERVER_DOMAIN:-localhost}/login/oauth/authorize
      - PROVIDERS_GENERIC_OAUTH_TOKEN_URL=https://gitea.${SERVER_DOMAIN:-localhost}/login/oauth/access_token
      - PROVIDERS_GENERIC_OAUTH_USER_URL=https://gitea.${SERVER_DOMAIN:-localhost}/api/v1/user
      - PROVIDERS_GENERIC_OAUTH_CLIENT_ID=${GITEA_CLIENT_ID?err}
      - PROVIDERS_GENERIC_OAUTH_CLIENT_SECRET=${GITEA_CLIENT_SECRET?err}
      - PROVIDERS_GENERIC_OAUTH_TOKEN_STYLE=query
      - SECRET=${SECRET?err}
#      # INSECURE_COOKIE is required if not using a https entrypoint
#      - INSECURE_COOKIE=true
#      - LOG_LEVEL=debug
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=false"
        - "traefik.docker.network=traefik_net"
        - "traefik.docker.lbswarm=true"
        - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"
        - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4181"
        - "traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"

networks:
  traefik_net:
    external: true
```

files.yaml
```yaml
# 版本
version: "3.7"

# 服务
services:

  files:
    image: nginx:1.17.9-alpine
#    ports:
#      - 80
    networks:
      - traefik_net
    volumes:
      - ../../dev-ops-repo/files:/usr/share/nginx/html/files
    environment:
      - TZ=${TIME_ZONE:-Asia/Shanghai}
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_net"
        - "traefik.docker.lbswarm=true"
        - "traefik.http.services.files.loadbalancer.server.port=80"
        - "traefik.http.routers.files.service=files"
        - "traefik.http.routers.files.rule=Host(`files.${SERVER_DOMAIN:-localhost}`)"
        - "traefik.http.routers.files.entrypoints=http"
        - "traefik.http.routers.files.middlewares=redirecttls"
        - "traefik.http.routers.filestls.service=files"
        - "traefik.http.routers.filestls.rule=Host(`files.${SERVER_DOMAIN:-localhost}`)"
        - "traefik.http.routers.filestls.entrypoints=https"
        - "traefik.http.routers.filestls.tls=true"
#        - "traefik.http.routers.filestls.tls.certresolver=letsencrypt"
        - "traefik.http.routers.filestls.middlewares=traefik-forward-auth"

networks:
  traefik_net:
    external: true
```
