### ISSUE TITLE
X-Forwarded-User is blank after logging in via Keycloak

### ISSUE THREAD

**Issue by ChristianKlass** [thomseddon/traefik-forward-auth#174]
I have been trying to use the traefik-forward-auth to do authentication with Keycloak. So far, I've managed to get it to log users in. However, I want to be able to get the username/identity of the users who are logging in as well.

To this end, I've tested with the whoami container and the X-Forwarded-User field is blank:

```
Hostname: <redacted>
IP: <redacted>
IP: <redacted>
IP: <redacted>
RemoteAddr: <redacted>
GET /whoami HTTP/1.1
Host: test.server
User-Agent: <redacted>
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Cache-Control: max-age=0
Cookie: _forward_auth=iQ99fj0lGbzUZtPsdBUsJJde9Aanz339h-OBobY6THg=|1598640347|
Referer: http://keycloak.test.server
Upgrade-Insecure-Requests: 1
X-Forwarded-For: 192.168.1.43
X-Forwarded-Host: test.server
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: 0f7195833sa78
X-Forwarded-User: 
X-Real-Ip: 192.168.1.43
```
The x-forwarded-user is blank, and I'm not sure why. As I understand it, the username of the user should be in this field? If I'm understanding it wrongly, please let me know. Basically, I'd like to be able to use this username to log in via oauth to [Grafana](https://grafana.com/docs/grafana/latest/auth/auth-proxy/).

How can I do this? I've attached the relevant configuration, and would appreciate any help and pointers. Please let me know if you need any more information.

Basically, I would like to get X-Forwarded-User to contain the information required the Grafana's Auth Proxy to work. 

```
--- traefik.toml ---
[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false

[api]
  insecure = true
  dashboard = true
  debug = true

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"

[accessLog]
  # filePath = "/var/log/traefik/access.log"
  format = "json"
  [accessLog.fields.names]
    "StartUTC" = "drop"

[metrics]
  [metrics.prometheus]
    entryPoint = "traefik"
    buckets = [0.1,0.3,1.2,5.0]
```
```
--- docker-compose.yml ---
  traefik:
    image: 'traefik:latest'
    container_name: traefik
    command:
      - '--entryPoints.http.address=:80'
      - '--entryPoints.https.address=:443'
      - '--entryPoints.http.http.middlewares=traefik-forward-auth'
    ports:
      - '80:80'
      - '443:443'
      - '8081:8080'
    labels:
      - 'traefik.http.routers.traefik.rule=Host(`test.server`)'
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User, X-Auth-User, X-WebAuth-User"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './traefik/traefik.toml:/etc/traefik/traefik.toml'
      - './traefik/log:/var/log'
    extra_hosts:
    # needed because for some reason it needs to be able to acces keycloak and the forward auth from outside.
    # I tried using the internal docker network, but it results in "host not found", 
    # or will present errors when trying to access.
      - "keycloak.st.ims:192.168.1.43"
      - "auth.st.ims:192.168.1.43"
    networks:
      - external-proxy
      - internal-proxy

  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:2
    container_name: traefik-forward-auth
    env_file: ./env/forward-auth.env
    restart: unless-stopped
    expose: 
      - '4181'
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.traefik-forward-auth.rule=Host(`auth.test.server`)"
      - "traefik.http.routers.traefik-forward-auth.middlewares=traefik-forward-auth"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User, X-Auth-User, X-WebAuth-User"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"
    extra_hosts:
      - "keycloak.st.ims:192.168.1.43"
      - "st.ims:192.168.1.43"
    networks:
      - external-proxy
      - internal-proxy

  whoami:
    image: containous/whoami
    container_name: whoami
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.whoami.rule=Host(`test.server`) && PathPrefix(`/whoami`)'
      - "traefik.http.routers.whoami.middlewares=traefik-forward-auth"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
    extra_hosts:
      - "keycloak.st.ims:192.168.1.43"
      - "auth.st.ims:192.168.1.43"
    networks:
      - external-proxy
      - internal-proxy
```
```
--- forward-auth.env ---
LOG_LEVEL=debug
DEFAULT_PROVIDER=generic-oauth
SECRET=supersecretpassword

PROVIDERS_GENERIC_OAUTH_AUTH_URL=http://keycloak.test.server/auth/realms/IMS/protocol/openid-connect/auth
PROVIDERS_GENERIC_OAUTH_TOKEN_URL=http://keycloak.test.server/auth/realms/IMS/protocol/openid-connect/token
PROVIDERS_GENERIC_OAUTH_USER_URL=http://keycloak.test.server/auth/realms/IMS/protocol/openid-connect/userinfo
PROVIDERS_GENERIC_OAUTH_CLIENT_ID=traefik
PROVIDERS_GENERIC_OAUTH_CLIENT_SECRET=7cff64bf-2cca-46c2-7723-a8b6e2331de7

INSECURE_COOKIE=true
AUTH_HOST=auth.test.server
COOKIE_DOMAIN=test.server
```

Thank you!
