### ISSUE TITLE
After authentication, redirected to "Service Unavailable"

### ISSUE THREAD

**Issue by amino-8** [thomseddon/traefik-forward-auth#190]
I've had a working set-up with Traefik 2 for about a year but in the last 2 days, I'm seeing an issue where whenever I authenticate, I get redirected to a "Service Unavailable" message instead of my site.
The docker services behind traefik are working fine and I can access them on other machines (where I I don't need to authenticate with oauth).
Has something changed with the google api that's impacting me?
Here's the relevant section from my compose file:
````
  oauth:
    container_name: oauth
    image: thomseddon/traefik-forward-auth:latest
    restart: unless-stopped
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    environment:
      - CLIENT_ID=$GOOGLE_CLIENT_ID
      - CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
      - SECRET=$OAUTH_SECRET
      - COOKIE_DOMAIN=$DOMAINNAME
      - INSECURE_COOKIE=false
      - AUTH_HOST=oauth.$DOMAINNAME
      - URL_PATH=/_oauth
      - WHITELIST=$MY_EMAIL
      - LOG_LEVEL=info
      - LOG_FORMAT=text
      - LIFETIME=2592000 # 30 days
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.oauth-rtr.entrypoints=https"
      - "traefik.http.routers.oauth-rtr.rule=HostHeader(`oauth.$DOMAINNAME`)"
      - "traefik.http.routers.oauth-rtr.tls=true"
      ## HTTP Services
      - "traefik.http.routers.oauth-rtr.service=oauth-svc"
      - "traefik.http.services.oauth-svc.loadbalancer.server.port=4181"
      ## Middlewares
      - "traefik.http.routers.oauth-rtr.middlewares=chain-oauth@file"
````

The error I'm getting in the log is:
````
time="2020-09-30T07:42:48Z" level=error msg="Code exchange failed with provider" error="Post https://www.googleapis.com/oauth2/v3/token: net/http: TLS handshake timeout" handler=AuthCallback
````
