### ISSUE TITLE
Always try to clear CSRF cookie

### ISSUE THREAD

**Issue by thomseddon** [thomseddon/traefik-forward-auth#198]
This should be done immediately after extracting the cookie

**Comment by colearendt** [comment]
Just experienced a mystifying issue with the CSRF cookie complaining. Incognito window worked fine, but I couldn't get my browser state to login for ~ 10 minutes. I tried clearing cookies on the only domain I could get to (sso.mydomian.com - points at the forwardauth container), but it seemed like the cookie was cached at (myapp.mydomain.com), since each new request there 
had a csrf cookie attached.

- Navigate to `myapp.mydomain.com`, in network devtools, this request had: `Cookie: _forward_auth_csrf=xxxx`
- Redirect to IDP and login
- Redirect back to `sso.mydomain.com`, get `Not Authorized` in the browser
- Error message in forward auth container:
```
time="2020-12-30T07:18:32Z" level=warning msg="Error validating csrf cookie" csrf_cookie="_forward_auth_csrf=xxx" error="CSRF cookie does not match state" handler=AuthCallback host=sso.mydomain.com method=GET proto=https rule=default source_ip=1.2.3.4 uri="/__oauth__?code=xxx&state=yyy%3Aoidc%3Ahttps%3A%2F%2Fmyapp.mydomain.com%2F"
```

Then suddenly it started working again. Not sure what triggered the change 🤷‍♂️ But wanted to report since it seemed somewhat related to a "bad" CSRF cookie

**Comment by whizzzkid** [comment]
I am getting a similar error, works in a new session but fails when already logged in:

```
time="2020-12-30T21:13:47Z" level=warning msg="Error validating csrf cookie" csrf_cookie="_forward_auth_csrf=<redacted>" error="CSRF cookie does not match state" handler=AuthCallback host=auth.sub.domain.com method=GET proto=https rule=default source_ip=<my public ip> uri="/_oauth?state=<redacted>%2F&code=<redacted>&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+openid&authuser=0&prompt=none"
```

```
tfa:
    image: thomseddon/traefik-forward-auth:2-arm
    environment:
      - PROVIDERS_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - PROVIDERS_GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SECRET=${AUTH_JWT_SECRET}
      - COOKIE_DOMAIN=${BS_URL} #sub domain
      - AUTH_HOST=auth.${BS_URL}
      - LOG_LEVEL=${LOG_LEVEL}
      - WHITELIST=${WHITELIST}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tfa.rule=Host(`auth.${BS_URL}`)"
      - "traefik.http.routers.tfa.entrypoints=websecure"
      - "traefik.http.routers.tfa.service=tfa"
      - "traefik.http.routers.tfa.tls.certresolver=bs"
      - "traefik.http.middlewares.tfa.forwardauth.address=http://tfa:4181"
      - "traefik.http.middlewares.tfa.forwardauth.authResponseHeaders=X-Forwarded-User"
      - "traefik.http.services.tfa.loadbalancer.server.port=4181"
      - "traefik.http.routers.tfa.middlewares=tfa"
```

This works great in icognito, fails in already logged in session.
