### ISSUE TITLE
Receive "not authorized" after Google Oauth rule

### ISSUE THREAD

**Issue by Svarto** [thomseddon/traefik-forward-auth#20]
Hi,

I really like the idea of having a centralized authentication for my self-hosted applications. I struggle to set it up though, I use the "overlay" mode and when going to my domain I did get redirected to the google login page. However, after logging in I just get a white page with "Not Authorized" written on top. 

What can I do to correct this? Do I need to do any setup to make sure the https://home-service-domain.com/_oauth gets correctly redirected to the traefik-forward-auth container or?

Would really appreciate your help in this, thanks alot!

**Comment by thomseddon** [comment]
No problem, it should mostly be "automatic" but if something has gone wrong it could be an opportunity to improve documentation, could you post your config?

**Comment by Svarto** [comment]
certainly!

traefik.toml
```
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.auth.forward]
      address = "http://172.19.0.7:4181" #ip to traefik-forward-auth docker
      authResponseHeaders = ["X-Forwarded-User"]
```

traefik-forward-auth docker:
```
version: '3'

services:
traefik-forward-auth:
    image: thomseddon/traefik-forward-auth
    environment:
      - CLIENT_ID="my client id from Google Oauth2"
      - CLIENT_SECRET="my client secret from Google Oauth2"
      - SECRET="I entered a password here, just letters and numbers"
      - COOKIE_SECURE=false
      - DOMAIN=my-top-domain.com
    networks:
- ovpn_network

```

Google Oauth consent screen:
Entered application name and also Authorized domains ("my-top-domain.com"). Left everything else blank or by defaults.

Google Credentials:
Create an Oauth2 credentials, entering a name for the application and then added the following authorized redirects URIs:

https://app1.svarto-server.com/_oauth
https://app1.svarto-server.com

I tried first time only adding the https://app1.svarto-server.com/_oauth, but that didnt work so added the second one just in case - still get not authorized though...
