### ISSUE TITLE
how redirect set to https instead http

### ISSUE THREAD

**Issue by obeyler** [thomseddon/traefik-forward-auth#205]
Hy, 
I've got a proxy who takes all https request and send it to traefik on http
![image](https://user-images.githubusercontent.com/23224162/98101585-b7a47900-1e92-11eb-8f1a-b0e076f1b567.png)

when I use traeffik middleware I see that on the browser debug :

```
          "method": "GET",
          "url": "https://longhorn.k8s-micro.xxx/",
        "response": {
          "status": 307,
          "statusText": "Temporary Redirect",
          "httpVersion": "HTTP/1.1",
             "value": "https://uaa.nd-int-ops-paas.xxxxxxx/oauth/authorize?client_id=k8s-micro&redirect_uri=http%3A%2F%2Flonghorn.k8s-micro.xxx%2F_oauth&response_type=code&scope=openid+profile+email&state=ccecde48d60db262e453bc773627307c%3Aoidc%3Ahttp%3A%2F%2Flonghorn.k8s-micro.xxx%2F"

          "redirectURL": "https://uaa.xxx/oauth/authorize?client_id=k8s-micro&redirect_uri=http%3A%2F%2Flonghorn.k8s-micro.xxx%2F_oauth&response_type=code&scope=openid+profile+email&state=ccecde48d60db262e453bc773627307c%3Aoidc%3Ahttp%3A%2F%2Flonghorn.k8s-micro.xxxx%2F",
```
As you can see the https request for https://longhorn.k8s-micro.xxx is redirected to UAA but redirect_uri is set to 'http' and not 'https'
Is there an option to force the https usage for the redirect_uri ?

**Comment by colearendt** [comment]
Same problem here. I worked around this (or used the intended solution) by having another middleware set the `X-Forwarded-Proto: https` header first, and that seems to resolve the issue! Hope it helps!

**Comment by thomseddon** [comment]
👍 @colearendt that's a good workaround, thanks for posting!

**Comment by colearendt** [comment]
Yeah, I use this behavior regularly 😄  I haven't upgraded / changed versions lately though - still using the `thomseddon/traefik-forward-auth:2` docker image. 

You have to make sure the `X-Forwarded-Proto: https` header is being sent to `traefik-forward-auth`, though. I normally make sure it is being sent by running a tcpdump and looking at the traffic in Wireshark 🤷‍♂️  I run something like `sudo tcpdump -i any -w output.pcap` on a traefik host so that I can see the plaintext traffic and then move that pcap file to my desktop so that I can open in wireshark and have a look at the appropriate requests.

**Comment by colearendt** [comment]
Interesting! I would dive into the traefik routes more deeply - either looking at the actual middleware definitions inside of docker / kubernetes / wherever traefik is running. Or loading up the traefik dashboard to look at things explicitly - I have been befuddled more than once by middlewares not picking up properly, not applied properly (i.e. traefik was stuck fighting with some other random area and not picking up my changes), etc. Seeing what traefik understands as its middleware definition is important - what version of traefik are you using?

**Comment by octopop** [comment]
I ended up here with the exact same issue of forward-auth requesting a `http` redirect URI instead of `https` as intended. We deployed Traefik on GCP GKE and terminated SSL at the load balancer. This meant that from the LB ingress to Traefik:web entrypoint it was all HTTP. 

Unfortunately @colearendt 's solution of adding a http->https headers middleware did not work for me. TBH, I have no idea why Traefik ignores this explicit overriding just like @kman1999 experienced although its an elegant solution.

After few hours of tinkering, I finally figured out a Traefik native way; which is to explicitly have `trustForwardHeader: true` set when defining the auth middleware.

```
# Auth Middleware
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-forward-auth
  namespace: default
spec:
  forwardAuth:
    address: http://traefik-forward-auth
    # Cloudwerx: trustForwardHeaders set to true explicitly
    # important otherwise redirect URI is http since we terminate SSL on GCP LB.
    trustForwardHeader: true  
    authResponseHeaders:
      - X-Forwarded-User
 ```

Additionally, you would want to ensure that you have enabled `proxyProtocol insecure:true` and `forwardedHeaders insecure:true` in your static config or helm values.yaml. Specifically, I enabled it for the `web` entrypoint as all trafic for us enters `web` after secure termination at GCP Global load balancer.

**Comment by ab77** [comment]
For anyone deploying to balenaCloud and accessing the app(s) via pbalena public device URLs](https://docs.balena.io/learn/develop/runtime/#public-device-urls), this is the only config I've been able to get working (i.e. by chaining middlewares):

```
version: "2.4"

x-common: &common
  tty: true
  restart: unless-stopped

services:
  # https://hub.docker.com/_/traefik
  traefik:
    image: traefik:v2.10.1
    <<: *common
    command:
      - --accesslog=true
      - --entryPoints.web.address=:80
      - --entrypoints.web.forwardedHeaders.insecure=true
      - --log.level=DEBUG
      - --ping=true
      - --providers.docker.endpoint=unix:///var/run/balena.sock
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: wget -qO /dev/null localhost:8080/ping
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 30s
    labels:
      io.balena.features.balena-socket: 1

  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:v2.2.0
    <<: *common
    environment:
      LOG_LEVEL: debug
    labels:
      traefik.enable: true
      traefik.http.middlewares.traefik-forward-auth.forwardauth.address: http://traefik-forward-auth:4181
      traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders: X-Forwarded-User
      traefik.http.middlewares.traefik-forward-auth.forwardauth.trustForwardHeader: true
      traefik.http.routers.traefik-forward-auth.entrypoints: web
      traefik.http.services.traefik-forward-auth.loadbalancer.server.port: 4181

  whoami:
    image: traefik/whoami
    <<: *common
    labels:
      traefik.enable: true
      traefik.http.middlewares.whoami.chain.middlewares: x-forwarded-port,x-forwarded-proto,traefik-forward-auth
      traefik.http.middlewares.x-forwarded-port.headers.customRequestHeaders.X-Forwarded-Port: 443
      traefik.http.middlewares.x-forwarded-proto.headers.customRequestHeaders.X-Forwarded-Proto: https
      traefik.http.routers.whoami.entrypoints: web
      traefik.http.routers.whoami.middlewares: whoami
      traefik.http.routers.whoami.rule: HostRegexp(`{subdomain:..*\.balena-(?:staging-)?devices}.com`)
      traefik.http.services.whoami.loadbalancer.server.port: 80
```

Note: balena public device URLs work by terminating HTTPS traffic on the cloud proxy and then forwarding HTTP traffic to the device(s) over the VPN (CloudLink) tunnel(s), **without** adding appropriate `X-Forwarded-Proto|Port` headers. So without injecting these headers, any proxy will treat the request as insecure and either get into redirect loops, or OAuth redirect url mismatches.
