### ISSUE TITLE
Advanced separate pod example results in 500s

### ISSUE THREAD

**Issue by duffn** [thomseddon/traefik-forward-auth#215]
I'm certain I'm doing something incorrectly here, but I'm not sure what it is. I'm trying to simply run the advanced separate pod example. What I would ideally like to do is run `traefik-forward-auth` in `kube-system` where `traefik` is running and then run applications in different namespaces and reference the middleware from there.

- However, I can't get the example running at all, regardless of where the forward auth and application are located. I always receive 500 with this message in `traefik` and no logs in `traefik-forward-auth`.

```
traefik-5d486b44f5-xhrvz traefik 97.118.227.64 - - [09/Dec/2020:15:41:36 +0000] "GET / HTTP/1.1" 500 0 "-" "-" 343318 "debug2-whoami-f553dd37034467403d31@kubernetescrd" - 3ms
```

- The `whoami` app works when I remove the middleware.

Here's what I'm doing, with secrets redacted. Thanks for any assistance.

```
kubectl -n kube-system create secret generic traefik-forward-auth-secrets \
  --from-literal=traefik-forward-auth-google-client-id='1234.apps.googleusercontent.com' \
  --from-literal=traefik-forward-auth-google-client-secret='1234' \
  --from-literal=traefik-forward-auth-secret='1234'

```

```
#
# Traefik Forward Auth Deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-system
  name: traefik-forward-auth
  labels:
    app: traefik-forward-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-forward-auth
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: traefik-forward-auth
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - image: thomseddon/traefik-forward-auth:2
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          name: traefik-forward-auth
          ports:
            - containerPort: 4181
              protocol: TCP
          env:
            - name: LOG_LEVEL
              value: "debug"
            - name: DOMAIN
              value: "mydomain.com"
            # INSECURE_COOKIE is required if not using a https entrypoint
            # - name: INSECURE_COOKIE
            #   value: "true"
            # Remove COOKIE_DOMAIN if not using auth host mode
            - name: COOKIE_DOMAIN
              value: "myotherdomain.tools"
            - name: AUTH_HOST
              value: "auth.myotherdomain.tools"
            - name: PROVIDERS_GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: traefik-forward-auth-secrets
                  key: traefik-forward-auth-google-client-id
            - name: PROVIDERS_GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: traefik-forward-auth-secrets
                  key: traefik-forward-auth-google-client-secret
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: traefik-forward-auth-secrets
                  key: traefik-forward-auth-secret
      volumes:
        - name: traefik-forward-auth-secrets
          secret:
            secretName: traefik-forward-auth-secrets
---
#
# Auth Service
#
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: traefik-forward-auth
  labels:
    app: traefik
spec:
  type: ClusterIP
  selector:
    app: traefik
  ports:
    - name: auth-http
      port: 4181
      targetPort: 4181
---
#
# Auth Ingress
#
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: kube-system
  name: traefik-forward-auth
  labels:
    app: traefik
spec:
  entryPoints:
    - https
  routes:
    - match: Host(`auth.mydomiain.tools`)
      kind: Rule
      services:
        - name: traefik-forward-auth
          port: 4181
      middlewares:
        - name: traefik-forward-auth
---
#
# Auth Middleware
#
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  namespace: kube-system
  name: traefik-forward-auth
spec:
  forwardAuth:
    address: http://traefik-forward-auth:4181
    authResponseHeaders:
      - X-Forwarded-User
---
#
# Example Application Deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: debug2
  name: whoami
  labels:
    app: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - image: containous/whoami
          name: whoami
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
#
# Service
#
apiVersion: v1
kind: Service
metadata:
  namespace: debug2
  name: whoami
  labels:
    app: whoami
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
  selector:
    app: whoami

---
#
# IngressRoute
#
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: debug2
  name: whoami
  labels:
    app: whoami
spec:
  entryPoints:
    - https
  routes:
    - match: Host(`whoami.mydomiain.tools`)
      kind: Rule
      services:
        - name: whoami
          port: 80
      middlewares:
        - name: kube-system-traefik-forward-auth

```

**Comment by kitos9112** [comment]
Hi @duffn - I'm literally facing the same situation here. My suspicion is that we're not hitting the `traefik-forward-auth` pod at all.
I replicated the exact same scenario as yours and same result.

**Comment by kitos9112** [comment]
Hello again,

So after an hour of debilitating troubleshooting within my arm64 K3S cluster I found the root cause, however don't know what's wrong with my traefik config. It seems that Traefik couldn't resolve the DNS name that points to `traeifk-forward-auth` SVC

```yaml
#
# Auth Middleware
#
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-forward-auth
  namespace: kube-system
spec:
  forwardAuth:
    address: http://<IPv4 of SVC in the cluster>:4181
    #trustForwardHeader: true
    authResponseHeaders:
      - X-Forwarded-User
```

I'll keep on investigating this afternoon as I'll get some spare time.

**Comment by kitos9112** [comment]
All right, problem solved. At least on my end.

A quick Google lookup does the job ar usually... It seems that when you deploy your Traefik Helm chart using `hostNetwork: true` you need to explicitly specify the dnsPolicy in the deployment config:

```yaml
deployment:
  dnsPolicy: ClusterFirstWithHostNet
```

Moreover, within your ingressRoute CR, make sure your middleware config comes along with the namespace where it's actually deployed:

```yaml
---
#
# IngressRoute
#
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
  labels:
    app: whoami
spec:
  entryPoints:
    - websecure (name of your entryPoint, I'm using Helm so it defaults to websecure)
  routes:
    - match: Host(`whoami.<yourDomain>.com`)
      kind: Rule
      services:
        - name: whoami
          port: 80
      middlewares:
        - name: traefik-forward-auth
          namespace: kube-system <<<<< This piece got missing in my initial config
```

Credits to https://github.com/traefik/traefik/issues/5543
