### ISSUE TITLE
Add support for reading config parameters from files for use with docker secrets

### ISSUE THREAD

**Issue by WisdomWolf** [thomseddon/traefik-forward-auth#24]
Would like to be able to provide things like client-id, client-secret, and secret from docker secrets stored as files.  Could either load the entire config from a file stored as a docker secret or (preferably) have additional environment variable options like the docker example:

- CLIENT_ID_FILE
- CLIENT_SECRET_FILE
- SECRET_FILE

This would enable the use of secrets in a similar fashion to the example:
```
environment:
       CLIENT_ID_FILE: /run/secrets/oauth_client_id
```

**Comment by thomseddon** [comment]
Hi,

This can already be done (it's how I pass those secrets :), it's described at the end of the configuration section of the README: https://github.com/thomseddon/traefik-forward-auth/blob/master/README.md#configuration 

Let me know if you have any problems

**Comment by maximunited** [comment]
I don't think this is working in v2. at least not for me:
I've tried:
```
PROVIDERS_GOOGLE_CLIENT_ID_FILE=/run/secrets/google_client_id
PROVIDERS_GOOGLE_CLIENT_ID=/run/secrets/google_client_id
CLIENT_ID_FILE=/run/secrets/google_client_id
CLIENT_ID=/run/secrets/google_client_id
```

**Comment by maximunited** [comment]
> I don't think this is working in v2. at least not for me:
> I've tried:
> 
> ```
> PROVIDERS_GOOGLE_CLIENT_ID_FILE=/run/secrets/google_client_id
> PROVIDERS_GOOGLE_CLIENT_ID=/run/secrets/google_client_id
> CLIENT_ID_FILE=/run/secrets/google_client_id
> CLIENT_ID=/run/secrets/google_client_id
> ```

answering to myself. The answer was in issue #147 
configuring docker-compose:
```
    environment:
      CONFIG: /run/secrets/credentials
    secrets:
      - credentials

secrets:
  credentials:
    name: oauth2_credentials
    file: ${SECRETSDIR}/oauth2_credentials.ini
```
