### ISSUE TITLE
traefik-forward-auth insists on requiring google credentials though I want to use OIDC only

### ISSUE THREAD

**Issue by skuzzle** [thomseddon/traefik-forward-auth#240]
Hi,
I'm basically using the selective auth example in docker swarm mode from [here](https://github.com/thomseddon/traefik-forward-auth/blob/master/examples/traefik-v2/swarm/docker-compose-oidc.ymll). But instead of using `google`, I want to only use the `oidc` provider:

```
  oauth:
    image: thomseddon/traefik-forward-auth:2
    environment:
      DEFAULT_PROVIDER: oidc
      PROVIDERS_OIDC_ISSUER_URL: https://...
      PROVIDERS_OIDC_CLIENT_ID: secret
      PROVIDERS_OIDC_CLIENT_SECRET: secret
      SECRET: secret
    deploy:
      labels:
        traefik.http.middlewares.oauth.forwardauth.address: http://oauth:4181
        traefik.http.middlewares.oauth.forwardauth.authResponseHeaders: X-Forwarded-User
        traefik.http.services.oauth.loadbalancer.server.port: 4181
```

When deploying the service like this it insists on requiring the `google` provider configuration:
```
evel=fatal msg="providers.google.client-id, providers.google.client-secret must be set"
```

I also tried to configure the `google` credentials with dummy values but that didn't help.  This is the configuration that is being logged upon starting the container. In this example, I configured dummy values for google client id and -secret:
```
{
    "LogLevel": "debug",
    "LogFormat": "text",
    "AuthHost": "",
    "CookieDomains": null,
    "InsecureCookie": false,
    "CookieName": "_forward_auth",
    "CSRFCookieName": "_forward_auth_csrf",
    "DefaultAction": "auth",
    "DefaultProvider": "oidc",
    "Domains": null,
    "LifetimeString": 43200,
    "LogoutRedirect": "",
    "MatchWhitelistOrDomain": false,
    "Path": "/_oauth",
    "Whitelist": null,
    "Providers": {
        "Google": {
            "ClientID": "xxx",
            "Scope": "",
            "Prompt": "select_account",
            "LoginURL": null,
            "TokenURL": null,
            "UserURL": null
        },
        "OIDC": {
            "IssuerURL": "[redacted]",
            "ClientID": "[redacted]",
            "Resource": "",
            "Config": {
                "ClientID": "[redacted]",
                "ClientSecret": "[redacted]",
                "Endpoint": {
                    "AuthURL": "[redacted]",
                    "TokenURL": "[redacted]",
                    "AuthStyle": 0
                },
                "RedirectURL": "",
                "Scopes": ["openid", "profile", "email"]
            }
        },
        "GenericOAuth": {
            "AuthURL": "",
            "TokenURL": "",
            "UserURL": "",
            "ClientID": "",
            "Scopes": ["profile", "email"],
            "TokenStyle": "header",
            "Resource": "",
            "Config": null
        }
    },
    "Rules": {},
    "Lifetime": 43200000000000,
    "CookieDomainsLegacy": null,
    "CookieSecureLegacy": "",
    "ClientIdLegacy": "",
    "PromptLegacy": ""
}
```

It feels like I am missing something obvious here?

**Comment by skuzzle** [comment]
Using version `2.2` of the docker image seems to resolve the problem. I guess this should be fixed in the examples as well?

**Comment by thomseddon** [comment]
The `2` tag on docker hub should pull the same image as `2.2` at the moment, I wonder if you had an old image cached?

**Comment by MatteoGioioso** [comment]
Hello, same bug here moving to 2.2 did not solve this issue, any workaround?

**Comment by zhou1591** [comment]
Can you send a complete docker configuration?

**Comment by skuzzle** [comment]
Maybe its some weird caching issue? You should check your image's hash and see whether it matches this one: ` sha256:4915f15bf88f72a71f0e756ccb5ad981de74cf2d9020085e9f915caf68cbe3d2`. That is what I'm running successfully with the following configuration in docker swarm (replace the `xxx` with a proper name):

```yaml
services:
  ## some service using oauth with forward authentication
  xxx:
    image: ...
    deploy:
      labels:
        traefik.enable: 'true'
        traefik.http.routers.xxx.tls: 'true'
        traefik.http.routers.xxx.tls.certresolver: le
        traefik.http.routers.xxx.rule: Host(`xxx.yz`)
        traefik.http.routers.xxx.entrypoints: https
        traefik.http.routers.xxx.middlewares: xxx-oauth
        traefik.http.services.xxx.loadbalancer.server.port: 8080
    networks:
    - traefik_proxy
    - default

  # forward auth container
  xxx-oauth:
    image: thomseddon/traefik-forward-auth:2.2
    environment:
    - DEFAULT_PROVIDER=oidc
    - PROVIDERS_OIDC_ISSUER_URL=<hidden>
    - PROVIDERS_OIDC_CLIENT_ID=<hidden>
    - PROVIDERS_OIDC_CLIENT_SECRET=<hidden>
    - SECRET=<hidden>
    - LOG_LEVEL=debug
    deploy:
      labels:
      - 'traefik.enable=true'
      - 'traefik.http.middlewares.xxx-oauth.forwardauth.address=http://xxx-oauth:4181'
      - 'traefik.http.middlewares.xxx-oauth.forwardauth.authResponseHeaders=X-Forwarded-User'
      - 'traefik.http.services.xxx-oauth.loadbalancer.server.port=4181'
    networks:
    - default
    - traefik_proxy
```
