### ISSUE TITLE
Unregistered Redirect URI

### ISSUE THREAD

**Issue by v7lin** [thomseddon/traefik-forward-auth#246]
```
https://gitea.haitanyule.com/login/oauth/authorize?client_id=24ff935f-6c45-4bf7-921b-c3e418b4c5e1&redirect_uri=http%3A%2F%2Ftraefik-forward-auth.haitanyule.com%2F_oauth&response_type=code&scope=profile+email&state=a46b7447e20fd07a0359c15ea4945599%3Ageneric-oauth%3Ahttp%3A%2F%2Ftraefik-forward-auth.haitanyule.com
```

```yaml
# 版本
version: "3.7"

# 服务
services:

  # 暂不支持设置时区
  traefik:
    container_name: traefik
    image: traefik:v2.4.8
    restart: always
    hostname: traefik
    ports:
      - 22:22
      - 80:80
      - 443:443
#      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/certs:/certs
      - ./traefik/certs.yml:/etc/traefik/dynamic_conf/conf.yml
      - ../dev-ops-repo/traefik/acme:/etc/traefik/acme
#    environment:
#      - TZ=${TIME_ZONE:-Asia/Shanghai}
    command:
#      - "--log.level=DEBUG"
      - "--api=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file=true"
      - "--providers.file.directory=/etc/traefik/dynamic_conf"
      - "--providers.file.watch=true"
      - "--entrypoints.ssh.address=:22"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
#      - "--certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL:-traefik@traefik.com}" # ocsp(在线证书状态协议, http://ocsp.int-x3.letsencrypt.org/)无法正常访问
##      - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory" # 默认
##      - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory" # staging
#      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme-v2.json" # 默认
##      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme-staging-v2.json" # staging
#      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
#      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.service=api@internal" # 不能用 traefik，除非开启 --api.insecure=true
      - "traefik.http.routers.traefik.rule=Host(`traefik.${SERVER_DOMAIN:-localhost}`)"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.middlewares=redirecttls"
      - "traefik.http.middlewares.redirecttls.redirectscheme.scheme=https"
      - "traefik.http.routers.traefiktls.service=api@internal" # 不能用 traefik，除非开启 --api.insecure=true
      - "traefik.http.routers.traefiktls.rule=Host(`traefik.${SERVER_DOMAIN:-localhost}`)"
      - "traefik.http.routers.traefiktls.entrypoints=https"
      - "traefik.http.routers.traefiktls.tls=true"
#      - "traefik.http.routers.traefiktls.tls.certresolver=letsencrypt"
#      - "traefik.http.routers.traefiktls.middlewares=auth"
#      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_AUTH_BASIC}"
      - "traefik.http.routers.traefiktls.middlewares=traefik-forward-auth"

  traefik-forward-auth:
    container_name: traefik-forward-auth
    image: thomseddon/traefik-forward-auth:2.2
    restart: on-failure
    hostname: traefik-forward-auth
#    ports:
#      - 4181
    environment:
#      - TZ=${TIME_ZONE:-Asia/Shanghai}
      - DEFAULT_PROVIDER=generic-oauth
      - PROVIDERS_GENERIC_OAUTH_AUTH_URL=https://gitea.${SERVER_DOMAIN:-localhost}/login/oauth/authorize
      - PROVIDERS_GENERIC_OAUTH_TOKEN_URL=https://gitea.${SERVER_DOMAIN:-localhost}/login/oauth/access_token
      - PROVIDERS_GENERIC_OAUTH_USER_URL=https://gitea.${SERVER_DOMAIN:-localhost}/api/v1/user
      - PROVIDERS_GENERIC_OAUTH_CLIENT_ID=${GITEA_CLIENT_ID?err}
      - PROVIDERS_GENERIC_OAUTH_CLIENT_SECRET=${GITEA_CLIENT_SECRET?err}
      - PROVIDERS_GENERIC_OAUTH_TOKEN_STYLE=query
      - SECRET=${TRAEFIK_FORWARD_AUTH_SECRET?err}
#      # INSECURE_COOKIE is required if not using a https entrypoint
#      - INSECURE_COOKIE=true
#      - LOG_LEVEL=debug
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"
      - "traefik.http.routers.traefik-forward-auth.service=traefik-forward-auth"
      - "traefik.http.routers.traefik-forward-auth.rule=Host(`traefik-forward-auth.${SERVER_DOMAIN:-localhost}`)"
      - "traefik.http.routers.traefik-forward-auth.entrypoints=http"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth.${SERVER_DOMAIN:-localhost}"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"

  # git 私库
  gitea:
    container_name: gitea
    image: gitea/gitea:1.13.6
    restart: on-failure
    hostname: gitea
#    ports:
#      - 3000
#      - 22
    volumes:
      - ../dev-ops-repo/gitea:/data
    environment:
      - TZ=${TIME_ZONE:-Asia/Shanghai}
      - APP_NAME=Gitea
      - USER_UID=1000
      - USER_GID=1000
      - ROOT_URL=https://gitea.${SERVER_DOMAIN:-localhost}/
      - DISABLE_SSH=true
      - DB_TYPE=sqlite3
      - DISABLE_REGISTRATION=true
      - REQUIRE_SIGNIN_VIEW=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
      - "traefik.http.routers.gitea.service=gitea"
      - "traefik.http.routers.gitea.rule=Host(`gitea.${SERVER_DOMAIN:-localhost}`)"
      - "traefik.http.routers.gitea.entrypoints=http"
      - "traefik.http.routers.gitea.middlewares=redirecttls"
      - "traefik.http.routers.giteatls.service=gitea"
      - "traefik.http.routers.giteatls.rule=Host(`gitea.${SERVER_DOMAIN:-localhost}`)"
      - "traefik.http.routers.giteatls.entrypoints=https"
      - "traefik.http.routers.giteatls.tls=true"
#      - "traefik.http.routers.giteatls.tls.certresolver=letsencrypt"

```
