### ISSUE TITLE
No X-Forwarded-User in the headers with Google provider

### ISSUE THREAD

**Issue by mbonnafon** [thomseddon/traefik-forward-auth#263]
Hi, 

First of all, thank you for this middleware!

I use it in Auth Host Mode with the Google provider. The authentication part works perfectly and I can see the `_forward_auth_csrf` and `_forward_auth` session cookies in my browser. However, the `X-Forwarded-User` does not seem to be propagated to the end.

I'm running it in a Kubernetes cluster, when I check the logs of my Traefik, I can see that multiple `X-Fowarded` are present: 
```json
{
  "Method": "GET",
  "URL": {},
  "Proto": "HTTP/2.0",
  "Header": {
    "X-Forwarded-Host": [
      "grafana.mydomain.net"
    ],
    "X-Forwarded-Server": [
      "traefik-57b579f4fc-kvhqc"
    ],
    "X-Forwarded-User": [
      "me@gmail.com"
    ]
  },
  "Host": "grafana.mydomain.net",
  "RequestURI": "/login",
}
```
My middleware allows the forward:
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: forward-auth
  namespace: traefik
spec:
  forwardAuth:
    address: http://forward-auth:4181
    authResponseHeaders:
      - X-Forwarded-User
      - X-Forwarded-Host
    trustForwardHeader: true
```

Here's my `traefik-forward-auth` logs 
```
time="2021-06-25T15:52:34Z" level=debug msg="Authenticating request" cookies="[redirect_to=%2F _forward_auth_csrf=value _forward_auth=val=|integer|me@gmail.com]" handler=Auth host=grafana.mydomain.net method=GET proto=https rule=default source_ip=ip uri=/login
time="2021-06-25T15:52:34Z" level=debug msg="Allowing valid request" handler=Auth host=grafana.mydomain.net method=GET proto=https rule=default source_ip=ip uri=/login
```

But in my browser, I have no `x-forwarded-*`. Do you have any clue about this behavior? If needed, you can find my full config here: https://gist.github.com/mbonnafon/bd75c2c5c82be1715619a88377fc8c2f

Thank you in advance!
