### ISSUE TITLE
No redirect to keycloak

### ISSUE THREAD

**Issue by sirTomasson** [thomseddon/traefik-forward-auth#265]
I am trying to get `traefik + treafik-forward-auth + keycloak` working. Problem is that I am getting a blank page when browsing to `whoami.example.org`.

The `traefik-forward-auth` debug logs only print the configuration output. In other words I don't see any signs that `traefik-forward-auth` is getting requests.

Debug log:
```
traefik-forward-auth_1  | time="2021-07-05T10:10:24Z" level=debug msg="Starting with config" config="{\"LogLevel\":\"debug\",\"LogFormat\":\"text\",\"AuthHost\":\"\",\"CookieDomains\":null,\"InsecureCookie\":true,\"CookieName\":\"_forward_auth\",\"CSRFCookieName\":\"_forward_auth_csrf\",\"DefaultAction\":\"auth\",\"DefaultProvider\":\"oidc\",\"Domains\":null,\"LifetimeString\":43200,\"LogoutRedirect\":\"\",\"MatchWhitelistOrDomain\":false,\"Path\":\"/_oauth\",\"Whitelist\":null,\"Providers\":{\"Google\":{\"ClientID\":\"\",\"Scope\":\"\",\"Prompt\":\"select_account\",\"LoginURL\":null,\"TokenURL\":null,\"UserURL\":null},\"OIDC\":{\"IssuerURL\":\"http://keycloak.example.org/auth/realms/master\",\"ClientID\":\"traefik-forward-auth\",\"Resource\":\"\",\"Config\":{\"ClientID\":\"traefik-forward-auth\",\"ClientSecret\":\"98acf50b-05f8-49a5-a3f8-43ba88661f49\",\"Endpoint\":{\"AuthURL\":\"http://keycloak.example.org/auth/realms/master/protocol/openid-connect/auth\",\"TokenURL\":\"http://keycloak.example.org/auth/realms/master/protocol/openid-connect/token\",\"AuthStyle\":0},\"RedirectURL\":\"\",\"Scopes\":[\"openid\",\"profile\",\"email\"]}},\"GenericOAuth\":{\"AuthURL\":\"\",\"TokenURL\":\"\",\"UserURL\":\"\",\"ClientID\":\"\",\"Scopes\":[\"profile\",\"email\"],\"TokenStyle\":\"header\",\"Resource\":\"\",\"Config\":null}},\"Rules\":{},\"Lifetime\":43200000000000,\"CookieDomainsLegacy\":null,\"CookieSecureLegacy\":\"\",\"ClientIdLegacy\":\"\",\"PromptLegacy\":\"\"}"
traefik-forward-auth_1  | time="2021-07-05T10:10:24Z" level=info msg="Listening on :4181"
```

This is my setup:
```
version: "3.0"

services:
  gateway:
    image: traefik:v2.4.8
    command:
      - "--providers.docker"
      - "--entryPoints.http.address=:80"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--log.level=DEBUG"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80 # entrypoint
      - 8080:8080 # dashboard
    networks:
      - gateway_net

  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:2
    command:
      - "--default-provider=oidc"
      - "--providers.oidc.issuer-url=http://keycloak.example.org/auth/realms/master"
      - "--providers.oidc.client-id=traefik-forward-auth"
      - "--providers.oidc.client-secret=traefik-forward-auth-client-secret"
      - "--secret=128f695f372a04736fc5467401582196"
      - "--insecure-cookie"
      - "--cookie-domain=example.org"
      - "--auth-host=keycloak.example.org"
      - "--log-level=debug"
    labels:
      - "traefik.http.routers.traefik-forward-auth.rule=Host(`auth.example.org`)"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.trustForwardHeader=true"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"

  whoami:
    image: containous/whoami
    networks:
      - gateway_net
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.example.org`)"
      - "traefik.http.routers.whoami.middlewares=traefik-forward-auth"

  auth:
    image: quay.io/keycloak/keycloak:14.0.0
    environment:
      - "KEYCLOAK_USER=admin"
      - "KEYCLOAK_PASSWORD=admin@123"
      - "DB_VENDOR=postgres"
      - "DB_USER=keycloak"
      - "DB_PASSWORD=keycloak"
      - "DB_ADDR=auth-db"
    networks:
      - gateway_net
    labels:
      - "traefik.http.routers.auth.rule=Host(`keycloak.example.org`)"
    depends_on:
      - auth-db

  auth-db:
    image: postgres
    environment:
      - "POSTGRES_DB=keycloak"
      - "POSTGRES_USER=keycloak"
      - "POSTGRES_PASSWORD=keycloak"
    networks:
      - gateway_net
```

I think I'm missing something obvious. 

Any help would be appriciated.

Thanks,

Youri
