### ISSUE TITLE
Dynamic Auth Rules

### ISSUE THREAD

**Issue by ksankar1993** [thomseddon/traefik-forward-auth#277]
is it possible to add dynamic rule for this middleware in IngressRouter? Currently, the rules are taken either from config file or environment variable. But I would to add a rule for a service when it is deployed.  

Expecting something like below.

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
  labels:
    app: whoami
spec:
  entryPoints:
    - web
  routes:
  - match: PathPrefix(`/who`)
    kind: Rule
    services:
      - name: whoami
        port: 80
    middlewares:
      - name: traefik-forward-auth
      - rule-definitions: 
           name: <<RULE NAME>>
           param: <<PARAM NAME>>
  tls:
    certresolver: default
```

when this Route deployed, middleware should load the rule defined inside this.

**Comment by sanzoghenzo** [comment]
+1, this would be greatly appreciated!

I still have to move to kubernetes, so I currently would like to do that in Docker compose, specifically to make use of auth host mode with multiple services, some of them needs to be restricted to admins only.

```
services:
  frontend:
    # ...
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`frontend.example.com`) && PathPrefix(`/api`)
      - traefik.http.routers.frontend.middlewares="traefik-forward-auth"
      - traefik-forward-auth.rules.<<RULE NAME>>.action=<<ACTION>>
      - traefik-forward-auth.rule.<<RULE NAME>>.whitelist=<<WHITELIST>>
```
