### ISSUE TITLE
[BUG?] redirect_uri always seems to point to the requested domain, regardless of the AUTH_HOST setting

### ISSUE THREAD

**Issue by tnwhitwell** [thomseddon/traefik-forward-auth#28]
Hello!

I'm having some issues with getting forward-auth working.

I have multiple subdomains, and I'm trying to get the AUTH_HOST parameter set correctly, but regardless of what I set, the requested domain is always passed to google as `redirect_uri` and it throws an error due to the mismatch.

Any ideas on what I'm doing wrong? The tests are passing A-OK, so i'm stumped.

Thanks!

Tom

My Config:

```
  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:latest
    networks:
      - traefik
    environment:
      CLIENT_ID: ${TRAEFIK_AUTH_CLIENT_ID}
      CLIENT_SECRET: ${TRAEFIK_AUTH_CLIENT_SECRET}
      SECRET: ${TRAEFIK_AUTH_COOKIE_SECRET}
      COOKIE_SECURE: "false"
      DOMAIN: ${TRAEFIK_AUTH_DOMAINS}
      AUTH_HOST: ${TRAEFIK_AUTH_AUTH_HOST}
      LOG_LEVEL: debug
    labels:
      traefik.enable: true
      traefik.port: 4181
      traefik.backend: traefik-forward-auth
      traefik.frontend.rule: Host:${TRAEFIK_AUTH_AUTH_HOST}
```

**Comment by tnwhitwell** [comment]
Turns out I had the network this container on set as `internal`. Setting it as normal, and setting the cookie domain has fixed the problem!

**Comment by sharkoz** [comment]
How did you diagnose this ? I am having the same problem but my network is not internal, I don't know where to look... It behaves like I didn't set the AUTH_HOST variable but I did... I see nothing in the logs that would explain why ?

**Comment by thomseddon** [comment]
@sharkoz can you post your config?

There is more debug logging in v2, and I'm planning to add more before the release (hopefully next week, very close now in #26 ).

**Comment by sharkoz** [comment]
Thanks @thomseddon , I realised it didn't work because I didn't set the COOKIE_DOMAIN... I think I mixed up because I used the demo compose.yml from master while I am using the v2 image.
Anyway it's working fine for me now. Keep up the awesome work !

**Comment by seuf** [comment]
Hi, I've the same issue here in kube deployment. I'm mixing config, environment and command line options.
I've tried both the `latest` and `development` version.
here is my deployment :
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: traefik-worward-auth
  namespace: traefik
  labels:
    app: traefik-worward-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-worward-auth
  template:
    metadata:
      labels:
        app: traefik-worward-auth
    spec:
      containers:
        - image: thomseddon/traefik-forward-auth:development
          name: traefik-worward-auth
          args:
            - "--config=/config/traefik-forward-auth.config",
            - "--auth-host=auth.company.foo",
            - "--cookie-domain=www.company.fr",
            - "--cookie-domain=www.company.com",
            - "--cookie-domain=company.foo,
            - "--domain=company.com",
            - "--domain=company.fr",
            - "--cookie-name=_forward_auth",
            - "--csrf-cookie-name=_forward_auth_csrf",
            - "--log-level=debug",
          env:
            - name: SECRET
              value: randomstring
          volumeMount:
            - name: config
              mountPath: /config
              readOnly: true
        volume:
          name: config
          secret:
              secretName: traefik-forward-auth

```
the secret contain a 
```
client-id = <id>
secret-id = <secret>
```

I've created service for traefik-forward-auth + an ingress for auth.company.foo .
Then, when I create an ingress with annotations for traefik-forward-auth :
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: whoami
  namespace: apps
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
    ingress.kubernetes.io/auth-type: "forward"
    ingress.kubernetes.io/auth-url: "http://traefik-forward-auth.traefik.svc:4181"
    ingress.kubernetes.io/auth-remove-header: "false"
    ingress.kubernetes.io/auth-trust-headers: "true"
    ingress.kubernetes.io/auth-header-field: "X-Forwarded-User"
    ingress.kubernetes.io/auth-response-headers: "X-Forwarded-User"
spec:
  rules:
    - host: www.company.fr
      http:
        paths:
          - path: /whoami
            backend:
              serviceName: whoami
              servicePort: 80
```
But when I'm requesting `www.company.fr/whoami` in my browser, The Google login page try to redirected to `www.company.fr/_oauth` instead of `auth.company.foo`

Any idea what's wrong in my config ?
