### ISSUE TITLE
Traefik can't find auth middleware

### ISSUE THREAD

**Issue by Jleagle** [thomseddon/traefik-forward-auth#296]
Hi i am struggling to get this working. I am using file and docker providers. I have defined the middleware using:

```
http:
  middlewares:
    traefik-forward-auth:
      forwardAuth:
        address: "http://localhost:4181"
        authResponseHeaders:
          - "X-Forwarded-User"
```

and also

```
labels:
  - "traefik.http.middlewares.traefik-forward-auth.forwardAuth.address=http://traefik-forward-auth:4181"
  - "traefik.http.middlewares.traefik-forward-auth.forwardAuth.authResponseHeaders=X-Forwarded-User"
```

I am enabling the middleware using:

```
entryPoints:
  websecure:
    address: ":443"
    http:
      middlewares:
        - "traefik-forward-auth"
      tls:
        certResolver: "leresolver"
```

But when i load traefik i just get these in the logs, one for each docker service.

> level=error msg="middleware \"traefik-forward-auth@docker\" does not exist" entryPointName=websecure routerName=pihole@docker

There isn't a log like that for the services in the file provider weirdly. But the sites in both providers go down with a 404.

Thanks.
