### ISSUE TITLE
How to setup traefik-forward-auth with traefik/docker behind corporate load balancer

### ISSUE THREAD

**Issue by cschlaefcke** [thomseddon/traefik-forward-auth#308]
Hi there,

I am pretty new to traefik and though also even newer to traefik-forward-auth. I managed to setup an internet facing traefik together with traefik-forward-auth with an Azure AD provider in a demo/evaluation session and love the idea that almost any web service could be combined with single-sign-on in this combination.

Now I need to transfer my findings into another (more professional) scenario where traefik is not internet facing anymore instead it works behind a corporate load balancer. I can already access the desired traefik/docker based service via https but cannot get traefik-forward-auth running in this scenario.

My traefik docker container listens on port 8195 (on which the corp LB terminates) with an http entry point and I have not configured a https entry point. When I test my configuration it looks promising at the beginning - I get redirected to the azure login page get asked for my user name and password. But then I only get this error:

`AADSTS50011: The redirect URI 'http://myservice.example.com/_oauth' specified in the request does not match the redirect URIs configured for the application '********-****-****-****-************'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.`

And sure - the **http** in the request uri directly catched my eye and it looks like somehow just the unsecured uri has been forwarded to the azure portal. In the Azure app registration I double checked that I have placed the uri correctly and it certainly is **https**://myservice.example.com/_oauth

And now I wonder if this is related to the fact that my traefik has just a http endpoint and how this could be fixed. I already played around with header and redirect schemes but I was not able to make any progress with that.

**I hope this is possible at all and any hint pointing me in the right direction would be very much appreciated!**

This is my docker-compose.yml - for simplicity reasons I replaced my real service with a basic nginx:

```
version: '3'
services:
  traengx:
    image: nginx:latest
    container_name: traengx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traengx.entrypoints=http"
      - "traefik.http.routers.traengx.rule=Host(`myservice.example.com`)"
      - "traefik.http.routers.traengx.middlewares=traefik-forward-auth"
      - "traefik.http.services.traengx.loadbalancer.server.port=80"
    networks:
      - traefik_net

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "8195:8195"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./dynamic_conf.yml:/dynamic_conf.yml
      - /opt/docker/logs/traefik:/var/log
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - REGISTRY_HTTP_RELATIVEURLS=true
    networks:
      - traefik_net

  traefik-forward-auth:
    container_name: traefik-forward-auth
    image: thomseddon/traefik-forward-auth:2
    environment:
     - DEFAULT_PROVIDER=oidc
     - PROVIDERS_OIDC_ISSUER_URL=https://login.microsoftonline.com/********-****-****-****-************/v2.0
     - PROVIDERS_OIDC_CLIENT_ID=********-****-****-****-************
     - PROVIDERS_OIDC_CLIENT_SECRET=**********************
     - SECRET=********-****-****-****-************
     #- INSECURE_COOKIE=true
     - LOG_LEVEL=debug
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"
    networks:
      - traefik_net

networks:
  traefik_net:
    external: true
```

My traefik.yml

```
api:
  dashboard: true
  insecure: true
entryPoints:
  http:
    address: ":8195"
  ping:
    address: ":8888"
log:
  filePath: "/var/log/traefik.log"
  #format: json
  level: "DEBUG"
accessLog:
  filePath: "/var/log/access.log"
  #format: json
ping:
  entryPoint: "ping"
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: "./dynamic_conf.yml"
```

And the dynamic_conf.yml

```
http:
  middlewares:
    secHeaders:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        #sslRedirect: true
        #HSTS Configuration
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
```

The stdout when starting the docker-compose.yml:

```
Attaching to traefik-forward-auth, traefik, traengx
traengx                 | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
traengx                 | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
traengx                 | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
traengx                 | 10-listen-on-ipv6-by-default.sh: Getting the checksum of /etc/nginx/conf.d/default.conf
traengx                 | 10-listen-on-ipv6-by-default.sh: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
traengx                 | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
traengx                 | /docker-entrypoint.sh: Configuration complete; ready for start up
traefik                 | time="2022-04-07T23:03:16+02:00" level=info msg="Configuration loaded from file: /traefik.yml"
traefik-forward-auth    | time="2022-04-07T21:03:20Z" level=debug msg="Starting with config" config="{\"LogLevel\":\"debug\",\"LogFormat\":\"text\",\"AuthHost\":\"\",\"CookieDomains\":null,\"InsecureCookie\":false,\"CookieName\":\"_forward_auth\",\"CSRFCookieName\":\"_forward_auth_csrf\",\"DefaultAction\":\"auth\",\"DefaultProvider\":\"oidc\",\"Domains\":null,\"LifetimeString\":43200,\"LogoutRedirect\":\"\",\"MatchWhitelistOrDomain\":false,\"Path\":\"/_oauth\",\"Whitelist\":null,\"Providers\":{\"Google\":{\"ClientID\":\"\",\"Scope\":\"\",\"Prompt\":\"select_account\",\"LoginURL\":null,\"TokenURL\":null,\"UserURL\":null},\"OIDC\":{\"IssuerURL\":\"https://login.microsoftonline.com/********-****-****-****-************/v2.0\",\"ClientID\":\"********-****-****-****-************\",\"Resource\":\"\",\"Config\":{\"ClientID\":\"********-****-****-****-************\",\"ClientSecret\":\"**********************\",\"Endpoint\":{\"AuthURL\":\"https://login.microsoftonline.com/********-****-****-****-************/oauth2/v2.0/authorize\",\"TokenURL\":\"https://login.microsoftonline.com/********-****-****-****-************/oauth2/v2.0/token\",\"AuthStyle\":0},\"RedirectURL\":\"\",\"Scopes\":[\"openid\",\"profile\",\"email\"]}},\"GenericOAuth\":{\"AuthURL\":\"\",\"TokenURL\":\"\",\"UserURL\":\"\",\"ClientID\":\"\",\"Scopes\":[\"profile\",\"email\"],\"TokenStyle\":\"header\",\"Resource\":\"\",\"Config\":null}},\"Rules\":{},\"Lifetime\":43200000000000,\"CookieDomainsLegacy\":null,\"CookieSecureLegacy\":\"\",\"ClientIdLegacy\":\"\",\"PromptLegacy\":\"\"}"
traefik-forward-auth    | time="2022-04-07T21:03:20Z" level=info msg="Listening on :4181"

```
And finally the output of traefik.log/access.log

```
time="2022-04-07T22:24:25+02:00" level=info msg="Traefik version 2.6.3 built on 2022-03-29T13:09:27Z"
time="2022-04-07T22:24:25+02:00" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"http\":{\"address\":\":8195\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"udp\":{\"timeout\":\"3s\"}},\"ping\":{\"address\":\":8888\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"udp\":{\"timeout\":\"3s\"}},\"traefik\":{\"address\":\":8080\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"udp\":{\"timeout\":\"3s\"}}},\"providers\":{\"providersThrottleDuration\":\"2s\",\"docker\":{\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"swarmModeRefreshSeconds\":\"15s\"},\"file\":{\"watch\":true,\"filename\":\"./dynamic_conf.yml\"}},\"api\":{\"insecure\":true,\"dashboard\":true},\"ping\":{\"entryPoint\":\"ping\",\"terminatingStatusCode\":503},\"log\":{\"level\":\"DEBUG\",\"filePath\":\"/var/log/traefik.log\",\"format\":\"common\"},\"accessLog\":{\"filePath\":\"/var/log/access.log\",\"format\":\"common\",\"filters\":{},\"fields\":{\"defaultMode\":\"keep\",\"headers\":{\"defaultMode\":\"drop\"}}},\"pilot\":{\"dashboard\":true}}"
time="2022-04-07T22:24:25+02:00" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://doc.traefik.io/traefik/contributing/data-collection/\n"
time="2022-04-07T22:24:25+02:00" level=info msg="Starting provider aggregator.ProviderAggregator"
time="2022-04-07T22:24:25+02:00" level=debug msg="Start TCP Server" entryPointName=traefik
time="2022-04-07T22:24:25+02:00" level=debug msg="Start TCP Server" entryPointName=http
time="2022-04-07T22:24:25+02:00" level=debug msg="Start TCP Server" entryPointName=ping
time="2022-04-07T22:24:25+02:00" level=info msg="Starting provider *file.Provider"
time="2022-04-07T22:24:25+02:00" level=debug msg="*file.Provider provider configuration: {\"watch\":true,\"filename\":\"./dynamic_conf.yml\"}"
time="2022-04-07T22:24:25+02:00" level=info msg="Starting provider *traefik.Provider"
time="2022-04-07T22:24:25+02:00" level=debug msg="*traefik.Provider provider configuration: {}"
time="2022-04-07T22:24:25+02:00" level=info msg="Starting provider *acme.ChallengeTLSALPN"
time="2022-04-07T22:24:25+02:00" level=info msg="Starting provider *docker.Provider"
time="2022-04-07T22:24:25+02:00" level=debug msg="*docker.Provider provider configuration: {\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"swarmModeRefreshSeconds\":\"15s\"}"
time="2022-04-07T22:24:25+02:00" level=debug msg="*acme.ChallengeTLSALPN provider configuration: {\"Timeout\":4000000000}"
time="2022-04-07T22:24:25+02:00" level=debug msg="Configuration received from provider file: {\"http\":{\"middlewares\":{\"secHeaders\":{\"headers\":{\"stsSeconds\":31536000,\"stsIncludeSubdomains\":true,\"stsPreload\":true,\"frameDeny\":true,\"customFrameOptionsValue\":\"SAMEORIGIN\",\"contentTypeNosniff\":true,\"browserXssFilter\":true}}}},\"tcp\":{},\"udp\":{},\"tls\":{}}" providerName=file
time="2022-04-07T22:24:25+02:00" level=debug msg="Configuration received from provider internal: {\"http\":{\"routers\":{\"api\":{\"entryPoints\":[\"traefik\"],\"service\":\"api@internal\",\"rule\":\"PathPrefix(`/api`)\",\"priority\":2147483646},\"dashboard\":{\"entryPoints\":[\"traefik\"],\"middlewares\":[\"dashboard_redirect@internal\",\"dashboard_stripprefix@internal\"],\"service\":\"dashboard@internal\",\"rule\":\"PathPrefix(`/`)\",\"priority\":2147483645},\"ping\":{\"entryPoints\":[\"ping\"],\"service\":\"ping@internal\",\"rule\":\"PathPrefix(`/ping`)\",\"priority\":2147483647}},\"services\":{\"api\":{},\"dashboard\":{},\"noop\":{},\"ping\":{}},\"middlewares\":{\"dashboard_redirect\":{\"redirectRegex\":{\"regex\":\"^(http:\\\\/\\\\/(\\\\[[\\\\w:.]+\\\\]|[\\\\w\\\\._-]+)(:\\\\d+)?)\\\\/$\",\"replacement\":\"${1}/dashboard/\",\"permanent\":true}},\"dashboard_stripprefix\":{\"stripPrefix\":{\"prefixes\":[\"/dashboard/\",\"/dashboard\"]}}},\"serversTransports\":{\"default\":{\"maxIdleConnsPerHost\":200}}},\"tcp\":{},\"tls\":{}}" providerName=internal
time="2022-04-07T22:24:25+02:00" level=debug msg="No default certificate, generating one" tlsStoreName=default
time="2022-04-07T22:24:25+02:00" level=debug msg="Provider connection established with docker 19.03.1 (API 1.40)" providerName=docker
time="2022-04-07T22:24:25+02:00" level=debug msg="Filtering disabled container" container=traefik-traefik-6f547c5cdd5f434fb914983ad7b20157fdc52613dba20ab5b1f57859334e8a64 providerName=docker
time="2022-04-07T22:24:25+02:00" level=debug msg="Configuration received from provider docker: {\"http\":{\"routers\":{\"traefik-forward-auth-traefik\":{\"service\":\"traefik-forward-auth\",\"rule\":\"Host(`traefik-forward-auth-traefik`)\"},\"traengx\":{\"entryPoints\":[\"http\"],\"middlewares\":[\"traefik-forward-auth\"],\"service\":\"traengx\",\"rule\":\"Host(`myservice.example.com`)\"}},\"services\":{\"traefik-forward-auth\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://192.168.224.4:4181\"}],\"passHostHeader\":true}},\"traengx\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://192.168.224.2:80\"}],\"passHostHeader\":true}}},\"middlewares\":{\"traefik-forward-auth\":{\"forwardAuth\":{\"address\":\"http://traefik-forward-auth:4181\",\"authResponseHeaders\":[\"X-Forwarded-User\"]}}}},\"tcp\":{},\"udp\":{}}" providerName=docker
time="2022-04-07T22:24:25+02:00" level=debug msg="Added outgoing tracing middleware ping@internal" entryPointName=ping routerName=ping@internal middlewareName=tracing middlewareType=TracingForwarder
time="2022-04-07T22:24:25+02:00" level=debug msg="Creating middleware" entryPointName=ping middlewareName=traefik-internal-recovery middlewareType=Recovery
time="2022-04-07T22:24:25+02:00" level=debug msg="Added outgoing tracing middleware dashboard@internal" entryPointName=traefik routerName=dashboard@internal middlewareName=tracing middlewareType=TracingForwarder
time="2022-04-07T22:24:25+02:00" level=debug msg="Creating middleware" routerName=dashboard@internal middlewareName=dashboard_stripprefix@internal middlewareType=StripPrefix entryPointName=traefik
time="2022-04-07T22:24:25+02:00" level=debug msg="Adding tracing to middleware" entryPointName=traefik routerName=dashboard@internal middlewareName=dashboard_stripprefix@internal
time="2022-04-07T22:24:25+02:00" level=debug msg="Creating middleware" entryPointName=traefik routerName=dashboard@internal middlewareName=dashboard_redirect@internal middlewareType=RedirectRegex
time="2022-04-07T22:24:25+02:00" level=debug msg="Setting up redirection from ^(http:\\/\\/(\\[[\\w:.]+\\]|[\\w\\._-]+)(:\\d+)?)\\/$ to ${1}/dashboard/" routerName=dashboard@internal middlewareName=dashboard_redirect@internal middlewareType=RedirectRegex entryPointName=traefik
time="2022-04-07T22:24:25+02:00" level=debug msg="Adding tracing to middleware" entryPointName=traefik middlewareName=dashboard_redirect@internal routerName=dashboard@internal
time="2022-04-07T22:24:25+02:00" level=debug msg="Added outgoing tracing middleware api@internal" entryPointName=traefik routerName=api@internal middlewareName=tracing middlewareType=TracingForwarder
time="2022-04-07T22:24:25+02:00" level=debug msg="Creating middleware" middlewareName=traefik-internal-recovery middlewareType=Recovery entryPointName=traefik
time="2022-04-07T22:24:25+02:00" level=debug msg="No entryPoint defined for this router, using the default one(s) instead: [http ping]" routerName=traefik-forward-auth-traefik
time="2022-04-07T22:24:25+02:00" level=debug msg="No default certificate, generating one" tlsStoreName=default
time="2022-04-07T22:24:26+02:00" level=debug msg="Creating middleware" middlewareName=pipelining middlewareType=Pipelining entryPointName=http routerName=traefik-forward-auth-traefik@docker serviceName=traefik-forward-auth
time="2022-04-07T22:24:26+02:00" level=debug msg="Creating load-balancer" serviceName=traefik-forward-auth entryPointName=http routerName=traefik-forward-auth-traefik@docker
time="2022-04-07T22:24:26+02:00" level=debug msg="Creating server 0 http://192.168.224.4:4181" serviceName=traefik-forward-auth serverName=0 entryPointName=http routerName=traefik-forward-auth-traefik@docker
time="2022-04-07T22:24:26+02:00" level=debug msg="child http://192.168.224.4:4181 now UP"
time="2022-04-07T22:24:26+02:00" level=debug msg="Propagating new UP status"
time="2022-04-07T22:24:26+02:00" level=debug msg="Added outgoing tracing middleware traefik-forward-auth" entryPointName=http routerName=traefik-forward-auth-traefik@docker middlewareName=tracing middlewareType=TracingForwarder
time="2022-04-07T22:24:26+02:00" level=debug msg="Creating middleware" middlewareName=pipelining middlewareType=Pipelining entryPointName=http routerName=traengx@docker serviceName=traengx
time="2022-04-07T22:24:26+02:00" level=debug msg="Creating load-balancer" entryPointName=http routerName=traengx@docker serviceName=traengx
time="2022-04-07T22:24:26+02:00" level=debug msg="Creating server 0 http://192.168.224.2:80" entryPointName=http routerName=traengx@docker serviceName=traengx serverName=0
time="2022-04-07T22:24:26+02:00" level=debug msg="child http://192.168.224.2:80 now UP"
time="2022-04-07T22:24:26+02:00" level=debug msg="Propagating new UP status"
time="2022-04-07T22:24:26+02:00" level=debug msg="Added outgoing tracing middleware traengx" routerName=traengx@docker entryPointName=http middlewareName=tracing middlewareType=TracingForwarder
time="2022-04-07T22:24:26+02:00" level=debug msg="Creating middleware" middlewareName=traefik-forward-auth@docker middlewareType=ForwardedAuthType entryPointName=http routerName=traengx@docker
time="2022-04-07T22:24:26+02:00" level=debug msg="Creating middleware" entryPointName=http middlewareName=traefik-internal-recovery middlewareType=Recovery
time="2022-04-07T22:24:26+02:00" level=debug msg="Added outgoing tracing middleware ping@internal" entryPointName=ping routerName=ping@internal middlewareName=tracing middlewareType=TracingForwarder
time="2022-04-07T22:24:26+02:00" level=debug msg="Creating middleware" entryPointName=ping middlewareName=traefik-internal-recovery middlewareType=Recovery
time="2022-04-07T22:24:26+02:00" level=debug msg="Added outgoing tracing middleware dashboard@internal" routerName=dashboard@internal middlewareType=TracingForwarder middlewareName=tracing entryPointName=traefik
time="2022-04-07T22:24:26+02:00" level=debug msg="Creating middleware" middlewareType=StripPrefix routerName=dashboard@internal entryPointName=traefik middlewareName=dashboard_stripprefix@internal
time="2022-04-07T22:24:26+02:00" level=debug msg="Adding tracing to middleware" middlewareName=dashboard_stripprefix@internal entryPointName=traefik routerName=dashboard@internal
time="2022-04-07T22:24:26+02:00" level=debug msg="Creating middleware" middlewareName=dashboard_redirect@internal middlewareType=RedirectRegex entryPointName=traefik routerName=dashboard@internal
time="2022-04-07T22:24:26+02:00" level=debug msg="Setting up redirection from ^(http:\\/\\/(\\[[\\w:.]+\\]|[\\w\\._-]+)(:\\d+)?)\\/$ to ${1}/dashboard/" middlewareName=dashboard_redirect@internal middlewareType=RedirectRegex entryPointName=traefik routerName=dashboard@internal
time="2022-04-07T22:24:26+02:00" level=debug msg="Adding tracing to middleware" routerName=dashboard@internal middlewareName=dashboard_redirect@internal entryPointName=traefik
time="2022-04-07T22:24:26+02:00" level=debug msg="Added outgoing tracing middleware api@internal" middlewareName=tracing middlewareType=TracingForwarder entryPointName=traefik routerName=api@internal
time="2022-04-07T22:24:26+02:00" level=debug msg="Creating middleware" entryPointName=traefik middlewareName=traefik-internal-recovery middlewareType=Recovery

==> /opt/docker/logs/traefik/access.log <==
172.29.32.12 - - [07/Apr/2022:20:24:35 +0000] "GET / HTTP/1.1" 404 19 "-" "-" 1 "-" "-" 0ms
172.29.56.161 - - [07/Apr/2022:20:24:36 +0000] "GET / HTTP/1.1" 404 19 "-" "-" 2 "-" "-" 0ms

==> /opt/docker/logs/traefik/traefik.log <==
time="2022-04-07T22:24:53+02:00" level=debug msg="Remote error http://traefik-forward-auth:4181. StatusCode: 307" middlewareName=traefik-forward-auth@docker middlewareType=ForwardedAuthType

==> /opt/docker/logs/traefik/access.log <==
172.29.32.12 - - [07/Apr/2022:20:24:53 +0000] "GET / HTTP/1.1" 307 404 "-" "-" 3 "traengx@docker" "-" 1ms
172.29.32.12 - - [07/Apr/2022:20:25:05 +0000] "GET / HTTP/1.1" 404 19 "-" "-" 4 "-" "-" 0ms
172.29.56.161 - - [07/Apr/2022:20:25:06 +0000] "GET / HTTP/1.1" 404 19 "-" "-" 5 "-" "-" 0ms

==> /opt/docker/logs/traefik/access.log <==
172.29.56.161 - - [07/Apr/2022:20:55:07 +0000] "GET / HTTP/1.1" 404 19 "-" "-" 125 "-" "-" 0ms
172.29.32.12 - - [07/Apr/2022:20:55:37 +0000] "GET / HTTP/1.1" 404 19 "-" "-" 126 "-" "-" 0ms
172.29.56.161 - - [07/Apr/2022:20:55:37 +0000] "GET / HTTP/1.1" 404 19 "-" "-" 127 "-" "-" 0ms
172.29.32.12 - - [07/Apr/2022:20:59:29 +0000] "GET / HTTP/1.1" 404 19 "-" "-" 1 "-" "-" 0ms
172.29.32.12 - - [07/Apr/2022:20:59:30 +0000] "GET /favicon.ico HTTP/1.1" 404 19 "-" "-" 2 "-" "-" 0ms
172.29.32.12 - - [07/Apr/2022:20:59:37 +0000] "GET / HTTP/1.1" 404 19 "-" "-" 3 "-" "-" 0ms
172.29.56.161 - - [07/Apr/2022:20:59:37 +0000] "GET / HTTP/1.1" 404 19 "-" "-" 4 "-" "-" 0ms
172.29.56.161 - - [07/Apr/2022:21:00:00 +0000] "GET / HTTP/1.1" 404 19 "-" "-" 5 "-" "-" 0ms
172.29.32.12 - - [07/Apr/2022:21:00:07 +0000] "GET / HTTP/1.1" 404 19 "-" "-" 6 "-" "-" 0ms
172.29.56.161 - - [07/Apr/2022:21:00:07 +0000] "GET / HTTP/1.1" 404 19 "-" "-" 7 "-" "-" 0ms

==> /opt/docker/logs/traefik/traefik.log <==
time="2022-04-07T23:03:16+02:00" level=debug msg="Adding tracing to middleware" middlewareName=dashboard_redirect@internal entryPointName=traefik routerName=dashboard@internal
time="2022-04-07T23:03:16+02:00" level=debug msg="Creating middleware" entryPointName=traefik middlewareName=traefik-internal-recovery middlewareType=Recovery
time="2022-04-07T23:03:16+02:00" level=debug msg="Creating middleware" entryPointName=http routerName=traengx@docker serviceName=traengx middlewareName=pipelining middlewareType=Pipelining
time="2022-04-07T23:03:16+02:00" level=debug msg="Creating load-balancer" entryPointName=http routerName=traengx@docker serviceName=traengx
time="2022-04-07T23:03:16+02:00" level=debug msg="Creating server 0 http://192.168.224.4:80" entryPointName=http routerName=traengx@docker serviceName=traengx serverName=0
time="2022-04-07T23:03:16+02:00" level=debug msg="child http://192.168.224.4:80 now UP"
time="2022-04-07T23:03:16+02:00" level=debug msg="Propagating new UP status"
time="2022-04-07T23:03:16+02:00" level=debug msg="Added outgoing tracing middleware traengx" routerName=traengx@docker middlewareName=tracing middlewareType=TracingForwarder entryPointName=http
time="2022-04-07T23:03:16+02:00" level=debug msg="Creating middleware" routerName=traengx@docker middlewareName=traefik-forward-auth@docker middlewareType=ForwardedAuthType entryPointName=http
time="2022-04-07T23:03:16+02:00" level=debug msg="Creating middleware" middlewareType=Recovery entryPointName=http middlewareName=traefik-internal-recovery

==> /opt/docker/logs/traefik/access.log <==
172.29.32.12 - - [07/Apr/2022:21:03:37 +0000] "GET / HTTP/1.1" 404 19 "-" "-" 1 "-" "-" 0ms
172.29.56.161 - - [07/Apr/2022:21:03:38 +0000] "GET / HTTP/1.1" 404 19 "-" "-" 2 "-" "-" 0ms
172.29.32.12 - - [07/Apr/2022:21:04:07 +0000] "GET / HTTP/1.1" 404 19 "-" "-" 3 "-" "-" 0ms
172.29.56.161 - - [07/Apr/2022:21:04:08 +0000] "GET / HTTP/1.1" 404 19 "-" "-" 4 "-" "-" 0ms

==> /opt/docker/logs/traefik/traefik.log <==
time="2022-04-07T23:04:23+02:00" level=debug msg="Remote error http://traefik-forward-auth:4181. StatusCode: 307" middlewareType=ForwardedAuthType middlewareName=traefik-forward-auth@docker
```

**Comment by cschlaefcke** [comment]
Hi there,
after playing with forward headers, settings and configuration I finally created an internal fork of this project and patched the source files config.go and auth.go to allow setting a hard coded (static) redirect URI or forcing the auth redirect to always return a https based redirect URI (flexible).

**config.go - line 43-44**
```
RedirectURL           string `long:"redirect-url" env:"REDIRECT_URL" description:"Override Redirect URI if X-Forwarded-Proto cannot be used"`
ForceHTTPSRedirectURI bool   `long:"force-https-redirect-uri" env:"FORCE_HTTPS_REDIRECT_URI" description:"Forces the redirect URI to HTTPS when operating behind load balancer"`

```

**auth.go - line 136-157**
```
// Get oauth redirect uri
func redirectUri(r *http.Request) string {
	result := fmt.Sprintf("%s%s", redirectBase(r), config.Path)
	if use, _ := useAuthDomain(r); use {
		log.Infof("USE_AUTH_DOMAIN", nil)
		p := r.Header.Get("X-Forwarded-Proto")
		result = fmt.Sprintf("%s://%s%s", p, config.AuthHost, config.Path)
	}

	//HDM: Redirect URL override in case X-Forwarded-Proto cannot work
	if config.RedirectURL != "" {
		result = config.RedirectURL
	}

	//HDM: Replace HTTP with HTTPS
	if config.ForceHTTPSRedirectURI {
		result = strings.ReplaceAll(result, "http://", "https://")
	}

	log.Infof("REDIRECT_URI :%s", result)
	return result
}
```

I am not sure if this is a good idea at all - at the moment it makes my use case work. Please feel free to adopt the features if useful or let me know how to improve if you think this is rubbish.

Cheers, Christian

**Comment by ektar** [comment]
Hi @cschlaefcke - I had the same question and found your issue.  Slightly different configuration but same effect - using EKS in AWS, TLS is terminating at load balancer so internal traffic looks like http, but need redirect to be https.  We were able to solve by chaining the header middleware with the forward auth - header goes first and sets the https proto (https://doc.traefik.io/traefik/middlewares/http/headers/#sslproxyheaders), then forward auth middleware connects to this plugin with that header.  The original code (https://github.com/thomseddon/traefik-forward-auth/blob/master/internal/auth.go#L136-L144) only checks the header value, not the actual proto used, so no further action needed.

**Comment by ektar** [comment]
It's been long enough that I'm forgetting details, hope this is what you're looking for, good luck!

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: internal-traefik-route
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: HostRegexp(`<from our helm chart...>`)
    middlewares:
      - name: ssl-proxy-headers
      - name: traefik-forward-auth
    services:
    - name: traefik-internal
      passHostHeader: true
      port: 80
      scheme: http
```
