### ISSUE TITLE
Not Authorized with Whitelisted Email

### ISSUE THREAD

**Issue by lightlySkewed** [thomseddon/traefik-forward-auth#324]
Hi all,

Thank you for this software. It has the potential to be a game changer for me.

I'm inching closer to getting it up and running, but I'm getting a weird error. I have myemail@example.com as a whitelisted email, but the logs give me:

level=warning msg="Invalid email" email=myemail@example.com handler=Auth host=traefik.mydomain.com method=GET proto=https rule=default source_ip=docker.ip uri=/favicon.ico

The error I receive at the target url (traefik.mydomain.com) is:

Not authorized

I've triple checked the spelling of the email address and can't figure out what I'm doing wrong. Does anyone see a problem with my docker-compose, middlewares, chains, or something else?

docker-compose.yml

```yaml

version: '3.8'

secrets:
  cloudflare_email:
    file: "./secrets/CF_API_EMAIL.secret"
  cloudflare_dns_api_token:
    file: "./secrets/CF_DNS_API_TOKEN.secret"

services:
  traefik:
    image: "traefik:v2.8"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # redirect insecure traffic to a secure connection
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.https.forwardedHeaders.trustedIPs=list_of_trusted_ips"
      # set up LetsEncrypt
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.letsencrypt.acme.email=myemail@example.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=list_of_resolver_ips"
      # set up the TLS configuration for our websecure listener
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certResolver=letsencrypt"
      - "--entrypoints.websecure.http.tls.domains[0].main=mydomain.com"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.mydomain.com"
      # define the location of the config file
      - "--providers.file.directory=/rules"
      - "--providers.file.watch=true"
    secrets:
      - "cloudflare_email"
      - "cloudflare_dns_api_token"
    environment:
      - CLOUDFLARE_EMAIL_FILE=/run/secrets/cloudflare_email
      - CLOUDFLARE_DNS_API_TOKEN_FILE=/run/secrets/cloudflare_dns_api_token
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./traefik2:/rules"
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.rule=Host(`traefik.mydomain.com`)"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=chain-oauth@file"

  oauth:
    container_name: oauth
    image: "thomseddon/traefik-forward-auth:latest"
    command:
      - "--whitelist=myemail@example.com"
    environment:
      - PROVIDERS_GOOGLE_CLIENT_ID=my_fancy_id
      - PROVIDERS_GOOGLE_CLIENT_SECRET=my_fancy_client_secret
      - SECRET=my_fancy_secret
      - WHITELIST=myemail@example.com
      - COOKIE_DOMAIN=mydomain.com
      - COOKIE_SECURE=true
      - INSECURE_COOKIE=false
      - AUTH_HOST=oauth.mydomain.com
      - URL_PATH=/_oauth
      - LOG_LEVEL=debug
      - LOG_FORMAT=text
      - LIFETIME=86400
      - DEFAULT_ACTION=auth
      - DEFAULT_PROVIDER=google
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.oauth.tls=true"
      - "traefik.http.routers.oauth.entrypoints=websecure"
      - "traefik.http.routers.oauth.rule=Host(`oauth.mydomain.com`)"
      ## Middlewares
      - "traefik.http.routers.oauth.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.oauth.service=oauth-svc"
      - "traefik.http.services.oauth-svc.loadbalancer.server.port=4181"

  # Cloudflare DDNS - Dynamic DNS Updater
  cf-ddns:
    container_name: cf-ddns
    image: oznu/cloudflare-ddns:latest
    restart: always
    secrets:
      - "cloudflare_dns_api_token"
    environment:
      - API_KEY=my_fancy_api_key
      - ZONE=mydomain.com
      - PROXIED=true
      - RRTYPE=A
      - DELETE_ON_STOP=false
      - DNS_SERVER=1.1.1.1

```

middlewares.yml

```yaml

http:
  middlewares:

    middlewares-rate-limit:
      rateLimit:
        average: 100
        burst: 50

    middlewares-https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true

    middlewares-oauth:
      forwardAuth:
        address: "http://oauth:4181" # Make sure you have the OAuth service in docker-compose.yml
        trustForwardHeader: true
        authResponseHeaders:
          - "X-Forwarded-User"

```

middleware-chains.yml

```yaml

http:
  middlewares:
    chain-oauth:
      chain:
        middlewares:
          - middlewares-rate-limit
          - middlewares-https-redirectscheme
          - middlewares-oauth

```

I'm sure I'm missing something dumb. I just have no idea what that thing is...

Thanks,
Mike
