### ISSUE TITLE
Not found  "_oauth" with Azure provider

### ISSUE THREAD

**Issue by vojtechvelkjop** [thomseddon/traefik-forward-auth#341]
Hello 
I would like to ask you I have configured app registration in Azure and set middleware in ingress and I can authenticate against Azure ad but response is 404.

404 page not found:
`https://<mydomain.com/_oauth?code=<cookie>`

It is true because my application didn't provide URLs  with /_outh so I suppose that my apps don't need to know any sso,salm and so on and this tools can do this work in behalf.

I have configured deployments and service
```
# filename app_auth_all_in_one.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: traefik-sso
  name: traefik-forward-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-sso
  template:
    metadata:
      labels:
        app: traefik-sso
    spec:
      containers:
        - name: traefik-forward-auth
          image: thomseddon/traefik-forward-auth:latest
          env:
            - name: DEFAULT_PROVIDER
              value: "oidc"
            - name: PROVIDERS_OIDC_ISSUER_URL
              valueFrom:
                secretKeyRef:
                  name: azuread
                  key: endpoint
            - name: PROVIDERS_OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: azuread
                  key: client_id
            - name: PROVIDERS_OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: azuread
                  key: client_secret
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: azuread
                  key: random_secret
            - name: LOG_LEVEL
              value: debug
          ports:
          - containerPort: 4181
            name: auth
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-sso
spec:
  selector:
    app: traefik-sso
  ports:
  - name: auth
    protocol: TCP
    port: 4181
    targetPort: 4181
```

traefik log
`time="2023-01-19T16:18:08Z" level=debug msg="Remote error http://traefik-sso.<namespace>.svc:4181. StatusCode: 307" middlewareName=<ns>-<middlewarename>@kubernetescrd middlewareType=ForwardedAuthType`

Thanks a lot for advice
