### ISSUE TITLE
Use docker secrets for environment variables

### ISSUE THREAD

**Issue by srad** [thomseddon/traefik-forward-auth#342]
Is there a way to use docker secrets for the environment variables?

**Comment by AnderssonPeter** [comment]
I did the following
```
secrets:
  google_oauth:
    file: "./oauth/secrets/google_oauth.secret"

container:
  secrets:
    - source: google_oauth
      target: /config
```

```
providers.google.client-id=
providers.google.client-secret=
secret=
whitelist=
whitelist=
```
