### ISSUE TITLE
Rules to allow api access match but doesn't redirect

### ISSUE THREAD

**Issue by pierreblais** [thomseddon/traefik-forward-auth#376]
Hello,

I have an issue while trying to add rules to allow api access.

## Context

Here is my configuration:

```yaml
  INSECURE_COOKIE: 'false'
  COOKIE_DOMAIN: my.domain.fr
  DOMAINS: my.domain.fr
  AUTH_HOST: auth. my.domain.fr
  LOG_LEVEL: debug
  URL_PATH: /_oauth
  DEFAULT_PROVIDER: oidc
  PROVIDERS_OIDC_ISSUER_URL: https://keycloak.my.other.domain/realms/tooling
  PROVIDERS_OIDC_CLIENT_ID: auth
  PROVIDERS_OIDC_CA_DIR: /config/ca.pem
  CONFIG: |
    rule.api_access.action=allow
    rule.api_access.rule=Host("whoami.my.domain.fr") && Headers("X-API-Authorization", "toto")
```

2 specifications:
- I'm using the latest docker images. (tags `2` or  `2.2.0` leads to infinite redirect loop with auth_host)
- I mounting manually keycloak ca certs

## Behaviour

Curl return a 5xx error: 

```bash
$ curl -I https://whoami.my.domain.fr -H "toto: toto"
HTTP/2 500
server: nginx
date: Fri, 17 May 2024 10:08:07 GMT
```

Here is the logs from auth server:

```logs
time="2024-05-17T10:07:37Z" level=debug msg="Allowing request" cookies="[]" handler=Allow host= whoami.my.domain.fr method=HEAD proto=https rule=api_access source_ip=<IP>uri=/
```

I can see that the rule match well `rule=api_access` but the curl doesn't work.

The default authentication with Keycloak (without `X-API-Authorization `) working well.

Is someone have the same problem ? I'm not sure if it's a configuration problem or a software issue so any help are welcome !
