### ISSUE TITLE
infinite login loop

### ISSUE THREAD

**Issue by ryzenpay** [thomseddon/traefik-forward-auth#399]
in the rules.ini, when making a rule such as:
`rule.docs.rule = Host(`example.com`)`
i am thrown into an infinite logging loop
but when i make a rule such as:
rule.joplin.rule = Host(`example.com`) && PathPrefix(`/admin`)
i can access example.com no problem, and get prompted for keycloak at /admin, which then lets me proceed and not throw me into an infinite logging loop.

Here are my configurations:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-staff-auth
  namespace: cs-systems-web
  labels:
    app: keycloak-staff-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-staff-auth
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: keycloak-staff-auth
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: thomseddon/traefik-forward-auth:2
        name: keycloak-staff-auth
        ports:
        - containerPort: 4181
          protocol: TCP
        env:
        - name: CONFIG
          value: "/config"
        - name: LOG_LEVEL
          value: "debug"
        - name: DEFAULT_PROVIDER
          value: "oidc"
        - name: DEFAULT_ACTION
          value: "allow"
        - name: PROVIDERS_OIDC_ISSUER_URL
          valueFrom:
            secretKeyRef:
              key: traefik-forward-auth-keycloak-issuer-url
              name: keycloak-staff-auth
        - name: PROVIDERS_OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: traefik-forward-auth-keycloak-client-id
              name: keycloak-staff-auth
        - name: PROVIDERS_OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: traefik-forward-auth-keycloak-client-secret
              name: keycloak-staff-auth
        - name: SECRET
          valueFrom:
            secretKeyRef:
              key: traefik-forward-auth-secret
              name: keycloak-staff-auth
        volumeMounts:
          - mountPath: /config
            name: configs
            subPath: rules.ini
      volumes:
        - configMap:
            defaultMode: 440
            name: keycloak-staff-auth
          name: configs
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: keycloak-staff-auth
  namespace: cs-systems-web
spec:
  forwardAuth:
    address: http://keycloak-staff-auth:4181
    authResponseHeaders:
      - X-Forwarded-User
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-staff-auth
  namespace: cs-systems-web
  labels:
    app: keycloak-staff-auth
spec:
  type: ClusterIP
  selector:
    app: keycloak-staff-auth
  ports:
  - name: auth-http
    port: 4181
    targetPort: 4181
---
apiVersion: v1
data:
  rules.ini: |
    rule.docs.action = auth
    rule.docs.provider = oidc
    rule.docs.rule = Host(`example.com`) && PathPrefix(`/`)
    rule.joplin.action = auth
    rule.joplin.provider = oidc
    rule.joplin.rule = Host(`example2.com`) && PathPrefix(`/admin`)
kind: ConfigMap
metadata:
  name: keycloak-staff-auth
  namespace: cs-systems-web
```
^ note: some of the variables are modified to hide the url's

i searched through the other issues and found some alike but they all had simple configuration issues.

**Comment by ryzenpay** [comment]
fix found:
why this works is incredibly annoying and dumb but rather than doing it the way im currently doing it "allowing all through but blacklisting certain paths" to "block everything, whitelist certain paths"

changed:
DEFAULT_ACTION from allow to auth
configmap to whitelist, example:
```
apiVersion: v1
data:
  rules.ini: |
    rule.joplin.action = allow
    rule.joplin.rule = Host(`example.com`)
    rule.joplin-admin.action = auth
    rule.joplin-admin.provider = oidc
    rule.joplin-admin.rule = Host(`example.com`) && PathPrefix(`/admin/`)
kind: ConfigMap
metadata:
  name: keycloak-staff-auth
  namespace: cs-systems-web
```

**Comment by dorinclisu** [comment]
Not sure how much it relates to your issue, but I faced the same infinite loop in my compose stack:
```yaml
  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:2
    ports:
      - 4181
    networks:
      - traefik
    environment:
      - LOG_LEVEL=${TRAEFIK_AUTH_LOG_LEVEL}
      - URL_PATH=${TRAEFIK_AUTH_PATH}
      - COOKIE_DOMAIN=${TRAEFIK_AUTH_COOKIE_DOMAIN}
      - DEFAULT_PROVIDER=oidc
      - PROVIDERS_OIDC_ISSUER_URL=${KC_HOSTNAME}/realms/${TRAEFIK_AUTH_REALM}
      - LOGOUT_REDIRECT=${KC_HOSTNAME}/realms/${TRAEFIK_AUTH_REALM}/protocol/openid-connect/logout
      - PROVIDERS_OIDC_CLIENT_ID=${TRAEFIK_AUTH_CLIENT_ID}
      - PROVIDERS_OIDC_CLIENT_SECRET=${TRAEFIK_AUTH_CLIENT_SECRET}
      - SECRET=${TRAEFIK_AUTH_COOKIE_SECRET}
      - LIFETIME=3600
    labels:
      - traefik.http.routers.tfauth.rule=PathPrefix(`${TRAEFIK_AUTH_PATH}`)
      - traefik.http.routers.tfauth.middlewares=sso   # this is required to avoid login loop
      - traefik.http.middlewares.sso.forwardauth.address=http://traefik-forward-auth:4181
      - traefik.http.middlewares.sso.forwardauth.authResponseHeaders=X-Forwarded-User
      - traefik.http.middlewares.sso.forwardauth.trustForwardHeader=true
```
See the label with a comment. Initially I thought it doesn't make sense to apply the forwardauth middleware onto itself, but without the association done by `traefik.http.routers.tfauth.middlewares=sso`, it not only gets stuck on login loop, but also the logout (/_oauth/logout) fails to clear the cookie (I performed the auth and got the cookie with the middleware applied, then I removed the middleware and tried the logout).
