### ISSUE TITLE
Redirect Loop when trying to use docker-compose auth-host example

### ISSUE THREAD

**Issue by shbatm** [thomseddon/traefik-forward-auth#42]
I'm having trouble and getting stuck in a redirect loop when trying to set-up an auth-host in the `docker-compose` file.  In your example, there is no `"COOKIE_DOMAINS=example.com"` in the docker-compose file, but the README states that this is required for an AUTH-HOST.  When I add that line, I get stuck in the loop.  When I remove it, the login works, but only for hosts that I have configured in the Google Developer Console (e.g. `https://host.example.com/_oauth` works).

docker-compose excerpt:
```yaml
  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth
    container_name: oauth
    networks:
      - traefik_proxy
    environment:
      - CLIENT_ID=<client>.apps.googleusercontent.com
      - CLIENT_SECRET=<secret>
      - SECRET=<secret>
      - COOKIE_SECURE=false
      - DOMAIN=example.com
      - AUTH_HOST=auth.example.com
      - COOKIE_DOMAINS=example.com
      - LOG_LEVEL=debug
    # When using an auth host, adding it here prompts traefik to generate certs
    labels:
      - "traefik.enable=true"
      - "traefik.port=4181"
      - "traefik.backend=traefik-forward-auth"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.rule=Host:auth.example.com"
  traefik:
    hostname: traefik
    image: traefik:latest
    container_name: traefik
    restart: always
    domainname: ${DOMAINNAME}
    networks:
      - viki
      - traefik_proxy
    ports:
      - "80:80"
      - "127.0.0.1:443:443"
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.${DOMAINNAME}"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      # - "traefik.frontend.auth.basic.users=${HTTP_USERNAME}:${HTTP_PASSWORD}"
      - "traefik.frontend.auth.forward.address=https://auth.example.com"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User"
      - "traefik.frontend.auth.forward.trustForwardHeader=true"
```
Looking at the log, it looks like its just going in a circle between google and auth.example.com... and not receiving a redirect_uri.  

Is there anything else I can check? 

EDIT: Log excerpt:
```
time="2019-04-18T18:00:32Z" level=debug msg="Set CSRF cookie and redirecting to google login" SourceIP=172.18.0.1
time="2019-04-18T18:00:32Z" level=debug msg="Handling request" Headers="map[X-Forwarded-Host:[auth.example.com] X-Forwarded-Server:[traefik.example.com] Cookie:[_forward_auth_csrf=c415a1fc8421bd7a01ad61e8cafa6c4e] Referer:[https://accounts.youtube.com/accounts/SetSID] X-Forwarded-Port:[443] X-Forwarded-Proto:[https] Accept:[text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3] Accept-Language:[en-US,en;q=0.9] Cache-Control:[max-age=0] X-Forwarded-For:[172.18.0.1] User-Agent:[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36] Accept-Encoding:[gzip, deflate, br] Upgrade-Insecure-Requests:[1] Dnt:[1] X-Real-Ip:[172.18.0.1]]" SourceIP=172.18.0.1
time="2019-04-18T18:00:32Z" level=debug msg="Set CSRF cookie and redirecting to google login" SourceIP=172.18.0.1
time="2019-04-18T18:00:32Z" level=debug msg="Handling request" Headers="map[X-Real-Ip:[172.18.0.1] Accept-Encoding:[gzip, deflate, br] Dnt:[1] Referer:[https://accounts.youtube.com/accounts/SetSID] Accept:[text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3] X-Forwarded-Server:[traefik.example.com] Upgrade-Insecure-Requests:[1] X-Forwarded-For:[172.18.0.1] X-Forwarded-Host:[auth.example.com] X-Forwarded-Port:[443] X-Forwarded-Proto:[https] User-Agent:[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36] Cache-Control:[max-age=0] Cookie:[_forward_auth_csrf=29127a11f27310bd7184cc304d1ff62e] Accept-Language:[en-US,en;q=0.9]]" SourceIP=172.18.0.1
time="2019-04-18T18:00:32Z" level=debug msg="Set CSRF cookie and redirecting to google login" SourceIP=172.18.0.1
time="2019-04-18T18:00:33Z" level=debug msg="Handling request" Headers="map[Accept-Encoding:[gzip, deflate, br] Cache-Control:[max-age=0] X-Forwarded-Server:[traefik.example.com] X-Real-Ip:[172.18.0.1] Dnt:[1] Referer:[https://accounts.youtube.com/accounts/SetSID] Upgrade-Insecure-Requests:[1] X-Forwarded-For:[172.18.0.1] User-Agent:[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36] Accept:[text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3] Accept-Language:[en-US,en;q=0.9] X-Forwarded-Port:[443] Cookie:[_forward_auth_csrf=5ecbc788d4e49c3fc94820630ebc80fd] X-Forwarded-Host:[auth.example.com] X-Forwarded-Proto:[https]]" SourceIP=172.18.0.1
time="2019-04-18T18:00:33Z" level=debug msg="Set CSRF cookie and redirecting to google login" SourceIP=172.18.0.1
time="2019-04-18T18:00:33Z" level=debug msg="Handling request" Headers="map[X-Forwarded-Server:[traefik.example.com] X-Real-Ip:[172.18.0.1] Accept-Encoding:[gzip, deflate, br] Dnt:[1] Upgrade-Insecure-Requests:[1] X-Forwarded-Host:[auth.example.com] User-Agent:[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36] Cookie:[_forward_auth_csrf=3f64fb5a64c88816db64cef8becb02e3] X-Forwarded-Proto:[https] X-Forwarded-Port:[443] X-Forwarded-For:[172.18.0.1] Accept:[text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3] Accept-Language:[en-US,en;q=0.9] Cache-Control:[max-age=0] Referer:[https://accounts.youtube.com/accounts/SetSID]]" SourceIP=172.18.0.1
time="2019-04-18T18:00:33Z" level=debug msg="Set CSRF cookie and redirecting to google login" SourceIP=172.18.0.1
time="2019-04-18T18:00:33Z" level=debug msg="Handling request" Headers="map[Referer:[https://accounts.youtube.com/accounts/SetSID] X-Forwarded-Host:[auth.example.com] Cache-Control:[max-age=0] Dnt:[1] Upgrade-Insecure-Requests:[1] X-Forwarded-For:[172.18.0.1] X-Forwarded-Proto:[https] User-Agent:[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36] Accept-Language:[en-US,en;q=0.9] X-Forwarded-Port:[443] Accept:[text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3] Cookie:[_forward_auth_csrf=32dede879133190b879991a92255f2f1] X-Forwarded-Server:[traefik.example.com] X-Real-Ip:[172.18.0.1] Accept-Encoding:[gzip, deflate, br]]" SourceIP=172.18.0.1
time="2019-04-18T18:00:33Z" level=debug msg="Set CSRF cookie and redirecting to google login" SourceIP=172.18.0.1
time="2019-04-18T18:00:33Z" level=debug msg="Handling request" Headers="map[X-Real-Ip:[172.18.0.1] Referer:[https://accounts.youtube.com/accounts/SetSID] X-Forwarded-For:[172.18.0.1] Dnt:[1] X-Forwarded-Host:[auth.example.com] X-Forwarded-Port:[443] X-Forwarded-Server:[traefik.example.com] Accept-Encoding:[gzip, deflate, br] Cache-Control:[max-age=0] X-Forwarded-Proto:[https] Accept-Language:[en-US,en;q=0.9] Cookie:[_forward_auth_csrf=c0216cec4d2a796b200e9f31858005ae] Upgrade-Insecure-Requests:[1] User-Agent:[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36] Accept:[text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3]]" SourceIP=172.18.0.1
time="2019-04-18T18:00:33Z" level=debug msg="Set CSRF cookie and redirecting to google login" SourceIP=172.18.0.1
```

**Comment by shbatm** [comment]
I just saw #41 and it looks like it might be related?

**Comment by thomseddon** [comment]
Hmm, I can't see an obvious problem with your config - does it work without the auth host?

As this has cropped up a few times, I may need to add more debug logging for a rejected request to help drill down into the cause.

**Comment by shbatm** [comment]
Yes, it worked fine without the auth-host--until I restarted my server.  I couldn't connect to anything that used the `traefik-forward-auth` provider until I updated the docker-compose file to use `http://traefik-forward-auth:4181` instead of `auth.example.com` which got things working again -- tried auth-host again after this change but had the same result.

**Comment by jnanthony14** [comment]
I was having a similar issue. I only had the redirect loop with https, http worked fine. I think my mistake was trying to use `https://traefik-forward-auth:4181` instead of `http://traefik-forward-auth:4181` on the https entrypoint.

Here are my final working configs. 

traefik.toml

```
debug = true

logLevel = "debug"
defaultEntryPoints = ["http","https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
    address = ":443"
  [entryPoints.https.auth.forward]
    address = "http://traefik-forward-auth:4181"
    authResponseHeaders = ["X-Forwarded-User"]
  [entryPoints.https.tls]


[retry]

[api]

[Docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "test.com"
  watch = true
  exposedByDefault = false
```

docker-compose.yml 

```
---
version: '3'

services:
      
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    networks:
      - traefik
    ports:
      - "80:80"
      - "443:443"
      - "8181:8080"
    environment: 
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/homelabos/traefik/traefik.toml:/traefik.toml
      - /var/homelabos/traefik/acme.json:/acme.json
 
  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - SECRET=${SECRET}
      - COOKIE_SECURE=false
      - DOMAIN=${DOMAIN}
      - AUTH_HOST=auth.${DOMAIN}
      - COOKIE_DOMAINS=${DOMAIN}
      - LOG_LEVEL=debug
      - WHITELIST=${WHITELIST}
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=homelabos_traefik"
      - "traefik.port=4181"
      - "traefik.backend=traefik-forward-auth"
      - "traefik.http.frontend.rule=Host:auth.${DOMAIN}"
      - "traefik.https.frontend.rule=Host:auth.${DOMAIN}"
      
 
networks:
  traefik:
    driver: bridge
  traefik_network:
    external:
      name: homelabos_traefik
```

**Comment by shbatm** [comment]
I confirmed that using forward auth/auth host on entryPoints works:

```toml
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
    address = ":443"
  [entryPoints.https.auth.forward]
    address = "http://traefik-forward-auth:4181"
    authResponseHeaders = ["X-Forwarded-User"]
  [entryPoints.https.tls]
```

But using forward auth / auth host on a host-by-host basis (e.g. the following docker labels, but no auth.forward in the entryPoints) does not--I get the redirect loop.  I can't figure out what's going on with it.

```yaml
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.${DOMAINNAME}"
      - "traefik.port=8080"
      - "traefik.docker.network=vlan50"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.auth.forward.address=http://oauth:4181"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User"
```
