### ISSUE TITLE
Support for traefik 2.0? 

### ISSUE THREAD

**Issue by dalanmiller** [thomseddon/traefik-forward-auth#45]
Hi there! 

Curious if you plan to support Traefik 2.0? I had everything working with Traefik 1.7 but now when I get redirected to Google, I'm seeing that the destination host name is being passed instead of the host name of the `traefik-forward-auth` container. Any thoughts on why this might be? 

e.g. I have `container1` at `c1.sub.domain.com` which requires auth via `auth.sub.domain.com`, when I'm redirected to google, I'm seeing:

```
The redirect URI in the request, https://c1.sub.domain.com/_oauth, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs
```

Where I believe before it was receiving `auth.sub.domain.com`? Ideas?

**Comment by thomseddon** [comment]
Yes! We'd definitely want to support 2.0, it's still alpha though isn't?

Perhaps they've changed the headers.

I'll have a look, but it probably won't be a priority until it hits beta?

**Comment by dalanmiller** [comment]
Yup still alpha. 

It appears though that the ForwardAuth middleware was just copypasta'd over.  

https://github.com/containous/traefik/blob/v2.0/pkg/middlewares/auth/forward.go

And then it appears that all headers are forwarded by default now from the auth responder. 

https://github.com/containous/traefik/commit/3d7633f4a6639a9218a40916290f8ae56add04e3#diff-5b170f890426c7bcf124e6c2dd6570c9

**Comment by dalanmiller** [comment]
An update that with the following label set, the ForwardAuth will work but only in overlay mode (where I have to add every host + path to the Google Console). Auth Host mode seems to no longer work.

Any advice on how I can see what is being passed to the `traefik-forward-auth` container?

**Comment by thomseddon** [comment]
If you enable debug logging you will see all the headers being passed, it would be interesting to see what's different

**Comment by dalanmiller** [comment]
Raw debug logs below from `traefik-forward-auth` and `traefik:v2.0`:

```
traefik-forward-auth    | time="2019-06-11T12:12:31Z" level=debug msg="Starting with options: {\"LogLevel\":\"debug\",\"LogFormat\":\"text\",\"AuthHost\":\"auth.sub.domain.com\",\"CookieDomains\":[{\"Domain\":\"sub.domain.com\",\"DomainLen\":20,\"SubDomain\":\".sub.domain.com\",\"SubDomainLen\":21}],\"InsecureCookie\":true,\"CookieName\":\"_forward_auth\",\"CSRFCookieName\":\"_forward_auth_csrf\",\"DefaultAction\":\"auth\",\"Domains\":null,\"LifetimeString\":43200,\"Path\":\"/_oauth\",\"Whitelist\":[\"me@email.com\",\"other@email.com\"],\"Providers\":{\"Google\":{\"ClientId\":\"<omitted_ID>.apps.googleusercontent.com\",\"Scope\":\"https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email\",\"Prompt\":\"\",\"LoginURL\":{\"Scheme\":\"https\",\"Opaque\":\"\",\"User\":null,\"Host\":\"accounts.google.com\",\"Path\":\"/o/oauth2/auth\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"TokenURL\":{\"Scheme\":\"https\",\"Opaque\":\"\",\"User\":null,\"Host\":\"www.googleapis.com\",\"Path\":\"/oauth2/v3/token\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"UserURL\":{\"Scheme\":\"https\",\"Opaque\":\"\",\"User\":null,\"Host\":\"www.googleapis.com\",\"Path\":\"/oauth2/v2/userinfo\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"}}},\"Rules\":{},\"Lifetime\":43200000000000,\"CookieDomainsLegacy\":null,\"CookieSecureLegacy\":\"\",\"DomainsLegacy\":null,\"ClientIdLegacy\":\"<omitted_ID>.apps.googleusercontent.com\",\"PromptLegacy\":\"\"}"
traefik-forward-auth    | time="2019-06-11T12:12:31Z" level=info msg="Listening on :4181"
traefik-forward-auth    | time="2019-06-11T12:12:51Z" level=debug msg="Authenticating request" headers="map[Accept:[text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8] Accept-Encoding:[gzip, deflate, br] Accept-Language:[en-US,en;q=0.5] Cookie:[_forward_auth_csrf=c814ce3749ab60d0d4f66d95ae9cdf27] Dnt:[1] Upgrade-Insecure-Requests:[1] User-Agent:[Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0] X-Forwarded-For:[192.168.1.1] X-Forwarded-Host:[synology.sub.domain.com] X-Forwarded-Method:[GET] X-Forwarded-Port:[443] X-Forwarded-Proto:[https] X-Forwarded-Server:[8bd8f24fbe93] X-Forwarded-Uri:[/] X-Real-Ip:[192.168.1.1]]" rule=default source_ip=192.168.1.1
traefik                 | 192.168.1.1 - - [11/Jun/2019:12:12:45 +0000] "GET /_oauth?state=c814ce3749ab60d0d4f66d95ae9cdf27:https://synology.sub.domain.com/&code=4/ZgF_eoY4qYEckmNyZN9uzV-XRtZM5omfbsUVZLB8cW5S3CD_hEVW6-CkwQJmj-QScYCJqC9Rl2Vj9NQsJCT9w8g&scope=email+profile+https://www.googleapis.com/auth/userinfo.email+https://www.googleapis.com/auth/userinfo.profile HTTP/2.0" 404 19 "-" "Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0" 1 - - 0ms
traefik                 | time="2019-06-11T12:12:51Z" level=debug msg="Remote error http://traefik-forward-auth:4181. StatusCode: 307" middlewareType=ForwardedAuthType middlewareName=file.forward-auth
traefik-forward-auth    | time="2019-06-11T12:12:51Z" level=debug msg="Set CSRF cookie and redirecting to google login" source_ip=192.168.1.1
traefik                 | 192.168.1.1 - - [11/Jun/2019:12:12:51 +0000] "GET / HTTP/2.0" 307 467 "-" "Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0" 2 "file.synology" - 2ms
traefik                 | 2019/06/11 12:12:51 server.go:3012: http: TLS handshake error from 192.168.1.1:49956: EOF
```

One thing that's interesting is that 192.168.1.1 is my router? It would be the last hop to the Docker host from my client laptop but seems weird to use that in a couple places.

**Comment by thomseddon** [comment]
Hmm, all seems to look OK...

This will require a bit more investigating into the source to check what's going on.

**Comment by dalanmiller** [comment]
https://docs.traefik.io/v2.0/middlewares/forwardauth/

Here's all the new labels:

```
# Forward authentication to authserver.com
labels:
- "traefik.http.middlewares.test-auth.ForwardAuth.Address=https://authserver.com/auth"
- "traefik.http.middlewares.test-auth.ForwardAuth.AuthResponseHeaders=X-Auth-User, X-Secret"
- "traefik.http.middlewares.test-auth.ForwardAuth.TLS.CA=path/to/local.crt"
- "traefik.http.middlewares.test-auth.ForwardAuth.TLS.CAOptional=true"
- "traefik.http.middlewares.test-auth.ForwardAuth.TLS.Cert=path/to/foo.cert"
- "traefik.http.middlewares.test-auth.ForwardAuth.TLS.InsecureSkipVerify=true"
- "traefik.http.middlewares.test-auth.ForwardAuth.TLS.Key=path/to/foo.key"
- "traefik.http.middlewares.test-auth.ForwardAuth.TrustForwardHeader=true"
```

**Comment by dalanmiller** [comment]
Hey @thomseddon I've progressed my experimentation a bit more at containous/traefik#4972 but I put together what I'm observing in this swimlanes diagram:

https://swimlanes.io/d/jstlkzV_T

**Comment by dalanmiller** [comment]
Investigating a bit further it appears that I'm still endlessly being redirected to Google. Reading through `server.go` it appears that the `AuthCallbackHandler` is never firing and I'm constantly getting the `authRedirect` handler. 

Here's my redirect request after authentication on Google as observed from my browser:
```
https://auth.sub.domain.com/_oauth?state=d318104fc145cd56cc52de772c19161f%3Ahttps%3A%2F%2Fauth.sub.domain.com&code=4%2FjwE18TTHV0kXMvIbIfgWJBpKXM-th0o9iRlDtI6eFIQ6doLgEa5CsdigOOyBDCg2WaYzPujiKytoJep6fTbnKGo&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+openid&authuser=0&session_state=f73ca64759d375e6de9d887637598ad9ed5f56c3..5ead&prompt=consent
```

`traefik-forward-auth` just responds with a 307 and the circle continues 😵

**Comment by robertbaker** [comment]
Traefik 2 is beta now, any updates on this?

**Comment by robertbaker** [comment]
I was able to test with traefik 2. Getting the config right is a PITA, but now I'm getting not_authorized or an endless redirect loop on the google login page when I go icognito.

**Comment by cry** [comment]
This is related to #11, traefik-forward-auth never calls `AuthCallbackHandler` since `X-Forwarded-URI` is never passed, as seen here:

```
traefik-forward-auth    | time="2019-08-23T06:36:20Z" level=debug msg="Authenticating request" headers="map[Accept:[text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8] Accept-Encoding:[gzip, deflate, br] Accept-Language:[en-US,en;q=0.5] Cookie:[_forward_auth_csrf=/; _forward_auth_csrf=/] Referer:[/] Te:[trailers] Upgrade-Insecure-Requests:[1] User-Agent:[Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:69.0) Gecko/20100101 Firefox/69.0] X-Forwarded-For:[/] X-Forwarded-Host:[/] X-Forwarded-Port:[443] X-Forwarded-Proto:[https] X-Forwarded-Server:[ae93b2507fa7] X-Real-Ip:[/]]" rule=default source_ip=/
traefik-forward-auth    | time="2019-08-23T06:36:20Z" level=debug msg="Set CSRF cookie and redirecting to google login" source_ip=/
traefik-forward-auth    | time="2019-08-23T06:36:20Z" level=debug msg=Done source_ip=1.129.111.181
```

If forwarded auth isn't enabled on all endpoints, traefik never adds the header with the example configuration since it doesn't treat it as a forwarded auth host. Setting the auth container as forwarded auth forces traefik to add the header and everything works correctly. To test this, I added auth through labels and it seemed work ok:

```yaml
  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth
    container_name: traefik-forward-auth
    volumes:
      - ./config/traefik/forward.ini:/forward.ini
    environment:
      - CONFIG=/forward.ini
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181
      - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
      - traefik.port=4181
      - traefik.backend=traefik-forward-auth
      - traefik.frontend.rule=Host:auth
  whoami:
    image: emilevauge/whoami
    container_name: whoami
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181
      - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
      - traefik.frontend.rule=Host:whoami
```

**Comment by cry** [comment]
This is related to #11, traefik-forward-auth never calls `AuthCallbackHandler` since `X-Forwarded-URI` is never passed, as seen here:

```
traefik-forward-auth    | time="2019-08-23T06:36:20Z" level=debug msg="Authenticating request" headers="map[Accept:[text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8] Accept-Encoding:[gzip, deflate, br] Accept-Language:[en-US,en;q=0.5] Cookie:[_forward_auth_csrf=/; _forward_auth_csrf=/] Referer:[/] Te:[trailers] Upgrade-Insecure-Requests:[1] User-Agent:[Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:69.0) Gecko/20100101 Firefox/69.0] X-Forwarded-For:[/] X-Forwarded-Host:[/] X-Forwarded-Port:[443] X-Forwarded-Proto:[https] X-Forwarded-Server:[ae93b2507fa7] X-Real-Ip:[/]]" rule=default source_ip=/
traefik-forward-auth    | time="2019-08-23T06:36:20Z" level=debug msg="Set CSRF cookie and redirecting to google login" source_ip=/
traefik-forward-auth    | time="2019-08-23T06:36:20Z" level=debug msg=Done source_ip=/
```

If forwarded auth isn't enabled on all endpoints, traefik never adds the header with the example configuration since it doesn't treat it as a forwarded auth host. Setting the auth container as forwarded auth forces traefik to add the header and everything works correctly. To test this, I added auth through labels and it seemed work ok:

```yaml
  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth
    container_name: traefik-forward-auth
    volumes:
      - ./config/traefik/forward.ini:/forward.ini
    environment:
      - CONFIG=/forward.ini
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181
      - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
      - traefik.port=4181
      - traefik.backend=traefik-forward-auth
      - traefik.frontend.rule=Host:auth
  whoami:
    image: emilevauge/whoami
    container_name: whoami
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181
      - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
      - traefik.frontend.rule=Host:whoami
```

**Comment by robertbaker** [comment]
That worked for me, I had to go to chrome dev tools and clear the application data (or just clear browser cookies for the domain, etc).

Here is my traefik 2.0 config

```
traefik:
    image: "traefik:v2.0"
    container_name: traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${APPDATA_ROOT}/traefik:/etc/traefik"
    ports:
      - "443:443"
    environment:
      CLOUDFLARE_EMAIL: "${CLOUDFLARE_EMAIL}"
      CLOUDFLARE_API_KEY: "${CLOUDFLARE_API_KEY}"
    command:
      - "--global.sendanonymoususage=false"
      - "--providers.file.directory=/etc/traefik"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.cfdns.acme.dnschallenge=true"
      - "--certificatesresolvers.cfdns.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cfdns.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.cfdns.acme.storage=/etc/traefik/acme.json"
  forwardauth:
    image: "thomseddon/traefik-forward-auth"
    container_name: forwardauth
    environment: 
      CLIENT_ID: "${OAUTH_CLIENT_ID}"
      CLIENT_SECRET: "${OAUTH_CLIENT_SECRET}"
      SECRET: "${OAUTH_SECRET}"
      COOKIE_DOMAIN: "${TLD}"
      LIFETIME: "2592000"
      AUTH_HOST: "forwardauth.${TLD}"
      WHITELIST: "${WHITELIST}"
      PUID: "${UID}"
      PGID: "${UID}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oauth.rule=Host(`forwardauth.${TLD}`)"
      - "traefik.http.routers.oauth.entrypoints=websecure"
      - "traefik.http.routers.oauth.tls.options=securetls@file"
      - "traefik.http.routers.oauth.tls.certresolver=cfdns"
      - "traefik.http.routers.oauth.middlewares=secureHeaders@file,googleAuth@file"
      - "traefik.http.services.oauth.loadbalancer.server.port=4181"
```
dynamic_conf.yml

```
tls:
  options:
    securetls:
      sniStrict: true
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_CHACHA20_POLY1305_SHA256
        - TLS_AES_256_GCM_SHA384 
        - TLS_AES_128_GCM_SHA256
        -  TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_RSA_WITH_AES_256_GCM_SHA384
http:
  middlewares:
    googleAuth:
      forwardAuth:
        address: "http://oauth:4181"
        trustForwardHeader: true
        authResponseHeaders:
          - "X-Forwarded-User"
    secureHeaders:
      headers:
        FrameDeny: true
        SSLRedirect: true
        stsSeconds: 315360000
        stsPreload: true
        stsIncludeSubdomains: true
        contentTypeNosniff: true
        browserXssFilter: true
        X-Custom-Request-Header: "X-Robots-Tag=noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"

  portainer:
    image: "portainer/portainer"
    container_name: portainer
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${TLD}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls.options=securetls@file"
      - "traefik.http.routers.portainer.tls.certresolver=cfdns"
      - "traefik.http.routers.portainer.middlewares=secureHeaders@file,googleAuth@file"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${APPDATA_ROOT}/portainer:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      PUID: "${UID}"
      PGID: "${UID}"
```
