### ISSUE TITLE
OIDC Support

### ISSUE THREAD

**Issue by thomseddon** [thomseddon/traefik-forward-auth#47]
- https://github.com/funkypenguin/traefik-forward-auth
- https://github.com/noelcatt/traefik-forward-auth

**Comment by thebetterjort** [comment]
time="2019-06-18T22:37:52Z" level=fatal msg="client-id, client-secret, secret and oidc-issuer must all be set"  

```
[](traefik-forward-auth:
    image: funkypenguin/traefik-forward-auth
    env_file: ./assets/traefik.env
    environment:
      - CLIENT_ID=Forward-auth
      - CLIENT_SECRET=9ca3051f-954b-4858-b007-5291ad192097
      - OIDC-ISSUER=https://keycloak.127.0.0.1.xip.io/auth/realms/master
      - SECRET=eladdale
      - AUTH_HOST=auth.127.0.0.1xip.io
      - COOKIE_DOMAINS=127.0.0.1.xip.io  
    networks:
      - web
      - internal
    labels:
```
      - traefik.port=4181
      - traefik.frontend.rule=Host:auth.127.0.0.1.xip.io
      - traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181
      - traefik.frontend.auth.forward.trustForwardHeader=true
)
