### ISSUE TITLE
[auth-host] Almost there, but not quite yet.

### ISSUE THREAD

**Issue by Webunity** [thomseddon/traefik-forward-auth#59]
What happens is this:
- When i browse to **http://consul.mydomain.io/** i am succesfully redirected to SSL using the redirector service set at consul (see below config), so i am redirected to **https://consul.mydomain.io/**.
- This then knows that i am not authenticated so it redirects me to the authentication host (Keycloak in my example, with redirect URL **https://auth.mydomain.io/_oauth**)
- I enter my credentials and i am redirected to **https://auth.mydomain.io/_oauth**, but this doesn't exist (404)

If i remove the SSL redirect on consul (so that it is hosted on HTTP instead) the redirect-url is automatically set to **http://auth.mydomain.io/_oauth** (e.g. non-ssl)

What am i missing to get the traefik-forward-auth working fully on SSL?

See below my config:

**Consul:**
```
  consul-leader:
    image: consul
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    networks:
      - internal
      - swarm_traefik
    volumes:
      - consul-leader:/consul/data
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
      labels:
        - traefik.enable=true
        - traefik.frontend.rule=Host:consul.${DOCKER_TRAEFIK_DOMAIN?Variable DOCKER_TRAEFIK_DOMAIN not set}
        - traefik.port=8500
        - traefik.tags=${DOCKER_TRAEFIK_TAG:-traefik-exposed}
        - traefik.docker.network=swarm_traefik
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
        # Security
        - traefik.frontend.headers.SSLRedirect=true
        - traefik.frontend.headers.forceSTSHeader=true
        - traefik.frontend.headers.STSSeconds=315360000
        - traefik.frontend.headers.STSIncludeSubdomains=true
        - traefik.frontend.headers.STSPreload=true
        - traefik.frontend.headers.browserXSSFilter=true
        - traefik.frontend.headers.contentTypeNosniff=true
        - traefik.frontend.headers.frameDeny=true
        # Traefik forward auth
        - traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181
        - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
        - traefik.frontend.auth.forward.trustForwardHeader=true
    command: agent -server -client=0.0.0.0 -bootstrap -ui
```

**Traefik:**
```
  traefik:
    image: traefik:v1.7
    depends_on:
      - consul-leader
    networks:
      - swarm_traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
      replicas: ${DOCKER_CORE_TRAEFIK_REPLICAS:-3}
      placement:
        constraints:
          - node.role == manager
        preferences:
          - spread: node.id
      labels:
        - traefik.enable=true
        - traefik.frontend.rule=Host:traefik.${DOCKER_TRAEFIK_DOMAIN?Variable DOCKER_TRAEFIK_DOMAIN not set}
        - traefik.port=8080
        - traefik.tags=${DOCKER_TRAEFIK_TAG:-traefik-exposed}
        - traefik.docker.network=swarm_traefik
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
        # Security
        - traefik.frontend.headers.SSLRedirect=true
        - traefik.frontend.headers.forceSTSHeader=true
        - traefik.frontend.headers.STSSeconds=315360000
        - traefik.frontend.headers.STSIncludeSubdomains=true
        - traefik.frontend.headers.STSPreload=true
        - traefik.frontend.headers.browserXSSFilter=true
        - traefik.frontend.headers.contentTypeNosniff=true
        - traefik.frontend.headers.frameDeny=true
        - traefik.frontend.auth.basic.users=${DOCKER_CORE_TRAEFIK_USERNAME?Variable DOCKER_CORE_TRAEFIK_USERNAME not set}:${DOCKER_CORE_TRAEFIK_PASSWORD_HASHED?Variable DOCKER_CORE_TRAEFIK_PASSWORD_HASHED not set}
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    command: >
      --docker
      --docker.swarmmode
      --docker.watch
      --docker.exposedbydefault=false
      --constraints=tag==${DOCKER_TRAEFIK_TAG:-traefik-exposed}
      --entrypoints='Name:http Address::80'
      --entrypoints='Name:https Address::443 TLS'
      --consul
      --consul.endpoint='consul-leader:8500'
      --acme
      --acme.email=${DOCKER_CORE_TRAEFIK_EMAIL?Variable DOCKER_swarm_traefik_EMAIL not set}
      --acme.storage=traefik/acme/account
      --acme.entryPoint=https
      --acme.httpChallenge.entryPoint=http
      --acme.onhostrule=true
      --acme.acmelogging=true
      --logLevel=INFO
      --accessLog
      --api
```

**Traefik-forward-auth:**
```
  traefik-forward-auth:
    image: funkypenguin/traefik-forward-auth
    environment:
      - CLIENT_ID=${DOCKER_CORE_TRAEFIK_AUTH_CLIENT_ID?Variable DOCKER_CORE_TRAEFIK_AUTH_CLIENT_ID not set}
      - CLIENT_SECRET=${DOCKER_CORE_TRAEFIK_AUTH_CLIENT_SECRET?Variable DOCKER_CORE_TRAEFIK_AUTH_CLIENT_SECRET not set}
      - OIDC_ISSUER=https://keycloak.${DOCKER_TRAEFIK_DOMAIN?Variable DOCKER_TRAEFIK_DOMAIN not set}/auth/realms/master
      - SECRET=${DOCKER_CORE_TRAEFIK_AUTH_SECRET?Variable DOCKER_CORE_TRAEFIK_AUTH_SECRET not set}
      - AUTH_HOST=auth.${DOCKER_TRAEFIK_DOMAIN?Variable DOCKER_TRAEFIK_DOMAIN not set}
      - COOKIE_DOMAINS=${DOCKER_TRAEFIK_DOMAIN?Variable DOCKER_TRAEFIK_DOMAIN not set}
    networks:
      - swarm_traefik
    deploy:
      labels:
        - traefik.enable=true
        - traefik.port=4181
        - traefik.frontend.rule=Host:auth.${DOCKER_TRAEFIK_DOMAIN?Variable DOCKER_TRAEFIK_DOMAIN not set}
        - traefik.tags=${DOCKER_TRAEFIK_TAG:-traefik-exposed}
        - traefik.docker.network=swarm_traefik
        - traefik.backend=traefik-forward-auth
```

p.s. i know i am running 'funkypenguin's version, but i hope you can give me a v2 thomseddon example after you've implemented custom oauth providers (e.g. keycloak)

**Comment by thomseddon** [comment]
it looks like you're using traefik acme to generate your SSL certs, as such your `traefik.frontend.rule` label on the `traefik-forward-auth` container should prompt traefik to generate the certificates.

If you could increase your traefik logging it should show you what certificates it's generating

**Comment by Webunity** [comment]
@thomseddon what loglevel do you want me to use?

p.s. if i host consul on http, like this:
```
  consul-leader:
    image: consul
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    networks:
      - internal
      - swarm_traefik
    volumes:
      - consul-leader:/consul/data
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
      labels:
        - traefik.enable=true
        - traefik.frontend.rule=Host:consul.${DOCKER_TRAEFIK_DOMAIN?Variable DOCKER_TRAEFIK_DOMAIN not set}
        - traefik.port=8500
        - traefik.tags=${DOCKER_TRAEFIK_TAG:-traefik-exposed}
        - traefik.docker.network=swarm_traefik
        # Traefik forward auth
        - traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181
        - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
        - traefik.frontend.auth.forward.trustForwardHeader=true
```

With the following traefik-forward-auth config:
```
  traefik-forward-auth:
    image: funkypenguin/traefik-forward-auth
    environment:
      - CLIENT_ID=${DOCKER_CORE_TRAEFIK_AUTH_CLIENT_ID?Variable DOCKER_CORE_TRAEFIK_AUTH_CLIENT_ID not set}
      - CLIENT_SECRET=${DOCKER_CORE_TRAEFIK_AUTH_CLIENT_SECRET?Variable DOCKER_CORE_TRAEFIK_AUTH_CLIENT_SECRET not set}
      - OIDC_ISSUER=https://keycloak.${DOCKER_TRAEFIK_DOMAIN?Variable DOCKER_TRAEFIK_DOMAIN not set}/auth/realms/master
      - SECRET=${DOCKER_CORE_TRAEFIK_AUTH_SECRET?Variable DOCKER_CORE_TRAEFIK_AUTH_SECRET not set}
      - AUTH_HOST=auth.${DOCKER_TRAEFIK_DOMAIN?Variable DOCKER_TRAEFIK_DOMAIN not set}
      - COOKIE_DOMAINS=${DOCKER_TRAEFIK_DOMAIN?Variable DOCKER_TRAEFIK_DOMAIN not set}
      - COOKIE_SECURE=false
    networks:
      - swarm_traefik
    deploy:
      labels:
        - traefik.enable=true
        - traefik.port=4181
        - traefik.frontend.rule=Host:auth.${DOCKER_TRAEFIK_DOMAIN?Variable DOCKER_TRAEFIK_DOMAIN not set}
        - traefik.tags=${DOCKER_TRAEFIK_TAG:-traefik-exposed}
        - traefik.docker.network=swarm_traefik
        - traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181
        - traefik.frontend.auth.forward.trustForwardHeader=true
```

It works fine, i get redirected to KeyCloak (running on HTTPS, hence the cookie_secure=false flag) but once authenticated i am redirected to consul as authenticated user on http.
