### ISSUE TITLE
AUTH-HOST not working

### ISSUE THREAD

**Issue by Webunity** [thomseddon/traefik-forward-auth#65]
For some reason, Google keeps telling me:
`The redirect URI in the request, ..., does not match the ones authorized for the OAuth client`

This is my Forward Auth compose:
```
  core-traefik-forward-auth:
    container_name: core-traefik-forward-auth
    depends_on:
      - core-traefik
    image: thomseddon/traefik-forward-auth
    restart: unless-stopped
    environment:
      - PROVIDERS_GOOGLE_CLIENT_ID=...
      - PROVIDERS_GOOGLE_CLIENT_SECRET=...
      - SECRET=something-random
      - INSECURE_COOKIE=false
      - DOMAIN=docker.mydomain.ext
      - AUTH_HOST=auth.docker.mydomain.ext
      - WHITELIST=...@gmail.com
      - LIFETIME=1800
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - traefik
    labels:
      - traefik.docker.network=traefik
      - traefik.enable=true
      - traefik.frontend.rule=Host:auth.docker.mydomain.ext
      - traefik.port=4181
      - traefik.tags=traefik-exposed
      - traefik.backend=core-traefik-forward-auth
```
And this is one of my services' compose section:
```
  network-cupsd:
    container_name: network-cupsd
    image: olbat/cupsd
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=999
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/dbus:/var/run/dbus
      - /dev/bus/usb:/dev/bus/usb
      - network-cupsd-config:/etc/cups
    labels:
      - traefik.docker.network=traefik
      - traefik.enable=true
      - traefik.frontend.rule=Host:cups.docker.mydomain.ext
      - traefik.port=631
      - traefik.tags=traefik-exposed
      - traefik.backend=network-cupsd
      - traefik.protocol=https
      - traefik.passHostHeader=true
      # Security
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.browserXSSFilter=true
      - traefik.frontend.headers.contentTypeNosniff=true
      - traefik.frontend.headers.frameDeny=true
      # Traefik forward auth
      - traefik.frontend.auth.forward.address=http://core-traefik-forward-auth:4181
      - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
      - traefik.frontend.auth.forward.trustForwardHeader=true
      # Traefik service that listens on HTTPS
      - traefik.webservice.frontend.entryPoints=https
```

What am i doing wrong?

**Comment by thomseddon** [comment]
Assuming "..." is the correct host then this should just be due to missing configuration in the Google console, please can you confirm that the exact uri listed has been added to the list of authorised redirect uris (protocol host and path all need to be exactly correct)

**Comment by rubasace** [comment]
I had the exact same issue:

you are not specifying the COOKIE_DOMAIN envar. DOMAIN is for specifying the authorized domains, auth host mode needs the auth host to be a subdomain of the cookie domain.

**Comment by Webunity** [comment]
Hi @thomseddon still have thesame issue; here is my config for Traefik v2 (thought that would solve the issue):

On the Traefik container i have setup the midleware for SSO:
```
      # Middleware: SSO middleware
      - "traefik.http.middlewares.sso.forwardauth.address=http://core-traefik-fa:4181"
      - "traefik.http.middlewares.sso.forwardauth.authResponseHeaders=X-Forwarded-User"
```

And i've setup the Traefik Forward auth container as this:
```
  core-traefik-fa:
    container_name: core-traefik-fa
    depends_on:
      - core-traefik
    image: thomseddon/traefik-forward-auth:2
    restart: unless-stopped
    environment:
      - PROVIDERS_GOOGLE_CLIENT_ID=xxx
      - PROVIDERS_GOOGLE_CLIENT_SECRET=xxx
      - SECRET=something-random
      - COOKIE_DOMAIN=at.domain.info
      - AUTH_HOST=auth.at.domain.info
      - WHITELIST=myname@gmail.com
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - traefik
    labels:
      # Enable traefik
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      # Router: Traefik Forward Auth-specific
      - "traefik.http.routers.core-traefik-fa.rule=Host(`auth.at.domain.info`)"
      - "traefik.http.routers.core-traefik-fa.entrypoints=websecure"
      - "traefik.http.routers.core-traefik-fa.tls=true"
      - "traefik.http.routers.core-traefik-fa.tls.certresolver=leresolver"
      - "traefik.http.services.core-traefik-fa.loadbalancer.server.port=4181"
```

Whenever i do this, i get the "This page isn’t working... accounts.google.com redirected you too many times." error.
