### ISSUE TITLE
Multiple whitelist address

### ISSUE THREAD

**Issue by HedgeShot** [thomseddon/traefik-forward-auth#80]
Hi,

I am getting `Invalid email` when I am setting more than one `whitelist` email address. According to the readme, it should be working fine. Here is my docker-compose file related to forward-auth.

```
forward-oauth:
    image: thomseddon/traefik-forward-auth
    container_name: "forward-oauth"
    restart: unless-stopped
    environment:
      - CLIENT_ID=${GOOGCLIENTID}
      - CLIENT_SECRET=${GOOGCLIENTSEC}
      - SECRET=${COOKIESECRET}
      - INSECURE_COOKIE=false
      - WHITELIST=address1@gmail.com
      - WHITELIST=address2@gmail.com
      - COOKIE_DOMAIN=domain1.com
      - COOKIE_DOMAIN=domain2.com
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=forward-oauth"
      - "traefik.port=4181"
      - "traefik.docker.network=traefik_proxy"
```
