### ISSUE TITLE
/_oauth overlay in Kubernetes

### ISSUE THREAD

**Issue by dannyyy** [thomseddon/traefik-forward-auth#83]
All the examples here and everywhere else are targeting Docker-Compose and Docker-Swarm. 

This leads to several questions:
- Is traefik-forward-auth even compatible with Kubernetes?
- Is traefik-forward-auth compatible wirh Traefik 2.0/2.1?

If the first two questions could be answered with a clear yes, then and only then the following questions make sense:
- I wanted to start in it's simplest version without `auth-host`. But how does the overlay of `/_oauth` really works? Following all the guides I don't see any reason why this path should be hooked up automatically to handle auth requests through traefik-forward-auth. The redirect of the Google is correctly to https://app.mydomain.com/_oauth but no-one is listening there.
- In the more advanced case of `auth-host` I get always and in any combination of `cookie-domain` a result of `too many redirects`. The auth provider and traefik-forwared-auth are redirecting forth and back until the browser stops. Also here, Google redirects correctly to https://auth.mydomain.com/_oauth. But the same here the container is not able to handle this and redirects back and forth to Google.

Calling `/_oauth` returns a `404` of course. There is actually nothing...

For the first example I used the following configuration:
**Orchestrator:** Kubernetes
**Ingress:** Traefik 2.1 with IngressRoute CRD (the only recommended ways as Traefik mentioned)

_For the traefik_forward_auth part_
```
apiVersion: v1
kind: Service
metadata:
  name: traefik-auth

spec:
  ports:
    - protocol: TCP
      name: web
      port: 4181
  selector:
    app: traefik-auth

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-auth
  labels:
    app: traefik-auth

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-auth
  template:
    metadata:
      labels:
        app: traefik-auth
    spec:
      containers:
        - name: traefik-auth
          image: thomseddon/traefik-forward-auth:2.0.1
          args:
            - --insecure-cookie
            - --log-level=debug
            - --secret=randomsecret
            - --providers.google.client-id=googleclientid
            - --providers.google.client-secret=googlesecret
            - --providers.google.prompt=select_account
          ports:
            - name: web
              containerPort: 4181

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth
spec:
  forwardAuth:
    address: http://traefik-auth:4181
    trustForwardHeader: true
    authResponseHeaders:
      - X-Forwarded-User
```

_For the actual workload part_
```
apiVersion: v1
kind: Service
metadata:
  name: whoami

spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
  selector:
    app: whoami

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
  labels:
    app: whoami

spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: containous/whoami
          ports:
            - name: web
              containerPort: 80

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-secure
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`whoami.mydomain.com`) && PathPrefix(`/test`)
    kind: Rule
    services:
      - name: whoami
        port: 80
    middlewares:
      - name: auth
  tls:
    certResolver: default
```
