### ISSUE TITLE
Fatal HTTP error 502, probably due to dependency on Keycloak service

### ISSUE THREAD

**Issue by croneter** [thomseddon/traefik-forward-auth#84]
traefik-forward-auth seems to abort start-up too quickly if Keycloak is not yet ready. All the log is saying is this:
```
time="2020-02-12T06:09:28Z" level=fatal msg="502 Bad Gateway: Bad Gateway"
```
I need to manually restart the traefik-forward-auth container for everything to work with `docker-compose restart forward-auth`. 

Any ideas?

Docker compose excerpt:
```
version: '3.7'

services:
  traefik:
    image: traefik:v2.1.4
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
      # See https://go-acme.github.io/lego/dns/duckdns/ and
      # https://github.com/go-acme/lego/issues/967
      # API request timeout
      - "DUCKDNS_HTTP_TIMEOUT=30"
      # Maximum waiting time for DNS propagation
      - "DUCKDNS_PROPAGATION_TIMEOUT=600"
      # Time between DNS propagation check
      - "DUCKDNS_POLLING_INTERVAL=16"
      # The TTL of the TXT record used for the DNS challenge
      - "DUCKDNS_TTL=600"
      # Link environment variable with secrets file
      - "DUCKDNS_TOKEN=${DUCKDNS_TOKEN}"
    volumes:
      # Safe SSL certificates by LetsEncrypt
      - "${CONFIG_DIR}/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command:
      # This is the "static traefik configuration"
      - "--log.level=INFO"  # Possible values: DEBUG, INFO, WARN, ERROR
      # Enable docker as provider for traefik. Containers won't automatically connect
      - "--providers.docker.exposedbydefault=false"
      - "--global.sendanonymoususage=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # letsencrypt SSL certificates ("acme")
      - "--certificatesresolvers.ssl.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.ssl.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.ssl.acme.dnschallenge.provider=duckdns"
    labels:
      # This is the "dynamic traefik configuration" (part of it)
      - "traefik.enable=true"
      # global redirect to https
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectScheme.scheme=https"
      # global wildcard certificates
      - "traefik.http.routers.wildcard-certs.entrypoints=websecure"
      - 'traefik.http.routers.wildcard-certs.tls.certresolver=ssl'
      - 'traefik.http.routers.wildcard-certs.tls.domains[0].main=${DOMAIN}'
      - 'traefik.http.routers.wildcard-certs.tls.domains[0].sans=*.${DOMAIN}'
      # Authentication done by our Keycloak container
      - "traefik.http.middlewares.auth.forwardauth.address=http://forward-auth:4181"
      - "traefik.http.middlewares.auth.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.auth.forwardauth.authResponseHeaders=X-Forwarded-User"
  keycloak_db:
    image: postgres:12.1-alpine
    container_name: keycloak_db
    volumes:
      - "${CONFIG_DIR}/keycloak_db:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_DB=keycloak"
      - "POSTGRES_USER=keycloak"
      - "POSTGRES_PASSWORD=password"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    labels:
      - "traefik.enable=false"
  keycloak:
    image: jboss/keycloak:latest
    container_name: keycloak
    secrets:
      - keycloak
    environment:
      - "DB_VENDOR=POSTGRES"
      - "DB_ADDR=keycloak_db"
      - "DB_PORT=5432"
      - "DB_DATABASE=keycloak"
      - "DB_USER=keycloak"
      - "DB_SCHEMA=public"
      - "DB_PASSWORD=password"
      - "KEYCLOAK_USER=${KEYCLOAK_ADMIN_USERNAME}"
      - "KEYCLOAK_PASSWORD_FILE=/run/secrets/keycloak"
      - "PROXY_ADDRESS_FORWARDING=true"
      - "KEYCLOAK_LOGLEVEL=INFO"  # Possible values: DEBUG, INFO, WARN, ERROR
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    depends_on:
      - keycloak_db
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.keycloak.entrypoints=websecure'
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.${DOMAIN}`)"
      - "traefik.http.routers.keycloak.tls=true"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
  forward-auth:
    image: thomseddon/traefik-forward-auth:2.1
    container_name: forward-auth
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
      - "LOG_LEVEL=TRACE"
      - "DEFAULT_PROVIDER=oidc"
      - "PROVIDERS_OIDC_CLIENT_ID=${KEYCLOAK_CLIENT_ID}"
      - "PROVIDERS_OIDC_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}"
      - "PROVIDERS_OIDC_ISSUER_URL=https://keycloak.${DOMAIN}/auth/realms/${KEYCLOAK_REALM}"
      - "SECRET=${COOKIE_SECRET}"
      - "COOKIE_DOMAIN=${DOMAIN}"
      - "AUTH_HOST=auth.${DOMAIN}"
    depends_on:
      - traefik
      - keycloak
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.forward-auth.entrypoints=websecure'
      - "traefik.http.routers.forward-auth.rule=Host(`auth.${DOMAIN}`)"
      - "traefik.http.routers.forward-auth.tls=true"
      - "traefik.http.routers.forward-auth.middlewares=auth"
      - "traefik.http.services.forward-auth.loadbalancer.server.port=4181"

secrets:
  keycloak:
    file: "./secrets/keycload_admin_pwd.txt"
```

**Comment by croneter** [comment]
Solved by adding the docker-compose label `restart: unless-stopped` or `restart: always`. So:
````
  forward-auth:
    image: thomseddon/traefik-forward-auth:2.1
    container_name: forward-auth
    restart: unless-stopped
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
      - "LOG_LEVEL=TRACE"
      - "DEFAULT_PROVIDER=oidc"
      - "PROVIDERS_OIDC_CLIENT_ID=${KEYCLOAK_CLIENT_ID}"
      - "PROVIDERS_OIDC_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}"
      - "PROVIDERS_OIDC_ISSUER_URL=https://keycloak.${DOMAIN}/auth/realms/${KEYCLOAK_REALM}"
      - "SECRET=${COOKIE_SECRET}"
      - "COOKIE_DOMAIN=${DOMAIN}"
      - "AUTH_HOST=auth.${DOMAIN}"
    depends_on:
      - traefik
      - keycloak
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.forward-auth.entrypoints=websecure'
      - "traefik.http.routers.forward-auth.rule=Host(`auth.${DOMAIN}`)"
      - "traefik.http.routers.forward-auth.tls=true"
      - "traefik.http.routers.forward-auth.middlewares=auth"
      - "traefik.http.services.forward-auth.loadbalancer.server.port=4181"
```
