### ISSUE TITLE
Email field in cookie is empty

### ISSUE THREAD

**Issue by Pixtriks** [thomseddon/traefik-forward-auth#85]
I am experiencing this issue (#60) as well. I am running in overlay mode and have one whitelisted e-mail address. Identity provider is GitLab. The e-mail field is empty causing a "Not Authorized" error.

Log file:
```
time="2020-02-17T15:22:03Z" level=debug msg="Starting with options: {\"LogLevel\":\"debug\",\"LogFormat\":\"text\",\"AuthHost\":\"\",\"CookieDomains\":[{\"Domain\":\"example.com\",\"DomainLen\":12,\"SubDomain\":\".example.com\",\"SubDomainLen\":13}],\"InsecureCookie\":false,\"CookieName\":\"_forward_auth\",\"CSRFCookieName\":\"_forward_auth_csrf\",\"DefaultAction\":\"auth\",\"DefaultProvider\":\"oidc\",\"Domains\":null,\"LifetimeString\":43200,\"Path\":\"/_oauth\",\"Whitelist\":[\"redacted@example.com\"],\"Providers\":{\"Google\":{\"ClientID\":\"\",\"Scope\":\"\",\"Prompt\":\"\",\"LoginURL\":null,\"TokenURL\":null,\"UserURL\":null},\"OIDC\":{\"Config\":{\"ClientID\":\"redacted\",\"ClientSecret\":\"redacted\",\"Endpoint\":{\"AuthURL\":\"https://gitlab.com/oauth/authorize\",\"TokenURL\":\"https://gitlab.com/oauth/token\",\"AuthStyle\":0},\"RedirectURL\":\"\",\"Scopes\":[\"openid\",\"profile\",\"email\"]},\"IssuerURL\":\"https://gitlab.com\",\"ClientID\":\"redacted\"}},\"Rules\":{},\"Lifetime\":43200000000000,\"CookieDomainsLegacy\":null,\"CookieSecureLegacy\":\"\",\"ClientIdLegacy\":\"\",\"PromptLegacy\":\"\"}"

time="2020-02-17T15:22:03Z" level=info msg="Listening on :4181"

time="2020-02-17T15:24:23Z" level=debug msg="Authenticating request" headers="map[Accept:[text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8] Accept-Encoding:[gzip, deflate, br] Accept-Language:[en-US,en;q=0.5] Cookie:[_forward_auth=QukNvOaeDrdgPha876Pdn9EyRmLEfFcrJqqctDUO2MM=|1581995233|] Dnt:[1] Upgrade-Insecure-Requests:[1] User-Agent:[Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0] X-Forwarded-For:[192.168.2.254] X-Forwarded-Host:[example.com] X-Forwarded-Method:[GET] X-Forwarded-Port:[443] X-Forwarded-Proto:[https] X-Forwarded-Server:[cd8bb7cff384] X-Forwarded-Uri:[/] X-Real-Ip:[redacted]]" rule=default source_ip=redacted

time="2020-02-17T15:24:23Z" level=error msg="Invalid email" email= source_ip=redacted
```

This is my docker-compose:
```
  traefik-oauth:
    container_name: traefik-oauth
    image: thomseddon/traefik-forward-auth:2.1-arm
    environment:
      - DEFAULT_PROVIDER=oidc
      - PROVIDERS_OIDC_ISSUER_URL=https://gitlab.com
      - PROVIDERS_OIDC_CLIENT_ID=<redacted>
      - PROVIDERS_OIDC_CLIENT_SECRET=<redacted>
      - SECRET=<redacted>
      - WHITELIST=<redacted>@users.noreply.gitlab.com
      - COOKIE_DOMAIN=example.com
      - LOG_LEVEL=debug
    networks:
      - proxy-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.oauth-secured.loadbalancer.server.port=4181"
      - "traefik.http.routers.oauth-secured.entrypoints=web-secured"
      - "traefik.http.routers.oauth-secured.rule=Host(`auth.example.com`)"
      - "traefik.http.routers.oauth-secured.tls.certresolver=mytlschallenge"
```

These are my GitLab settings:
![image](https://user-images.githubusercontent.com/6831735/74665826-b3b7b600-51a0-11ea-81a1-eb4ab8f15864.png)

I should also note that my profile and e-mail address are all set to public on GitLab.
