### ISSUE TITLE
How to add as frontend rule?

### ISSUE THREAD

**Issue by Berndinox** [thomseddon/traefik-forward-auth#9]
i would like to replace my Basic auth with oauth, is there a frontend rule?

```
        #- "traefik.frontend.auth.basic=user:super-secret"
        - "traefik.frontend.auth.forward=http://forward-oauth:4181"
```

**Comment by thomseddon** [comment]
Hi,

Yes, I believe this can be done using the following rule:
```
traefik.frontend.auth.forward.address=http://forward-oauth:4181
```

I lifted this from the traefik docs: https://docs.traefik.io/configuration/backends/docker/

**Comment by HedgeShot** [comment]
@Berndinox @thomseddon
Hi, I was wondering if you could make it work using labels?
I get an error 500 when trying with the following config.

```
# Traefik Reverse Proxy
  traefik:
    hostname: traefik
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    domainname: ${DOMAINNAME}
    networks:
      - default
      - traefik_proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - NAMECOM_USERNAME=${NAMECOM_USERNAME}
      - NAMECOM_API_TOKEN=${NAMECOM_API_TOKEN}
      - NAMECOM_SERVER=${NAMECOM_SERVER}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.${DOMAINNAME}"  
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=DOMAIN.COM"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.auth.basic.usersFile=/shared/.htpasswd"
#      - "traefik.frontend.auth.basic.removeHeader=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${USERDIR}/docker/traefik:/etc/traefik
      - ${USERDIR}/docker/shared:/shared
# NZBHydra – NZB Meta Search
  hydra:
    image: "linuxserver/hydra"
    container_name: "hydra"
    volumes:
      - ${USERDIR}/docker/hydra:/config
      - /nfs/Multimedia/Downloads:/downloads
      - ${USERDIR}/docker/shared:/shared
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=hydra"
      - "traefik.frontend.rule=Host:hydra.${DOMAINNAME}"
      - "traefik.port=5075"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=DOMAIN.COM"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=false"
      #- "traefik.frontend.auth.basic.usersFile=/shared/.htpasswd"
      - "traefik.frontend.auth.forward=http://forward-oauth:4181"

forward-oauth:
    image: thomseddon/traefik-forward-auth
    environment:
      - CLIENT_ID=${GOOGCLIENTID} 
      - CLIENT_SECRET=${GOOGCLIENTSEC} 
      - COOKIE_SECRET=${COOKIESECRET}
      - COOKIE_SECURE=false
      - DOMAIN=DOMAIN.COM
      - AUTH-HOST=auth.DOMAIN.COM
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=forward-oauth"
      - "traefik.frontend.rule=Host:auth.DOMAIN.COM"
      - "traefik.port=4181"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=DOMAIN.COM"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=false"
```
