### ISSUE TITLE
Redirected Too Many Times Problem - Traefik file config +  docker-compose setup

### ISSUE THREAD

**Issue by gcavalcante8808** [thomseddon/traefik-forward-auth#99]
Hi Folks,

I'm trying to create a local setup but after I enter my credentials on google and get redirect back, the   the `traefik-forward-auth` app redirect me to **auth0** and that creates a too many redirects loop.

I'm using the following configuration:
```
version: '3'
services:
  gateway:
    build: gateway
    command: traefik --log.level DEBUG --log true
    ports:
      - "9000:80"
      - "9090:8080"

  opa:
    build: opa
    ports:
      - "8181:8181"

  auth-dummy:
    build: gateway-middlewares/auth-dummy
    tty: true

  auth-oidc:
    image: thomseddon/traefik-forward-auth:2
    command:
    - --providers.oidc.issuer-url=${OIDC_ISSUER_URL:?err}
    - --providers.oidc.client-id=${OIDC_CLIENT_ID:?err}
    - --providers.oidc.client-secret=${OIDC_SECERT:?err}
    - --secret=${COOKIE_SECRET:-`openssl rand -hex 16`}
    - --default-provider=oidc
    - --log-format=json
    - --log-level=debug
    - --insecure-cookie

  auth-opa:
    build: gateway-middlewares/auth-opa

  api-1:
    build: apps/api-1
    tty: true
```

Traefik 2.2 dynamic.yaml configuration:

```
http:
  routers:
    api-1:
      rule: "PathPrefix(`/api-1`)"
      service: api-1
      middlewares:
      - "oidc-auth"
      - "dummy_auth"
      - "opa-authz"
    oauth:
      rule: "PathPrefix(`/_oauth`)"
      service: oauth
  middlewares:
    oidc-auth:
      forwardAuth:
        address: "http://auth-oidc:4181"
    dummy_auth:
      forwardAuth:
        address: "http://auth-dummy:5000"
    opa-authz:
      forwardAuth:
        address: "http://auth-opa:5000"
  services:
    api-1:
      loadBalancer:
        servers:
        - url: http://api-1:5000
    oauth:
      loadBalancer:
        servers:
        - url: http://auth-oidc:418
```

In the `traefik-forwarded-auth` logs I can see the following: 
```
{'level': 'debug', 'msg': 'Starting with options: {"LogLevel":"debug","LogFormat":"json","AuthHost":"","CookieDomains":[{"Domain":"localhost","DomainLen":9,"SubDomain":".localhost","SubDomainLen":10}],"InsecureCookie":true,"CookieName":"_forward_auth","CSRFCookieName":"_forward_auth_csrf","DefaultAction":"auth","DefaultProvider":"oidc","Domains":null,"LifetimeString":43200,"Path":"/_oauth","Whitelist":null,"Providers":{"Google":{"ClientID":"","Scope":"","Prompt":"","LoginURL":null,"TokenURL":null,"UserURL":null},"OIDC":{"Config":{"ClientID":"<redacted>","ClientSecret":"<redacted>","Endpoint":{"AuthURL":"https://dev-uydokoit.auth0.com/authorize","TokenURL":"https://dev-uydokoit.auth0.com/oauth/token","AuthStyle":0},"RedirectURL":"","Scopes":["openid","profile","email"]},"IssuerURL":"https://dev-uydokoit.auth0.com/","ClientID":"<redacted>"}},"Rules":{"1":{"Action":"allow","Rule":"Path(`/`)","Provider":"oidc"}},"Lifetime":43200000000000,"CookieDomainsLegacy":null,"CookieSecureLegacy":"","ClientIdLegacy":"","PromptLegacy":""}', 'time': '2020-04-13T01:20:30Z'}
```
```
auth-oidc_1   | {"headers":{"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"],"Accept-Encoding":["gzip, deflate"],"Accept-Language":["pt-BR,pt;q=0.8,en-US;q=0.5,en;q=0.3"],"Cache-Control":["no-cache"],"Cookie":["_forward_auth_csrf=43fde01e855b6ee0038b66272862fdcb"],"Pragma":["no-cache"],"Upgrade-Insecure-Requests":["1"],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"],"X-Forwarded-For":["172.20.0.1"],"X-Forwarded-Host":["localhost:9000"],"X-Forwarded-Port":["9000"],"X-Forwarded-Proto":["http"],"X-Forwarded-Server":["727b4fa3210a"],"X-Real-Ip":["172.20.0.1"]},"level":"debug","msg":"Authenticating request","rule":"default","source_ip":"172.20.0.1","time":"2020-04-13T00:20:36Z"}
auth-oidc_1   | {"level":"debug","msg":"Set CSRF cookie and redirecting to google login","source_ip":"172.20.0.1","time":"2020-04-13T00:20:36Z"}
auth-oidc_1   | {"level":"debug","msg":"Done","source_ip":"172.20.0.1","time":"2020-04-13T00:20:36Z"}
auth-oidc_1   | {"headers":{"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"],"Accept-Encoding":["gzip, deflate"],"Accept-Language":["pt-BR,pt;q=0.8,en-US;q=0.5,en;q=0.3"],"Cache-Control":["no-cache"],"Cookie":["_forward_auth_csrf=9682a1bfc454a3478b2a8c39cb8a075c"],"Pragma":["no-cache"],"Upgrade-Insecure-Requests":["1"],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"],"X-Forwarded-For":["172.20.0.1"],"X-Forwarded-Host":["localhost:9000"],"X-Forwarded-Port":["9000"],"X-Forwarded-Proto":["http"],"X-Forwarded-Server":["727b4fa3210a"],"X-Real-Ip":["172.20.0.1"]},"level":"debug","msg":"Authenticating request","rule":"default","source_ip":"172.20.0.1","time":"2020-04-13T00:20:36Z"}
auth-oidc_1   | {"level":"debug","msg":"Set CSRF cookie and redirecting to google login","source_ip":"172.20.0.1","time":"2020-04-13T00:20:36Z"}
auth-oidc_1   | {"level":"debug","msg":"Done","source_ip":"172.20.0.1","time":"2020-04-13T00:20:36Z"}
```
For me, looks like that auth0 made its part; I can see the following entries on the browser network tool:

![image](https://user-images.githubusercontent.com/640897/79083708-48a0e080-7d06-11ea-8057-a462ddaccf92.png)

For each time that the auth0 redirect me back to the `localhost:9000/_oauth` endpoint I get redirected back to Auth0 Page but I have the cookie installed, soh I get redirected back for oauth endpoint and so on.

What I missing in the setup?

Thanks in advance.
